### ISSUE TITLE
parseModuleEx incorrectly allows invalid source code such as "main = do" and "do"

### ISSUE THREAD

**Issue by vaibhavsagar** [ndmitchell/hlint#1014]
`parseModuleEx` seems to be incorrectly allowing invalid Haskell source code, which makes interactive use (as in https://github.com/ndmitchell/hlint/issues/144) difficult.

```haskell
λ> import Language.Haskell.HLint 
λ> (flags, classify, hint) <- autoSettings
λ> Right mods <- parseModuleEx flags "-" (Just "main = do")
λ> applyHints classify hint [mods]
*** Exception: Prelude.init: empty list
```

```haskell
λ> import Language.Haskell.HLint 
λ> (flags, classify, hint) <- autoSettings
λ> Right mods <- parseModuleEx flags "-" (Just "do")
λ> applyHints classify hint [mods]
*** Exception: Prelude.init: empty list
```

Is this a bug or am I using the API incorrectly?

**Comment by ndmitchell** [comment]
Thanks for the report @vaibhavsagar. There are two issues here - you should have got `Left` not `Right` to specify a parse error, and then even if you had got as far as `applyHints`, you shouldn't have got an `init` on empty list. I've just pushed a fix for the second of those issues - does that solve your problem? If it does, I'll roll a release.

For the first, I have no idea why we don't get a parse error. @shayne-fletcher - any idea? I tried enabling no extensions, and it still gave a passing parse tree. We are checking both the return code and the errors in the state. Is there somewhere else we should be checking? Or do things like empty do blocks get raised as type errors?

**Comment by shayne-fletcher** [comment]
@ndmitchell Indeed, parsing is successful. In this case, the absence of statements in the `do` block is discovered during renaming.
```haskell
-- GHC.Rename.Expr.hs

checkEmptyStmts :: HsStmtContext GhcRn -> RnM ()
-- We've seen an empty sequence of Stmts... is that ok?
checkEmptyStmts ctxt
  = unless (okEmpty ctxt) (addErr (emptyErr ctxt))
```

**Comment by ndmitchell** [comment]
Then I guess that's just how we expect GHC parsing to work. Although it does seem odd, since morally it's definitely a parse error.

**Comment by shayne-fletcher** [comment]
I'm afraid that yes, that's just the way it works. I agree it's unfortunate corner case 😞

**Comment by ndmitchell** [comment]
OK. Slightly annoying, but shouldn't be too fatal. @vaibhavsagar - can you confirm that having it a parse success but then not throwing an error when checking it is sufficient for you?

**Comment by vaibhavsagar** [comment]
I've worked around both issues for now [using `try` and `evaluate`](https://github.com/vaibhavsagar/experiments/commit/68a79d1485a172c0e6ebbcaf49fbe9c30cefb556#diff-9d3e22f7f11a0d70435fd1e32c7b9f19R53-R54), so I'm not blocked. Thank you for looking into this so quickly!

**Comment by ndmitchell** [comment]
I just released HLint 3.1.2 which should make the try/evaluate combo unnecessary. It will treat `main = do` like a parse success, but everything will work with it.

**Comment by ndmitchell** [comment]
I've also added a comment on `parseModuleEx` to note that it's the "expected" behaviour.

**Comment by vaibhavsagar** [comment]
Thank you!
