### ISSUE TITLE
parse error since update

### ISSUE THREAD

**Issue by dten** [ndmitchell/hlint#1031]
```
module ModuleName where

data Type = TypeA { } | TypeB { }

f a = case a of
  i @ TypeA {} -> undefined
  _ -> undefined
```

results in 

```
6:3 - Error Parse error: Expression syntax in pattern: i @TypeA
```

somewhere between v2.2.11 (which i came from) and now 3.1.4

removing the space around the `@` fixes it

**Comment by googleson78** [comment]
Related: https://github.com/ndmitchell/hlint/issues/999

**Comment by dten** [comment]
ah so it will be an error in 8.10. i'll just change the code and close this then :) thanks
