### ISSUE TITLE
"Use hierarchical imports" - still needed?

### ISSUE THREAD

**Issue by zliu41** [ndmitchell/hlint#1033]
There are hints suggesting hierarchical imports, such as
```
import List -- import Data.List
```
Are they still needed? I can't find a module named "List" or "Monad" in base (or anywhere). Maybe they existed a long time ago?

**Comment by ndmitchell** [comment]
Good spot - these can be deleted

**Comment by googleson78** [comment]
Is it fine to ask what the original motivation is? (curiosity)

**Comment by ndmitchell** [comment]
In the before times Haskell didn't support module names with `.` in them, eg. its an addition after-the-fact to Haskell98. Therefore base shipped with `List`, `IO` etc. Time went by, people realised that people only like long module names if they can put a dot in them (e.g. Data_List everyone frowns at, Data.List is just fine, humans are weird). Then the modules moved and List was there for compat, so HLint advised you to move over. And then, sometime later, List got deleted, so its no longer an interesting hint.

**Comment by zliu41** [comment]
Good to know! That must be ancient history - even base 3.0.3 doesn't seem to have `List`.

**Comment by ndmitchell** [comment]
Yeah, I think this code is at least a decade old - HLint as a whole is 14 years old.
