### ISSUE TITLE
Whitespace sensitive operator lexing

### ISSUE THREAD

**Issue by shayne-fletcher** [ndmitchell/hlint#1061]
It might be worth considering writing some rules to provide hints for writing stable code in the presence of language extensions. For example, `x.y` is function composition but will become field projection in the presence of `RecordDotSyntax`. Given how we default enable most extensions this may or may not be a useful idea.

**Comment by shayne-fletcher** [comment]
To provide a concrete starter idea, if `RecordDotSyntax` is not enabled, warn on uses of `.` not surrounded by whitespace.

**Comment by ndmitchell** [comment]
Given RecordDotSyntax hasn't even been finished yet, this seems premature. If it becomes popular, then maybe, but for the moment, I can't imagine every lens user would thank us - as this style is very common with lens.

**Comment by shayne-fletcher** [comment]
I thought it might have value as a "forward compatibility" hint but fair. What about, if template haskell is not enabled, and we see `$` and `(` with no intervening whitespace?

**Comment by shayne-fletcher** [comment]
Of course, just floating the idea for discussion. If we don't think it has legs that's fine, we can close :)

**Comment by shayne-fletcher** [comment]
> I can't imagine every lens user would thank us - as this style is very common with lens.

Very good point.

**Comment by shayne-fletcher** [comment]
Shelving this for now. Perhaps reconsider if problems that this sort of thing might solve become prevalent.

**Comment by ndmitchell** [comment]
I think if they do `$(` they'll find out super quickly, because HLint won't work for them. It's a nice idea, but I'm not sure there are any high value problems it tackles at the moment.

**Comment by shayne-fletcher** [comment]
Yes, with this discussion have reached the same conclusion. That and your pointing out how this would affect e.g. lens means it's a potential minefield with deeper consequences than is immediately obvious.
