### ISSUE TITLE
QuasiQuote parse error on input

### ISSUE THREAD

**Issue by razvan-flavius-panda** [ndmitchell/hlint#1068]
Using the package: https://hackage.haskell.org/package/neat-interpolation-0.3.2.1/docs/NeatInterpolation.html

With code:

```haskell
f :: T.Text
f =
  [text|
    function(){
      function(){
      }
    }
  |]
```

it shows the error:

```
/tmp/haskell-lsp59186/Debian.hs-00000-4856614137838069181.hs:107:15: error:
    parse error on input `('
    [text|
      function(){
> function(){
        }
      }
```

**Comment by jorpic** [comment]
Seems like you need to enable `QuasiQuotes` extension.
Try `hlint -X QuasiQuotes . ` or use `{-# LANGUAGE QuasiQuotes #-}` pragma.

**Comment by razvan-flavius-panda** [comment]
@jorpic this issue is not related to the code, the code compiles and the language extension is enabled in the `.cabal` file.

I am using the Haskell IDE Engine so I am not calling HLint myself.

**Comment by ndmitchell** [comment]
An issue for the Haskell IDE Engine team then - it seems they aren't passing QuasiQuotes from the .cabal file properly.

**Comment by razvan-flavius-panda** [comment]
@ndmitchell Thank you, I passed that to them.

**Comment by BiscuitCookies** [comment]
This was not fixed in the IDE engine before archival.
I'm seeing the same error with QuasiQuotes in the extensions in the .cabal file.
