### ISSUE TITLE
Fix --quickcheck tests on GHC 7.10

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/hlint#107]
Currently they fail because things like foldr/foldl are too polymorphic. I should have a Mono module that overrides things like foldr with a concrete type.

**Comment by kk-hainq** [comment]
@ndmitchell I think we can close this issue now after 77600418b5d254124fd735386ea44e6de571b26f?

**Comment by ndmitchell** [comment]
Yep, thanks!
