### ISSUE TITLE
Multiple notes on the same hint

### ISSUE THREAD

**Issue by josephcsible** [ndmitchell/hlint#1079]
What's the proper syntax to put multiple notes on the same hint? I ask because I just discovered that the hint I added `IncreasesLaziness` to in #1053 also needs `DecreasesLaziness`: `zip (take 0 []) (take undefined [])` is `[]`, but `take (min 0 undefined) (zip [] [])` bottoms.

**Comment by ndmitchell** [comment]
I'd just put them in a list, e.g. `note: [IncreasesLaziness, DecreasesLaziness]`. I don't guarantee it will work, but if it doesn't, I'll happily accept a PR or feature request (but I suspect it may just work),

**Comment by josephcsible** [comment]
That works!
