### ISSUE TITLE
Parse error with PatternSynonyms extension

### ISSUE THREAD

**Issue by jaseemabid** [ndmitchell/hlint#109]
Hlint is giving potentially wrong warning for the following code. Complete
source [here](https://github.com/jaseemabid/lisper/commit/d470bfd18cfdc8f835eef5082347bcd5565301c4#diff-b68291379a7e7b433673ce7b677ebe30R33).

In general does hlint work with `{-# LANGUAGE PatternSynonyms #-}` ??

Code:

    pattern If predicate conseq alt = List [Atom "if", predicate, conseq, alt]
    pattern Defun name args body = List [Atom "defun", Atom name, List args, body]
    pattern Let args body = List [Atom "let", args, body]
    pattern Quote = Atom "quote"
    pattern Set var val = List [Atom "set!", (Atom var), val]

Warning:
    
    src/Core.hs:38:1: Warning: Parse error: arity mismatch for 'pattern'
    Found:
        pattern Let args body = List [Atom "let", args, body]
      > pattern Quote = Atom "quote"
        pattern Set var val = List [Atom "set!", (Atom var), val]
    
    
    1 suggestion

**Comment by ndmitchell** [comment]
This is an issue with the underlying parser library haskell-src-exts, I've reraised the ticket for them: https://github.com/haskell-suite/haskell-src-exts/issues/194. It does support pattern synonyms, but not completely it seems.

**Comment by jaseemabid** [comment]
@ndmitchell Thanks. So lets keep this bug open till it gets fixed upstream?

**Comment by ndmitchell** [comment]
Yep, that's the plan (I even have a special tag for those bugs in HLint).

**Comment by mpickering** [comment]
I'm pretty sure that HSE doesn't support pattern synonyms. Patterns such as  `pattern (A a) = Just a` don't cause parse errors because it is parsed as a function declarations.

**Comment by ndmitchell** [comment]
@mpickering yes, you're right of course :) - I've noted that on the HSE bug.

**Comment by jaseemabid** [comment]
Can we close this, since https://github.com/haskell-suite/haskell-src-exts/issues/194 got closed?

**Comment by ndmitchell** [comment]
Sure. I sometimes wait until after the corresponding HSE release, but the only real reason for having these tickets are so HLint users have somewhere to report it.

**Comment by jaseemabid** [comment]
:+1:
