### ISSUE TITLE
`hlint -g .` does not respect .gitignore

### ISSUE THREAD

**Issue by donatello** [ndmitchell/hlint#1090]
In my repo directory, I have `dist-newstyle` created by cabal in my gitignore, however `hlint -g` goes into this directory and returns lint errors for sources checkout by cabal inside this directory.

As a workaround I am using `git ls-files | grep '.hs$' | xargs hlint`.

**Comment by ndmitchell** [comment]
On my machine it runs `git ls-files --cached --others --exclude-standard *.hs *.lhs`. What does that command return on your machine? (You probably need to quote the `*`). I just pushed changes to `--verbose` so `hlint -g -v` shows what command it runs, if you want to try HEAD.

**Comment by ndmitchell** [comment]
Ah, I think `hlint -g .` is saying test all files found by `--git` AND test all files found by `.` - together which is everything. As it happens #780 was fixed a few days ago, which likely means that `.` will start ignoring `dist-newstyle` anyway.

**Comment by donatello** [comment]
Ah I see, I didn't realize that providing a directory/file argument was optional, but it's clear from the `--help` message now. `hlint -g` works fine for me. Closing this. Thanks your quick response!
