### ISSUE TITLE
hlint outputting multiline code references `MySource.hs:(104,1)-(105,49): `

### ISSUE THREAD

**Issue by juhp** [ndmitchell/hlint#1095]
Recently hlint (I am using hlint-3.1.6) sometimes outputs codeline ranges for its hints.
This "breaks" comint (compile-mode) error line detection in Emacs for example.

Is there some way to unconfigure this or change the output format perhaps to be more backwards compatible?
Are other IDEs more flexible about this - maybe I need to teach emacs to parse this type of line reference...

Been hitting this sometimes lately - so thought I would ask about it here first before investigating further.

**Comment by ndmitchell** [comment]
It now reuses the GHC pretty-printing code for multi-line formats, and in some cases we have better tracking of locations, so I can certainly imagine it happens more. My suggestion would be to fix Emacs itself, as then you'll get range locations in GHC, which I've found very valuable for debugging errors.

Of course, if that's difficult, I could imagine a flag to change the rendering - although it wouldn't be trivial to plumb in and seems sad to lose the extra info.

**Comment by juhp** [comment]
Okay, thanks Neil, that's totally fair - I'll look into the emacs side next time I hit it.
