### ISSUE TITLE
Suggestion for Map.fromList []

### ISSUE THREAD

**Issue by ayakovlenko** [ndmitchell/hlint#111]
HLint doesn't show suggestion for `Map.fromList []`. It could suggest using `Map.empty`.

**Comment by ndmitchell** [comment]
Seems like a good idea. Not sure I have any containers based suggestions yet, but a good time to start.

**Comment by hellerve** [comment]
Hey! Is this issue still open and is there still interest in getting this merged in? I’d like to start diving into the codebase and maybe contribute back and this seems like a simple enough thing to get started!

**Comment by ndmitchell** [comment]
Still open, still reasonable - PR welcome :)

**Comment by ndmitchell** [comment]
No problem at all @hellerve - I hope you found the investigation interesting at least.
