### ISSUE TITLE
Ugly refactor for `x >>= pure . f` when x is large

### ISSUE THREAD

**Issue by expipiplus1** [ndmitchell/hlint#1112]
The original isn't great, but I think the suggested refactoring is a little worse. Would it be sensible to restrict this rule from firing when `x` contains newlines or would rely on the parse error rule?

I don't think I've noticed such a content sensitive rule in the lints before, so perhaps it's not in the spirit of the library.

```haskell
runTravWithTravState state traversal =
    unTravT traversal state >>= pure . \case
        Left trav_err                                 -> Left [trav_err]
        Right (v, ts) | hadHardErrors (travErrors ts) -> Left (travErrors ts)
                      | otherwise                     -> Right (v,ts)
```

goes to

```haskell
runTravWithTravState state traversal =
    (\case
        Left trav_err                                 -> Left [trav_err]
        Right (v, ts) | hadHardErrors (travErrors ts) -> Left (travErrors ts)
                      | otherwise                     -> Right (v,ts)) <$> unTravT traversal state
```

**Comment by googleson78** [comment]
Another idea is to recommend `(<&>)` instead

**Comment by expipiplus1** [comment]
Oh of course! That's my go-to fix for this I'd forgotten :D

**Comment by ndmitchell** [comment]
Sounds like a great idea.  Someone want to send a patch?

**Comment by expipiplus1** [comment]
done, did what seemed obvious in hlint.yaml, hopefully that's all that there is to it.
