### ISSUE TITLE
Direct application of a Hint to a source AST

### ISSUE THREAD

**Issue by tonyday567** [ndmitchell/hlint#112]
refer chrisdone/hindent#75 for context.

By the time a Hint turns into an Idea, (haskell-src-ext) ast information is lost, with ideaFrom being a String. 

Would it be possible to have something like `Decl SrcSpanInfo -> Hint -> Decl SrcSpanInfo` as part of the library? Or any other method where you could keep manipulations at the ast level?

**Comment by ndmitchell** [comment]
Hmm. HLint doesn't always suggest `Decl -> Decl` transformations, and sometimes even when it does some aspects of the `Decl` get elided for display, which currently happens at the point the hint is generated, not at the point of display. I'll think if we can do anything to retain some of the structure.

**Comment by tonyday567** [comment]
I'm assuming that a hlint was ast -> ast at least, and that original comments and formatting is best preserved in that amber.  But maybe String -> String is the more practical approach.

**Comment by ndmitchell** [comment]
Most of the hints are AST -> AST, but it's often different types of AST. Some hints work on Exp, some on Decl, some on Stmt. Some work on Decl but also elide some of the output. To give a single consistent view, I normalise all hints to being String -> String before putting them in a data structure. I'll think about how feasible it is to preserve more information.

**Comment by ndmitchell** [comment]
We now produce refactoring information through a different route, with the refactor library, so I recommend using that as diffs onto the whole AST.
