### ISSUE TITLE
Make test not a separate subcommand

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/hlint#1124]
Currently `hlint lint foo` runs linting on `foo`, `hlint test` runs the tests, and `hlint foo` implicitly defaults to lint. I think we should make `hlint` a non-mode command line program, and use `hlint --test` to invoke hints. Based on ideas from https://github.com/ndmitchell/hlint/issues/1048#issuecomment-643793928

**Comment by ndmitchell** [comment]
Note that removing `test` is probably fine (impacts dev users). Removing lint might mean that some people who have correctly passed `hlint lint $X` suddenly break. A possible solution is to ignore an initial `lint` if its not the name of a directory - a bit grim, but avoids too much breakage.

**Comment by shayne-fletcher** [comment]
> ... use `hlint --test` to invoke hints

I'm reading that as a typo where you meant to say 'tests'.

**Comment by ndmitchell** [comment]
> I'm reading that as a typo where you meant to say 'tests'.

Yep :)

**Comment by ndmitchell** [comment]
Done - now use `--test` to run the tests.
