### ISSUE TITLE
How to prevent an entire hierarchy of modules from being imported?

### ISSUE THREAD

**Issue by peti** [ndmitchell/hlint#1125]
I would like to ensure that my code does not import any module from the `Cabal` library anywhere (except for my own `MyCabal` module). How can I configure this without having to list every single Cabal module explicitly? I tried

~~~
- modules:
  - { name: Distribution, within: [MyCabal] }
~~~

but this doesn't seem to work. Neither will

~~~
- modules:
  - { name: Distribution.*, within: [MyCabal] }
~~~

Is there an alternative syntx to accomplish this by any chance?

**Comment by ndmitchell** [comment]
The plan was for `Distribution.**` to work using the filepattern library. #402 is the work tracking that.

**Comment by peti** [comment]
Closing as a duplicate.
