### ISSUE TITLE
Unicode literals gets flagged

### ISSUE THREAD

**Issue by nitinprakash96** [ndmitchell/hlint#1155]
This is not exactly a bug but more of a versioning issue.
GHC extended it's unicode support in `v8.8.3`.

But, hlint with `v8.6.5` keeps flagging a lot of unicode literals. Eg:
The following will be flagged by hlint but gets compiled with ghc`v8.8.3`
```haskell
main = putStrLn "Thinking about what to eat for lunch? 🥦🥬🥗 "
```
The error produced by hlint:
```
Error: Parse error: lexical error in string/character literal at character '\129382'
```

Is there any update when the version bump might take place?

**Comment by ndmitchell** [comment]
You are welcome to build HLint with a newer version - what is pinning you to 8.6.5? Are you referring to the stack.yaml? In general, Windows and GHC has been a complete disaster zone for the last few releases. 8.6.5 is the last reliable one.

**Comment by nitinprakash96** [comment]
> You are welcome to build HLint with a newer version - what is pinning you to 8.6.5? Are you referring to the stack.yaml?

Yes, I was referring to stack.yml. Isn't that the same version that gets pulled when running in CI? Locally, it seems to be fine with later LTS.


> In general, Windows and GHC has been a complete disaster zone for the last few releases. 8.6.5 is the last reliable one.

Ah I see. This clears my confusion around this. Just wanted to make sure 😄

**Comment by ndmitchell** [comment]
We have two sets of CI - one with Linux which uses Cabal and multiple GHC versions, and one with Windows, that uses this Stack.
