### ISSUE TITLE
Reexport SrcSpan?

### ISSUE THREAD

**Issue by mvoidex** [ndmitchell/hlint#1158]
Hi! Since `hlint` doesn't export `SrcSpan`, one have to depend on `ghc-lib-parser` to deconstruct it. If you also depend on `ghc` or `ghc-lib`, you'll have many ambiguous imports. `PackageImports` may be used to resolve conflict, but won't be it better to have something like `HLint.SrcLoc` module?

**Comment by ndmitchell** [comment]
Is unpackSrcSpan enough for you? That lets you decompose all the parts you might need with no additional dependencies.

**Comment by mvoidex** [comment]
Oh, I didn't notice this function. It will be enough, thanks!
