### ISSUE TITLE
Expose Idea pretty-printing functions (showEX/showANSI)

### ISSUE THREAD

**Issue by Fuuzetsu** [ndmitchell/hlint#1160]
If you use hlint as a library the main entry point is `hlint` function. However, you're in trouble if you want to react to the resulting `Idea`s somehow. In our use-case, we want to only print the hints for lines touched in the current working git diff.

So far we've been parsing the `--json` output and filtering that against some ranges. Trying to use the library, means that either:

* hlint prints everything (we don't want this)
* hlint prints nothing with --quiet but you have to pretty out the resulting hints

If you just use `show`, it uses the `show = showEx id` instance which means all the colouring is lost. I suppose `showANSI` or even `showEX` functions would be nice to have so that not much of code has to be copy-pasted.

**Comment by ndmitchell** [comment]
Thanks for the diff - I'll reply to it here. I think exposing showANSI is fine, modulo two concerns:

1. It doesn't have the word Idea in its name, and it doesn't show any type of thing as ANSI. I renamed it showIdeaANSI.
2. The current version is in IO so it can read the hscolour preferences file. While I'm OK with HLint doing that, I don't want to expose an API where it queries the existence of a weird file no one expects. I wrote an alternative that uses default preferences.

Does that still answer all your requests?

**Comment by Fuuzetsu** [comment]
>It doesn't have the word Idea in its name, and it doesn't show any type of thing as ANSI. I renamed it showIdeaANSI.

Cool. Personally I think a better solution would be to make the module with Idea exposed (maybe marked with .Internal) and then we don't have to worry about naming. Users can import qualified if they'd like. This would also help with the following discussion:

>The current version is in IO so it can read the hscolour preferences file. While I'm OK with HLint doing that, I don't want to expose an API where it queries the existence of a weird file no one expects. I wrote an alternative that uses default preferences.

The reason why I wanted `showEx` initially but then just `showANSI` was so I could do whatever HLint binary does: after all, that was my goal except I also wanted it to filter a few of the ideas out. Now that only `hsColourConsolePure` variant is used puts us back to where we were: we can't render in same way that hlint would do. We can't recover the behaviour either because `showEx` is still private.

So the situation is better (and indeed for us where we don't have .hscolour file: it works) but in attempt to not expose some API, it became impossible to mimic the binary.

So ideally either:

* expose `showEx` from the Idea module: this allows to re-implement either variant of showANSI

or

* expose both `showANSI` and `showIdeaANSI` perhaps after some renaming. `showANSI` is currently hlint internal so rename shouldn't matter.

Having said that, these are only minor complaints because `showIdeaANSI` happens to work for us. It's a shame that a lot of the code is outright inaccessible behind private modules however. `showANSI` was one example, some other was code that processed SrcLocs into line numbers and so on. Non-polished API would probably have been much better than no API at all. 

Feel free to do nothing about this issue though I'd love if more parts of the code were exposed even if they don't seem like perfect API.

**Comment by ndmitchell** [comment]
I realise there is a Haskell movement to expose the internals with `.Internal`. I don't like it, and find it encourages bad practices, broken abstractions and means that people working around your API which means you lack the feedback to fix your API. While others may choose to follow this approach, I don't. If there are specific things you would find useful to be in the API, let me know - usually I'm happy to expose things.

What do you want to do that mimics the HLint binary so precisely? If you really want to be just like HLint, why not just use HLint? But if you've got freedom to be different, I'd take it - if I was writing HLint today I don't think I'd rely on hscolour at all - printing out source code with syntax highlighting isn't what most other linters and compilers do. I doubt any HLint users know about .hscolour files, where to put them, or what their syntax is. I suspect when people do get involved in these files, its to be upset that suddenly a random file appears and HLint breaks. I wish I'd reserved color for the semantically meaningful parts of the message - like the word error/warning/suggestion, just like GHC and Rust do.

**Comment by Fuuzetsu** [comment]
> find it encourages bad practices, broken abstractions and means that people working around your API which means you lack the feedback to fix your API

I agree in principal. In practice though, I think the opposite just encourages copy+pasting of code from inside the library which is probably even worse.

>What do you want to do that mimics the HLint binary so precisely? If you really want to be just like HLint, why not just use HLint? 

I want to do exactly what hlint does down to how it renders the output _except_ that I want to filter out which hints it shows. In our codebase we only show hints for lines of code that were touched in the current branch to avoid the hundreds unfixed lints in rest of codebase. To do this, I have to filter out some of the `Idea`s and I can't do that with the binary (unless I parse stdout) so I need to use the library. When I tried to use the library, I stopped being able to get the same looking output as I got with binary.

>I doubt any HLint users know about .hscolour files, 

Neither did I.

>printing out source code with syntax highlighting isn't what most other linters and compilers do

FWIW I like it. It's your tool though so you can do whatever you want with it of course, I'm not trying to put pressure on any features.

**Comment by ndmitchell** [comment]
Cool - filtering out unchanged lines does seem like a valid application for writing your own "a lot like HLint but not quite" program. I wouldn't say there are many, but that is one!

I don't want to expose the colour preference thing, because I don't really think its a very good. I've just pushed a change so that we always use the showIdeaANSI function internally in HLint, which means you can mirror HLint.

For a long time I've wanted to rewrite the HLint binary using only the HLint API, since that seems the right thing to do. Unfortunately, I've never had time. HLint was a program that became an API later, so it has a weird history.
