### ISSUE TITLE
Inspired by python: hint for zipWith [1..]

### ISSUE THREAD

**Issue by pjljvandelaar** [ndmitchell/hlint#1162]
In python the following enumerate function exists: https://www.geeksforgeeks.org/enumerate-in-python/

HLint learned me a lot of nice code improvements including zipWith.
However HLint never suggested zipWith [n..] to be replaced by such enumerate function.
Maybe this function does not yet exists in Haskell, but if it does I would like HLint to recommend it!

**Comment by ndmitchell** [comment]
Such a function doesn't exist yet. In general HLint only suggests functions from the base library, unless an extra flag is given. There is zipFrom n though, and using `--with-group=extra` it will suggest it.
