### ISSUE TITLE
Wrong suggestion to use newtype instead of data for unboxed payload

### ISSUE THREAD

**Issue by Bodigrim** [ndmitchell/hlint#1166]
```haskell
{-# LANGUAGE MagicHash #-}

import GHC.Exts

data BA    = BA# ByteArray#
data MBA s = MBA# (MutableByteArray# s)
```

```
$ hlint --version
HLint v3.2.1, (C) Neil Mitchell 2006-2020
$ hlint UnboxedPayload.hs
UnboxedPayload.hs:6:1-39: Suggestion: Use newtype instead of data
Found:
  data MBA s = MBA# (MutableByteArray# s)
Perhaps:
  newtype MBA s = MBA# (MutableByteArray# s)
```

However, `newtype` cannot be used here, because the payload `MutableByteArray# s` is unboxed. Applying the suggestion provokes GHC error "Expecting a lifted type, but `MutableByteArray# s` is unlifted".

On the other hand, `hlint` does not suggest to replace `data BA` with `newtype BA`, so it seems to perform some kind of levity analysis?..

**Comment by ndmitchell** [comment]
The "levity analysis" is looking for variables that end with `#`. I've just extended it to look in nested applications, so it won't trigger on these either.

**Comment by Bodigrim** [comment]
Thanks!

**Comment by josephcsible** [comment]
Why did we turn this off altogether instead of just adding a `RequiresExtension UnliftedNewtypes` note for it?

**Comment by ndmitchell** [comment]
I don't know what UnliftedNewTypes does. It also seems reasonable people might want to wrap in a data to get the lifted behaviour.

**Comment by josephcsible** [comment]
> I don't know what UnliftedNewTypes does.

It makes things like `newtype BA = BA# ByteArray#` legal to write. See https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html#extension-UnliftedNewtypes for the full details.

> It also seems reasonable people might want to wrap in a data to get the lifted behaviour.

I think every unlifted type already has such a wrapper though, e.g., `ByteArray#` has `ByteArray`. Putting the former in `data` is exactly equivalent to putting the latter in `newtype`.

**Comment by Bodigrim** [comment]
Suggesting `UnliftedNewtypes` changes semantics, the whole point of `data MBA s = MBA# (MutableByteArray# s)` is to box unboxed data. 

> I think every unlifted type already has such a wrapper though, e.g., `ByteArray#` has `ByteArray`.

There is no boxed `ByteArray` in `base`, it comes from `primitive`.

**Comment by josephcsible** [comment]
Fair points. I was thinking about the case where someone would wrap an unlifted type just for type safety, only using `data` because they didn't know `UnliftedNewtypes` existed. But I suppose that case probably is rare relative to cases like yours.

**Comment by ndmitchell** [comment]
I think many people won't know about the unlifted newtypes. And the data to newtype transition isn't semantics preserving - removes one additional location of errors. But I think given we can't be sure what the user expected, saying nothing is a reasonable way to go.
