### ISSUE TITLE
hie.yaml variants?

### ISSUE THREAD

**Issue by yairchu** [ndmitchell/hlint#1170]
I opened hlint in VS Code, which lately became great for Haskell (thanks btw! ❤️),
and surprisingly, unlike my recent experiences, it did nothing smart (jump to symbol etc) for hlint's own code.
and it seems like what I needed to do to make it work for me was just removing hlint's `hie.yaml` file.

If I understand correctly: some folks use stack, some use cabal, some use nix, some use ghc directly, etc, and HLS or the Haskell extension in VS Code knows how to work with all of them, either by `hie.yaml`, or it seems like if it doesn't exist then it figures it on its own according to what you have installed (or maybe it just defaults to stack?)

How about having an `hie.yaml.cabal` (and possibly other variants too) which folks who use cabal could symlink or locally copy into a `.gitignore`d `hie.yaml`?

**Comment by ndmitchell** [comment]
It used to work terribly without a hie.yaml, but that area of HLS has improved significantly in recent releases. If not having a hie.yaml fixes it, then lets do that.

**Comment by yairchu** [comment]
Note that it does pop open a notification about using an implicit cradle (which I got used to)

**Comment by ndmitchell** [comment]
Does it do that popup notification once per file? I had it doing that at some point, and it was awful.

I think it should really do that popup at most once per project, so if it doesn't, lets file an issue with HLS.

**Comment by yairchu** [comment]
It isn't once per file, tried to check now and it seems like it is *occasionally*.
Perhaps it's per file that wasn't already imported by other files that I edited?

**Comment by ndmitchell** [comment]
Since I do IDE development, I sometimes have stale half-versions lying around, if its occasionally that's fine.

**Comment by ndmitchell** [comment]
Deleted!
