### ISSUE TITLE
Removing brackets may need to insert spaces

### ISSUE THREAD

**Issue by expipiplus1** [ndmitchell/hlint#1179]
Consider:

```haskell
x = do(y)
```

Hlint currently removes the brackets leaving 

```haskell
x doy
```

Seems to happen for all keywords

**Comment by ndmitchell** [comment]
Given:

```
x = do(this is a test)
```

We produce after refactoring:

```
x = dothis is a test
```

Which is driven by the refactoring tool:

```
[("Sample.hs:1:7-22: Suggestion: Redundant bracket\nFound:\n  do (this is a test)\nPerhaps:\n  do this is a test\n",[Replace {rtype = Expr, pos = SrcSpan {startLine = 1, startCol = 7, endLine = 1, endCol = 23}, subts = [("x",SrcSpan {startLine = 1, startCol = 8, endLine = 1, endCol = 
22})], orig = "x"}])]
```

I don't think there's anything else we could send, so I guess this one should be a bug for apply-refact? @zliu41 ?

**Comment by zliu41** [comment]
Yeah this looks like a bug in apply-refact.

**Comment by expipiplus1** [comment]
Ah, makes sense. happy to close this or leave it open as a tracking issue.

**Comment by ndmitchell** [comment]
Let's leave this as a tracking issue.

**Comment by expipiplus1** [comment]
Thanks!
