### ISSUE TITLE
Suggest packaging test directory with release

### ISSUE THREAD

**Issue by ezzieyguywuf** [ndmitchell/hlint#1185]
I am working on packaging hlint for gentoo, and would like to enable the test suite. However, due to the missing test directory (and the missing .hlint.yaml) from the release tarball, I am unable to easily do so.

Is it possible to include everything needed to run tests in the release tarball?

**Comment by ndmitchell** [comment]
No objection to including whatever you want in the tarball. If you have a good idea of what should be included, a PR would be most welcome.

**Comment by ezzieyguywuf** [comment]
That's fantastic, I'll put the PR together.

**Comment by ndmitchell** [comment]
Closed by #1191
