### ISSUE TITLE
Missing parentheses with tuple sections and operator sections

### ISSUE THREAD

**Issue by josephcsible** [ndmitchell/hlint#1196]
HLint will suggest turning `flip (,) (+ 1)` into `(, + 1)`, which is invalid. It should instead turn it into `(, (+ 1))`.

**Comment by ndmitchell** [comment]
Thanks for the report. I note that `map (+ 1) . map (+ 2)` gets the correct suggestion of `map ((+ 1) . (+ 2))` so there must be something a bit funky with just that suggestion... I'll investigate.

**Comment by ndmitchell** [comment]
Thanks! We have to deal with sections properly, and we were in remParen, but not fromParen or fromParen1. I made the latter two delegate to remParen, so hopefully fixed now.
