### ISSUE TITLE
Support for "&" operator (similar to "$")

### ISSUE THREAD

**Issue by yairchu** [ndmitchell/hlint#1201]
hlint knows how to fire rules also when function applications are done indirectly via "$" to reduce parentheses. Since `lens` came along the `&` operator gain popularity, and similar behavior for it will be valuable. I'll gladly implement this given some pointers on where to look :)

**Comment by ndmitchell** [comment]
https://github.com/ndmitchell/hlint/blob/master/src/Hint/Match.hs is the place to look - that has a bunch of comments on $ in various places. But perhaps first you could give some examples you see that you expect to come up? E.g. `concat $ map f x` comes up all the time. Does `map f x & concat` come up similarly?

**Comment by yairchu** [comment]
Someone may write `thing ^? somePrism <&> someFunc & fromMaybe someDefault`, and it would be nice to suggest `maybe someDefault someFunc (thing ^? somePrism)` just as would had happened with `fromMaybe someDefault $ someFunc <$> thing ^? somePrism`

**Comment by ndmitchell** [comment]
Hints which change the order of terms tend to be less useful - if you write `a b c`, sometimes the fact they are in that order is also a meaningful choice. I wonder if `&` by necessity involves changing the order when making suggestions?

**Comment by yairchu** [comment]
As in https://github.com/lamdu/lamdu/commit/621d48a20a65a8b50ad558682991291e4441380a, one would probably end up not changing the order. But even if the hint does change the order it is still useful info to guide towards the end goal. With extra work I suppose the hints could even preserve the order but that's probably much more difficult and also less important.

**Comment by ndmitchell** [comment]
OK, I think I see what the reason to do it would be. Give it a whirl, and let's see how it performs in practice.

**Comment by yairchu** [comment]
> We also see through (.) by translating rules that have (.) equivalents
to separate rules. For example:

Ok, iiuc, this is done by `readRule` invoking `dotVersion` to generate these equivalent rules, right? But as for

> We see through ($)/(.) by expanding it if nothing else matches.

Where is this part performed? It that what `extendInstances` is for?

**Comment by ndmitchell** [comment]
Oh, I think the `$` might actually be performed at https://github.com/ndmitchell/hlint/blob/master/src/GHC/Util/Unify.hs#L174 - back when that comment was written they were probably in the same file :)

**Comment by ndmitchell** [comment]
This is done now with #1204.
