### ISSUE TITLE
Mistakenly labels GeneralizedNewtypeDeriving pragma as unused

### ISSUE THREAD

**Issue by RyanGlScott** [ndmitchell/hlint#121]
I'm using `text-show`, which exports a typeclass called `Show`. When I use this version of `Show` in conjunction with `GeneralizedNewtypeDeriving`, HLint believes that the `GeneralizedNewtypeDeriving` extension isn't needed (as if `text-show`'s `Show` were being derived like `base`'s `Show`) when it actually is. As an example:

```haskell
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
module Main (main) where

import Prelude hiding (Show, print)
import Text.Show.Text (Show, print)

newtype MyInt = MyInt Int deriving Show

main :: IO ()
main = print (MyInt 42)
```

Running `hlint` on this will yield:

```
MyInt.hs:1:1: Error: Unused LANGUAGE pragma
Found:
  {-# LANGUAGE GeneralizedNewtypeDeriving #-}
Why not remove it.

1 suggestion
```

**Comment by mpickering** [comment]
HLint doesn't do name resolution (it is purely syntactic) so I don't think that this will be possible to fix.

**Comment by ndmitchell** [comment]
HLint has some approximate name resolution, and in this case it might actually be enough to figure out that Show /= Prelude.Show, and thus skip the hint.

**Comment by ndmitchell** [comment]
Hmm, it's possible to figure out it's not equal to Prelude.Show, but lots of modules reexport type classes, and in those instances they genuinely won't be equal to Prelude.Show (I count 6 such modules on Hackage), so I don't think there's much I can do about it - unless anyone has any good suggestions?

**Comment by RyanGlScott** [comment]
That's unfortunate, but I can see why this would be difficult to implement. Thanks for looking into it!
