### ISSUE TITLE
Redundant bracket hints on TH splices not compatible with GHC 8.10.3

### ISSUE THREAD

**Issue by yairchu** [ndmitchell/hlint#1212]
Since e2c0833c4a337f78f2cee58ef59d318d26f1666b, `hlint` warns on TH splice such as [`$(Git.hash)`](https://github.com/lamdu/lamdu/blob/82f66bc/src/main/Lamdu/Version.hs#L40):

```
src/main/Lamdu/Version.hs:40:20-29: Warning: Redundant bracket
Found:
  (Git.hash)
Perhaps:
  Git.hash
```

But removing the bracket makes the code not compile on GHC 8.10.3 (and I assume that on older versions as well)

**Comment by ndmitchell** [comment]
Oh dear - that needs investigating - ideally before we make a GHC 9.0 release.

**Comment by RyanGlScott** [comment]
This is a consequence of [GHC proposal 229](https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0229-whitespace-bang-patterns.rst), which GHC 9.0 implements. Previously, GHC would require all Template Haskell splices to be written as `$(x)` or `$$(x)`, where the parentheses were mandatory. After proposal 229, however, GHC only requires `$x` or `$xx`. Put differently, if you write `$(x)` or `$$(x)` in 9.0 or later, then the parentheses are no longer special lexemes, but rather part of the expression being spliced.

As a consequence of this, the parentheses in `$(Git.hash)` are redundant in 9.0 or later, but required in earlier versions of GHC. I'm not sure if there's a way to tell GHC to give advice conditionally based off of what GHC is being used.

**Comment by yairchu** [comment]
So one possible solution could be to add logic to avoid warning about redundant parens in TH splices, which once most users have switched to GHC 9 could be removed. An alternative could be to keep using an older `ghc-lib-parser` version.

**Comment by ndmitchell** [comment]
Using an older ghc-lib-parser is not a real option. We move forward with the times, and want to continue to do so forever.

I've put in a special case that says if you have a splice, then the immediately next bracket is always allowed.

**Comment by ndmitchell** [comment]
Thanks for the report, and thanks @RyanGIScott for the explanation - agreed we should remove this once GHC 9.6 is out.
