### ISSUE TITLE
Unsound hint with respect to subtraction

### ISSUE THREAD

**Issue by NorfairKing** [ndmitchell/hlint#1242]
I got this hint: 
```
1 hint
smos-calendar-import/src/Smos/Calendar/Import/WeekDate.hs:68:37-42: Suggestion: Redundant bracket
Found:
  7 * (w -1)
Perhaps:
  7 * w -1
```
This is very dangerous!

**Comment by ndmitchell** [comment]
Which version of HLint? I suspect the `-1` has been lexed as a number, not as a subtraction, which is why the issue comes up. We turned off LexicalNegation in the last release, so I'm hoping that fixed it.

**Comment by NorfairKing** [comment]
```
[nix-shell:~/src/smos]$ hlint --version
HLint v3.3, (C) Neil Mitchell 2006-2021
```
I just did a `niv upgrade` and got this version via https://github.com/cachix/pre-commit-hooks.nix

**Comment by ndmitchell** [comment]
I suspect this got fixed in v3.3.1 which was released last night.

**Comment by NorfairKing** [comment]
@ndmitchell Thanks!

**Comment by ndmitchell** [comment]
Until then, passing `-XNoLexicalNegation` will hopefully fix the error.

**Comment by NorfairKing** [comment]
> Until then, passing `-XNoLexicalNegation` will hopefully fix the error.

Putting a space between the `-` and the `1` also fixes this, so I suspect you're right :)
