### ISSUE TITLE
Implementing NO_COLOR

### ISSUE THREAD

**Issue by tchoutri** [ndmitchell/hlint#1243]
Hi @ndmitchell! I would like to know if you were open to a PR implementing https://no-color.org/  in HLint?

The behaviour is fairly simple and standardised:

> How should configuration files and command-line arguments be processed in the presence of $NO_COLOR?

> User-level configuration files and per-instance command-line arguments should override $NO_COLOR. A user should be able to export $NO_COLOR in their shell configuration file as a default, but configure a specific program in its configuration file to specifically enable color.

Cheers

**Comment by ndmitchell** [comment]
That sounds very reasonable - PR most welcome.

**Comment by zliu41** [comment]
Closed via #1517

**Comment by tchoutri** [comment]
thanks @elland
