### ISSUE TITLE
Configuration option for disabling {-# ANN #-}

### ISSUE THREAD

**Issue by rvl** [ndmitchell/hlint#1251]
Hello, is there a configuration option to switch off the ANN pragma method of directing HLint?

This would be useful for us, because we do not wish to accidentally increase compile times due to TemplateHaskell evaluation caused by `{-# ANN myFunction "HLint: ignore" #-}` and similar directives, when `{- HLINT ignore myFunction -}` works just as well.

**Comment by ndmitchell** [comment]
See #1148 which goes further than this - I think we should detect ANN pragmas for HLint with a lint and suggest the alternative.

**Comment by rvl** [comment]
Or that :smile:, but I thought it would be more work to add a new class of Hint.
Most of the time, developers won't add ANN pragmas which don't fix their HLint errors.
So even if there is a cabal build flag which disables `readPragma`, that would be good enough for me.

**Comment by ndmitchell** [comment]
I don't think adding a new class of Hint is any more work than the other things - there are already things that consult ANN pragmas, so it's pretty easy (pretty much the existing code that reads them). Whereas cabal build flags are an absolute nightmare to maintain, and then imply C-pre-processor, which gets even worse.
