### ISSUE TITLE
hlint is confused by OPTIONS_GHC

### ISSUE THREAD

**Issue by ikirill** [ndmitchell/hlint#126]
In the following file

    {-# OPTIONS_GHC -Wall
          -fwarn-type-defaults
          -fwarn-name-shadowing
          -fwarn-missing-signatures
          -fwarn-hi-shadowing
          -fwarn-orphans
          -fwarn-unused-do-bind
          -fno-warn-unused-imports #-}

    main :: IO ()
    main = do return ()

hlint suggests the following:

    src $ hlint test.hs
    test.hs:4:8: Error: Redundant do
    Found:
      do return ()
    Why not:
      return ()

But the line should be 11, not 4. It seems hlint somehow ignores the 7 extra lines inside the OPTIONS_GHC pragma.

This is with hlint 1.9.20, ghc 7.8.3 from Haskell Platform on OSX.

**Comment by ndmitchell** [comment]
Thanks for the report. It's a bug in the underlying haskell-src-exts library, I've reported it upstream: https://github.com/haskell-suite/haskell-src-exts/issues/218

**Comment by ndmitchell** [comment]
Should be fixed in the latest HSE/HLint combo, please reopen if not.
