### ISSUE TITLE
Should hlint ignore filenames starting with .?

### ISSUE THREAD

**Issue by bmjames** [ndmitchell/hlint#127]
When searching for files recursively, HLint ignores directories beginning with `.`, but finds temporary files created by my editor, which begin with `.`. This can result in spurious errors.

I can work around this by using a glob pattern in my shell, for example:

    $ hlint **/*.hs

When expanding the glob pattern, the shell finds all the real source files that HLint would by default, but ignores the temporary files.

However, sometimes one might want to invoke HLint without a shell that has the capability to expand a glob pattern.

Do you agree that HLint should ignore them by default?

**Comment by ndmitchell** [comment]
Agreed, sounds reasonable. Patch welcome :)

**Comment by ndmitchell** [comment]
Merged the patch, so now fixed.
