### ISSUE TITLE
use mconcat is wrong

### ISSUE THREAD

**Issue by locallycompact** [ndmitchell/hlint#1271]
Hlint hints that `foldr (<>) mempty` can be replaced with `mconcat`. This isn't true.

```
foldr (<>) mempty :: (Monoid a, Foldable f) => f a -> a
mconcat :: Monoid a => [a] -> a
```

**Comment by ndmitchell** [comment]
Thanks for spotting and reporting! Thanks to @zliu41 for fixing!
