### ISSUE TITLE
Proposing a few "more complex" rules

### ISSUE THREAD

**Issue by jvoigtlaender** [ndmitchell/hlint#1283]
There are a few patterns I saw in a student's code that I would suggest refactorings on. I'd be glad to make pull requests with corresponding hlint rules, but first wanted to check whether they are considered reasonable, because they might be seen as "too special".

Case 1:

The student wrote code like this:
```haskell
mapM (const ts) [1 .. n]
```
I'd replace this by:
```haskell
replicateM n ts
```
An hlint rule
```yaml
mapM (const x) l -> replicateM (length l) x
```
could serve that purpose, in particular if there were also a rule
```yaml
length [1..n] -> max 0 n
```
or so.

If the above is considered fair game, then also this analogous rule would make sense:
```yaml
map (const x) l -> replicate (length l) x
```

Case 2:

The student wrote code like this:
```haskell
filter (`notElem` list) otherList
```
I'd propose a rule:
```yaml
filter (`notElem` x) y -> y \\ x
```

Side issue:

I was surprised Hlint didn't "complain" about this elsewhere in the student's code: `(,t) x`. Can there be ordinary new rules
```yaml
(,b) a -> (a,b)
```
and
```yaml
(a,) b -> (a,b)
```
or are tuple sections treated in some special way during parsing so that these rules would not help?

**Comment by ndmitchell** [comment]
All the first rules make a lot of sense. The ones about tuple sections might not though - as there are legitimate cases where the code becomes worse:

```
(,short) $ a really long sub expression
(short,) $ a really long sub expression
```

If those tuple rules were restricted to `b` being atomic (doesn't require brackets) then they'll probably all good.

**Comment by jvoigtlaender** [comment]
I've made a pull request with these rules. Uncertain about two bits:
1. Is some kind of escaping (when writing the rule) necessary for `\\` meant as list subtraction? https://github.com/ndmitchell/hlint/blob/68a7850e4f619d27fffbb14da010e85a89351b0f/data/hlint.yaml#L212
2. Above, did you really mean that in both cases `b` should be atomic in the tuple rules? Or always the expression that is moved from outside the tuple section inside the tuple? https://github.com/ndmitchell/hlint/blob/68a7850e4f619d27fffbb14da010e85a89351b0f/data/hlint.yaml#L571-L572

**Comment by sjakobi** [comment]
> I'd propose a rule:
> 
> ```yaml
> filter (`notElem` x) y -> y \\ x
> ```

Note that the RHS can behave differently from the LHS:

```
ghci> x = [1]
ghci> y = [1,1]
ghci> filter (`notElem` x) y
[]
ghci> y \\ x
[1]
```

See [the haddocks for `(\\)`](https://hackage.haskell.org/package/base-4.15.0.0/docs/Data-List.html#v:-92--92-).

**Comment by jvoigtlaender** [comment]
Good catch, thank you!

I've removed that rule from the pull request https://github.com/ndmitchell/hlint/pull/1289.

**Comment by ndmitchell** [comment]
Anything else to do on this ticket or should it be shut?

**Comment by jvoigtlaender** [comment]
Closing it.
