### ISSUE TITLE
Consider moving filter rules

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/hlint#1285]
Following on from #1268 by @jvoigtlaender I wondered about rules that move `filter, e.g.:

```
filter f (nub x) ==> nub (filter f)
```

I think `sort`/`reverse` probably also benefit from the same treatment.

**Comment by jvoigtlaender** [comment]
I had considered these rules as well (with `filter` and also thinking about other similar functions), but saw problems *except* for `catMaybes`, `lefts`, `rights`. The problems have to do with `Eq` instances (and possibly `Ord` instances) for custom types.

Let's say we have:
```haskell
data D = A | B

instance Eq D where
  x == y = True

isA :: D -> Bool
isA A = True
isA _ = False
```

Then:
```shell
> length $ filter isA (nub [B,A])
0
> length $ nub (filter isA [B,A])
1
```

The reason something like this does not happen in https://github.com/ndmitchell/hlint/pull/1268 is that we know what the `Eq`/`Ord` instances for `Maybe` and `Either` are.

**Comment by jvoigtlaender** [comment]
I've made a pull request (https://github.com/ndmitchell/hlint/pull/1290) for the `filter`/`reverse` case.

The `filter`/`sort` case has potential pitfalls like discussed for the `filter`/`nub` case above.

**Comment by ndmitchell** [comment]
So we've probably done all we can do now. It's unfortunate these aren't safe, but better safe than wrong.
