### ISSUE TITLE
Regression: many hints no longer shown

### ISSUE THREAD

**Issue by Mikolaj** [ndmitchell/hlint#1298]
Since probably around 70 days ago hlint stopped showing some hints, e.g., the following are not shown with the current version, but are shown with hlint compiled with cabal index from 70 days ago (master branch of https://github.com/LambdaHack/LambdaHack, using `.hlint.yaml` from there):

```
./engine-src/Game/LambdaHack/Server/HandleRequestM.hs:1055:13: Warning: Redundant if
Found:
  if absentPermitted then True else k == kOld
Why not:
  absentPermitted Prelude.|| (k == kOld)

./engine-src/Game/LambdaHack/Server/ItemM.hs:224:62: Warning: Redundant do
Found:
  do when (IA.checkFlag Ability.Unique arItem) $
       modifyServer $
         \ ser -> ser{suniqueSet = ES.insert itemKindId (suniqueSet ser)}
Why not:
  when (IA.checkFlag Ability.Unique arItem) $
    modifyServer $
      \ ser -> ser{suniqueSet = ES.insert itemKindId (suniqueSet ser)}

./engine-src/Game/LambdaHack/Server/ItemRev.hs:192:28: Warning: Redundant do
Found:
  do if length flvs < 6 then
       do flavour <- oneOf flvs
          return (EM.insert key flavour assocs, availableMap)
       else
       do let available = availableMap EM.! IK.isymbol ik
              proper = ES.fromList flvs `ES.intersection` available
          assert
            (not (ES.null proper) `blame` "not enough flavours for items"
               `swith` (flvs, available, ik, availableMap))
            $
            do flavour <- oneOf $ ES.elems proper
               let availableReduced = ES.delete flavour available
               return
                 (EM.insert key flavour assocs,
                  EM.insert (IK.isymbol ik) availableReduced availableMap)
Why not:
  if length flvs < 6 then
    do flavour <- oneOf flvs
       return (EM.insert key flavour assocs, availableMap)
    else
    do let available = availableMap EM.! IK.isymbol ik
           proper = ES.fromList flvs `ES.intersection` available
       assert
         (not (ES.null proper) `blame` "not enough flavours for items"
            `swith` (flvs, available, ik, availableMap))
         $
         do flavour <- oneOf $ ES.elems proper
            let availableReduced = ES.delete flavour available
            return
              (EM.insert key flavour assocs,
               EM.insert (IK.isymbol ik) availableReduced availableMap)

./test/doctest-driver.hs:1:1: Warning: Use better pragmas
Found:
  {-# OPTIONS_GHC
    -F -pgmF doctest-driver-gen -optF --verbose -optF definition-src -optF engine-src -optF -XMonoLocalBinds -optF -XScopedTypeVariables -optF -XOverloadedStrings -optF -XBangPatterns -optF -XRecordWildCards -optF -XNamedFieldPuns -optF -XMultiWayIf -optF -XLambdaCase -optF -XDefaultSignatures -optF -XInstanceSigs -optF -XPatternSynonyms -optF -XStrictData -optF -XCPP -optF -XTypeApplications #-}
  
Why not:
  {-# LANGUAGE MonoLocalBinds, ScopedTypeVariables,
    OverloadedStrings, BangPatterns, RecordWildCards, NamedFieldPuns,
    MultiWayIf, LambdaCase, DefaultSignatures, InstanceSigs,
    PatternSynonyms, StrictData, CPP, TypeApplications #-}
  {-# OPTIONS_GHC
    -F -pgmF doctest-driver-gen -optF --verbose -optF definition-src -optF engine-src -optF -optF -optF -optF -optF -optF -optF -optF -optF -optF -optF -optF -optF -optF#-}
```

Edit: here is a CI run with no hints for the same codebase: https://github.com/LambdaHack/LambdaHack/runs/3644703790?check_suite_focus=true

**Comment by zliu41** [comment]
In the first example, the reason why the hint isn't shown is because of `import Prelude ()`. With that, HLint doesn't know that the `True` is from Prelude, so the rule is not matched. I thought this has always been the behavior; not sure why it behaved differently 70 days ago.

It seems that project has `import Prelude ()` in every module, so a workaround is to put `NoImplicitPrelude` in the cabal file, which would make HLint believe that Prelude is in scope.

**Comment by Mikolaj** [comment]
@zliu41: thank you very much. Indeed, adding `NoImplicitPrelude` to `default-extensions` and removing `import Prelude ()` from every module does the trick. However, won't hlint become smarter at some point and deduce that `NoImplicitPrelude` makes `True suspect? Could we add some hlint option that says "ignore that I have a non-standard prelude"? I understand that tracking down the definition of `True` and automatically proving that it's equal to `Bool` is not an option.

**Comment by zliu41** [comment]
Yeah it's more of a workaround than a proper solution. Scoping is one of the main outstanding problems and there are quite a few open issues with the `scope` label, e.g., #1001. A proper solution needs to be determined and implemented.

I don't think I agree with a "ignore that I have a non-standard prelude" option though, because the problem is not limited to Prelude. You can, for example, re-export `Data.Map.fromList` from another module, which would cause the rule `{lhs: "Data.Map.fromList []", rhs: Data.Map.empty}` to fail to be triggered.

**Comment by Mikolaj** [comment]
How about a more general option, like "assume all of base is unchanged and in scope, even if re-exported in various ways"? Then whenever something is, in fact, changed, the user can just manually disable a particular hint. Yes, hlint would potentially suggest invalid hints, but that's a poweruser option, so it's fine.

**Comment by zliu41** [comment]
I think it's reasonable to assume:
- if we are not sure which module an identifier is from, assume that it possibly comes from Prelude, even if Prelude is not imported.

Currently HLint treats `import Prelude ()` and `{-# LANGUAGE NoImplicitPrelude #-}` differently. At least it should be consistent, and the above is one way to make it consistent. Doesn't fix the `Data.Map.fromList []` case but doesn't make it worse either.

This does create a new problem e.g., if one imports `Data.Vector` without explicit or qualified import, and uses `forM` from it, HLint would assume that it is from Prelude. But of course one is not supposed to use bare import for `Data.Vector`.

@ndmitchell What do you think? Alternatively we can treat `{-# LANGUAGE NoImplicitPrelude #-}` the same as `import Prelude ()`, but it is not uncommon for a module to use a custom Prelude so this doesn't seem like a good option.

**Comment by Mikolaj** [comment]
ping? so what's your decision? I'd prefer not to have to redo workarounds, so I'd like to know what to prepare for :)

**Comment by ndmitchell** [comment]
I think the idea of saying Prelude is the default origin of everything makes a lot of sense, and might help with some of the scope issues. Thanks for that patch @zliu41 - do you think this ticket is now ready to close, or is it worth doing something further?

**Comment by zliu41** [comment]
@ndmitchell I think it can be closed. I don't have anything further to do in mind.
