### ISSUE TITLE
Some hints are incorrect for non-lifted types

### ISSUE THREAD

**Issue by konsumlamm** [ndmitchell/hlint#1306]
Some hints (like `Use const` or `Avoid lambda` suggesting to use `.`) don't work for non-lifted types, since `const`, `.`, etc. aren't levity/representation-polymorphic.
If my assumption that hlint doesn't have any type information is correct, this can't be fixed, but it should at least be added to the [bugs and limitations](https://github.com/ndmitchell/hlint#bugs-and-limitations) list.

**Comment by zliu41** [comment]
I agree. I think this justifies adding another type of [Note](https://github.com/ndmitchell/hlint/blob/master/src/Config/Type.hs#L59).

**Comment by ndmitchell** [comment]
Adding it to the bugs/limitations section seems fine as a bullet point in the readme. The problem with adding a note is I think it would occur in many many hints, and that makes it a lot less useful as a hint. Your assumption that HLint doesn't have any type information is correct.
