### ISSUE TITLE
generate-summary seems to cache old result

### ISSUE THREAD

**Issue by Anton-Latukha** [ndmitchell/hlint#1316]
During: #1315 I noticed that after first run:

`cabal v2-run hlint -- --generate-summary` stoped to represent `hlint.yml` changes into `hints.md`. It seems to use some old cache for generation of `hints.md`. (I note that in the [`fx` commit](https://github.com/ndmitchell/hlint/pull/1315/commits/f1fcedf6c833fb6d7dd490acc983d729e4e5f743)), it essentially broke on me - changes in `yaml` not appear in `hints.md` (I imagine) because of some caching somewhere, deleting `hints.md` does not help - generation still produces old variant with old wording & without rule updates etc.. .

---

<details><summary> tech details </summary>

</p>

```
* The Glorious Glasgow Haskell Compilation System, version 8.10.7

* cabal-install version 3.6.2.0

* compiled using version 3.6.2.0 of the Cabal library

* hackage.haskell.org,2021-11-11T03:14:22Z
```

Patch branch is based on 8e10b51, user first noted it in 441049c81e2d0ba1a10e1ec297ad77efd936784d during PR work.

</details>

**Comment by zliu41** [comment]
This seems like either a Cabal bug or a GHC bug. I opened a Cabal issue: https://github.com/haskell/cabal/issues/7862
A workaround is to `cabal clean` before generating the summary. Then you should get the up-to-date summary.

**Comment by Anton-Latukha** [comment]
Thank you. Would close after recheck & enough time for people who hit this to see the solution.

**Comment by zliu41** [comment]
I previously knew that `hlint.yaml` is loaded at compile time. So when I noticed that modifying `hlint.yaml` doesn't trigger Cabal to recompile anything, that points to a Cabal/GHC issue.

By the way, according to the comments in haskell/cabal#7862, another workaround is to stop using wildcards in `extra-source-files`, so I'll make that change which should prevent this problem from occurring in the future.
