### ISSUE TITLE
Consider backport support for extras >=1.7.10 and aeson >= 2.0 to hlint-3.2

### ISSUE THREAD

**Issue by jneira** [ndmitchell/hlint#1328]
* In hls we have to use hlint-3.2 cause 3.3 uses ghc-lib >= 9.0.1 which does not support ghc-8.6.5, ghc version we are gonna support for long time yet
* hlint-3.2 does not support extras-1.7.10 nor aeson-2.0.1 so it block hls from upgrade other deps needed them (like brittany)
* So i would like to ask maintainers if it would be possible to backport support for those libs versions and make a hlint-3.2.8 release including it
Thanks in advance!

**Comment by ndmitchell** [comment]
No objection to producing a 3.2.8, I guess forked from 3.2.7. I suspect supporting extra-1.7.10 is no big deal, and aeson-2.0.1 would be annoying but not fatal.

However, is there really a requirement to run the very latest HLS against ancient compilers? Would those developers be better off getting an HLS as of today, and just not upgrading it (like they've managed to not upgrade GHC for a very long period of time). By sticking to HLint 3.2 there are a bunch of bugs that won't be fixed, so all HLS users will have a worse HLint experience as a result, which is a bit sad.

**Comment by jneira** [comment]
> No objection to producing a 3.2.8, I guess forked from 3.2.7. I suspect supporting extra-1.7.10 is no big deal, and aeson-2.0.1 would be annoying but not fatal.

Many thanks that will be very helpful.

> However, is there really a requirement to run the very latest HLS against ancient compilers?

The motivation is support users who are still using ghc-8.6.5. I guess mainly hard to upgrade private code bases, people using ghcjs (it officially only supports 8.6.5), etc.
Our [deprecation policy](https://haskell-language-server.readthedocs.io/en/latest/supported-versions.html) says ghc-8.6.5 `will be deprecated after LTS and HLS full suppot for ghc-9.2`.

We dont have full support for ghc-9.0.1 yeat and stack lts in on ghc-8.10.7 so 🤷 

>

**Comment by ndmitchell** [comment]
Done. Can you confirm it matches your needs? None of my CI works with it, so I'm mostly just hoping...

**Comment by jneira** [comment]
@ndmitchell many thanks, i am trying hlint-3.2.8 in this branch: https://github.com/jneira/haskell-language-server/tree/brittany-9.0.1
I was able to upgrade extra to 1.7.10, but no luck with aeson-2.0, my main goal 😢 
Brittany-0.14.0.0 only support `aeson >= 2.0` *and* `base >=4.15.0 && <4.16` so it doesnt allow to use `aeson-2.0` for `ghc < 9.0.1`. So i would need ask brittany maintainers to add aeson.2.0 for older versions of base. 🤦

**Comment by ndmitchell** [comment]
Closing this as it seems the HLint piece is done, even if that wasn't as helpful as hoped

**Comment by jneira** [comment]
yeah, I hope I still could be useful to remove compat with aeson < 2 if Brittany maintainers release a version with support for both aeson -2 and GHC < 9
