### ISSUE TITLE
Enforce qualified import?

### ISSUE THREAD

**Issue by lierdakil** [ndmitchell/hlint#1346]
Hi. I'd like to make a hint to enforce certain imports to be qualified, e.g something to the tune of 

```yaml
- modules:
  - {name: [Unsafe], qualified: 'always'}
```

Is that possible now? If not, would you like a PR?

**Comment by ndmitchell** [comment]
https://github.com/ndmitchell/hlint#restricting-items says that

```
  - {name: [Data.Set, Data.HashSet], as: Set}
```

> Requires that all imports of Set must be qualified Data.Set as Set, enforcing consistency

Not sure you can just demand qualified without the `as` though - but that seems a very sensible addition. PR most welcome.

**Comment by lierdakil** [comment]
See https://github.com/ndmitchell/hlint/pull/1348 for the explanation of why `'always'`. TL;DR I did have a misconception about how wildcards work, but I've made that misconception a reality in the PR anyway because I find it more convenient.
