### ISSUE TITLE
Support for ghc-9.2.1?

### ISSUE THREAD

**Issue by peti** [ndmitchell/hlint#1347]
I tried to generate a CI build for my Haskell project with the fine `haskell-ci` utility, but alas the generated build fails because it can't create a build plan for `hlint` while building with `ghc-9.2.1`. The culprit seems to be the constraint `ghc-lib-parser ==9.0.*`. Is there any way to build hlint with the most recent version of `ghc`?

**Comment by LeventErkok** [comment]
Duplicate of #1314
