### ISSUE TITLE
Suggest `id` for identity functions

### ISSUE THREAD

**Issue by ChefYeum** [ndmitchell/hlint#1369]
For functions equivalent to `id`, for instance:
```hs
f x = x
```

Suggest the following:
```hs
f = id
```

Also happy birthday to Haskell.

**Comment by ndmitchell** [comment]
HLint actually used to do that, as part of its eta reduction hints, but generally people found these a lot less clear so they were often disabled. As a result, HLint doesn't suggest it anymore.

**Comment by parsonsmatt** [comment]
Furthermore, we can't know syntactically if this sort of eta reduction is possible. Simplified Subsumption in GHC 9.0 and above mean that `f x = x` and `f = id` are only equivalent if `x` does not have any `forall`s.
