### ISSUE TITLE
Mirror `return` rules to also fire on `pure`

### ISSUE THREAD

**Issue by tysonzero** [ndmitchell/hlint#1377]
They seem to all apply equally well on `pure`.

The first one I noticed in practice that didn't fire was `if x then y else pure ()`.

**Comment by ndmitchell** [comment]
Within the Haskell hints themselves, we have `isReturn` which is true for either `return` or `pure`. For the hints, unfortunately we have to duplicate them. We had duplicated a bunch of them, but now I've gone through and made sure we duplicated all of them.
