### ISSUE TITLE
Support for `<$>` and `<&>` operators (equivalent to (f)map)

### ISSUE THREAD

**Issue by akazukin5151** [ndmitchell/hlint#1390]
`concat $ fmap f x` triggers the `concatMap` lint, but `concat $ f <$> x` does not, even though it is equivalent.

The same goes for the `&` versions: whilst issue #1201 and PR #1204 supported the `&` operator so that `fmap f x & concat` triggers the lint, `x <&> f & concat` does not.

**Comment by ndmitchell** [comment]
Very true - happy to take a patch adding those hints. Note that you would add it for `concat (f <$> x)` as HLint sees through `$` vs bracket automatically.

**Comment by jvoigtlaender** [comment]
Concerning `<$>`, this seems to be largely done by https://github.com/ndmitchell/hlint/commit/f6fadf4892039fc5214d3b4c17d8f70b1bf25fa0 already. In fact, the original assertion above that `concat $ f <$> x` did not trigger `concatMap` last June is a bit odd, given that the March commit (released with v3.4 in April) already added this hint: https://github.com/ndmitchell/hlint/blob/f6fadf4892039fc5214d3b4c17d8f70b1bf25fa0/data/hlint.yaml#L134

Anyway, https://github.com/ndmitchell/hlint/pull/1447 now also adds the `<&>` versions.

**Comment by akazukin5151** [comment]
Sorry, apparently I was using version 3.2.7 last June, which did not have the lints for `<$>` in v3.4. They work correctly in v3.4. I tested #1447, and it correctly works for the `<&>` versions. Hope it gets merged soon!

**Comment by ndmitchell** [comment]
Merged #1447, so closing this. Thanks for spotting and fixing!
