### ISSUE TITLE
Rule for Maybe Monad rhs not working

### ISSUE THREAD

**Issue by chenvictor** [ndmitchell/hlint#1425]
I am trying to capture the pattern shown here: https://wiki.haskell.org/Maybe#Maybe_as_a_Monad

```
# before
 h x = case f x of
         Just n -> g n
         Nothing -> Nothing
 
 # after
 h' x = do n <- f x
           g n
```

I also want to be able to capture things like
```
f x = case x of
    Nothing -> Nothing
    Just v -> if v == 5 then
        ... else ...
```

Currently I'm attempting
```
- hint: {
    lhs: "case m of Nothing -> Nothing; Just x -> y",
    rhs: "do x <- m; y"
}
```
which doesn't seem to work (I get no lints found). However, if I replace use `rhs: Nothing` instead, the suggestion appears. So it seems like something is up with my `rhs`?

**Comment by zliu41** [comment]
Thanks for reporting this. Looks like a bug.

By the way, `case m of Nothing -> Nothing; Just x -> y` won't match `case f x of Just n -> g n; Nothing -> Nothing` because of the order of the `Just` case and the `Nothing` case. But by reversing the two cases I was able to reproduce it.
