### ISSUE TITLE
Hints with the same name

### ISSUE THREAD

**Issue by 9999years** [ndmitchell/hlint#1427]
The only way to ignore hints is by their name, but names are not unique; for example, according to `hints.md`, there are 8 different hints named "Use map":

```ShellSession
$ rg '<td>Use map</td>' hints.md
755:<td>Use map</td>
2843:<td>Use map</td>
4187:<td>Use map</td>
4203:<td>Use map</td>
4219:<td>Use map</td>
4235:<td>Use map</td>
9151:<td>Use map</td>
9167:<td>Use map</td>
```

Two of these hints introduce tuple sections, which I would like to hide, but I have no way to select them.

Maybe we could work on getting each hint a unique numeric identifier?

**Comment by ndmitchell** [comment]
A unique numeric identifier is a lot of work, and easy to go stale, so I've always avoided that. Giving the tuple hints different names makes a lot of sense though!
