### ISSUE TITLE
Support hiding warning levels on command line

### ISSUE THREAD

**Issue by brandonchinn178** [ndmitchell/hlint#1430]
Can't find an existing issue for this (or existing functionality); feel free to point to existing issues.

It would be great to be able to hide all suggestions when running hlint in a precommit hook (i.e. warnings are displayed + return nonzero exit code, suggestions not displayed and dont change exit code). hlint.yaml should not change so that IDE plugins could still show suggestions.

We don't want suggestions displayed at all in the pre-commit hook (not just not failing the hook) so that warnings dont get hidden underneath all the non-failing suggestions

**Comment by ndmitchell** [comment]
That doesn't exist at the moment. There is the show flag which enables ignored hints, so I imagine an `--ignore-suggestions` flag would be reasonable to add to. PR welcome.

**Comment by batkot** [comment]
If that's okay, I'll take a look at it today.

**Comment by zliu41** [comment]
@batkot Sounds good!
