### ISSUE TITLE
HLint built with GHC 9.2 trips over `MIN_VERSION_ghc` CPP

### ISSUE THREAD

**Issue by tchoutri** [ndmitchell/hlint#1442]
```haskell
binaryInterfaceVersion :: Word16
#if MIN_VERSION_ghc(9,4,0) && !MIN_VERSION_ghc(9,5,0)
binaryInterfaceVersion = 41

binaryInterfaceVersionCompatibility :: [Word16]
binaryInterfaceVersionCompatibility = [binaryInterfaceVersion]
#else
#error Unsupported GHC version
#endif
```

I don't pretend to understand how HLint exposes the MIN_VERSION_ghc CPP var when evaluating the [InterfaceFile](https://github.com/haskell/haddock/blob/main/haddock-api/src/Haddock/InterfaceFile.hs#L125-L133) file but it exposes the version of GHC with which it has been built, not the one that is specified in the cabal.project file.

Not sure how to remedy to this unless we can get HLint to build with GHC 9.4

**Comment by tchoutri** [comment]
@shayne-fletcher okay that's an interesting workaround, thanks a bunch! Any idea if that could be defined in the .hlint.yaml?

**Comment by shayne-fletcher** [comment]
sorry, that i don't know.

**Comment by tchoutri** [comment]
Works for me! :) 

Thanks for the useful answer anyway. :heart:

**Comment by philderbeast** [comment]
@tchoutri an alternative that lets this module get a pass from HLint.

```diff
  binaryInterfaceVersion :: Word16
  #if MIN_VERSION_ghc(9,4,0) && !MIN_VERSION_ghc(9,5,0)
  binaryInterfaceVersion = 41

  binaryInterfaceVersionCompatibility :: [Word16]
  binaryInterfaceVersionCompatibility = [binaryInterfaceVersion]
  #else
+ #ifndef __HLINT__
  #error Unsupported GHC version
+ #endif
  #endif
```
