### ISSUE TITLE
QuasiQuote parse error on input

### ISSUE THREAD

**Issue by BiscuitCookies** [ndmitchell/hlint#1444]
Using GHC 8.10.7
QuasiQuotes is in the extensions for the .cabal file.
https://github.com/BiscuitCookies/pdxparse/blob/master/src/QQ.hs using this quasi quoter
`[pdx| opinion_modifiers = @mods |]`
it shows the error
`Hlint Error: Parse error: on input '='`

this code
`[pdx| %_ = @scr |]`
shows this error
`Hlint Error: Parse error: on input '%'`

Code works and builds fine.

~~The issue #1068 might be related but Was moved to haskell IDE and was not addressed before archival~~

**Comment by shayne-fletcher** [comment]
hlint seems to be working as expected. 

![Screenshot 2023-01-19 at 5 29 27 PM](https://user-images.githubusercontent.com/1500167/213576623-8beb88ca-20c8-46e2-a219-43708902c87b.png)

**Comment by BiscuitCookies** [comment]
Alright so that isn't why the parse error shows up.
Any clue as to what causes it read as a parse error?

**Comment by shayne-fletcher** [comment]
hlint by default chooses a  set of enabled extensions that aims to parse as broad a number of haskell files as possible.

`QuasiQuotes` though "breaks whitespace free list comprehensions `[x|...]` so is considered "bad" and not by default in that set.
 
passing hlint `-XQuasiQuotes` enables it.

passing `-XGHC2021 -XQuasiQuotes` has the effect of enabling exactly the [extensions implied by `GHC2021`](https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/control.html#extension-GHC2021) and `QuasiQuotes`.

**Comment by shayne-fletcher** [comment]
this is of course consistent with the behavior of ghc itself

<img width="796" alt="Screenshot 2023-01-19 at 6 23 51 PM" src="https://user-images.githubusercontent.com/1500167/213584377-58b7b977-7db4-4a52-9d3f-527b15f36a69.png">

**Comment by BiscuitCookies** [comment]
Thanks, that explains it.
