### ISSUE TITLE
Usage of `~` shouldn't flag `TypeOperators` as unused

### ISSUE THREAD

**Issue by ocharles** [ndmitchell/hlint#1445]
In GHC 9.4 [`~` is now a type operator](https://gitlab.haskell.org/ghc/ghc/-/wikis/migration/9.4#-is-now-a-type-operator), meaning we need to enable `-XTypeOperators`. However, HLint seems to be reporting this pragma as unnecessary

**Comment by zliu41** [comment]
Do you have an example? HLint doesn't seem to report unused TypeOperator when `~` is used.

**Comment by ocharles** [comment]
Ah, my bad! I think I did a find and replace to add `TypeOperator`s to all modules in one of our libraries, and forgot that I needed to go back and clean it up! I think these warnings are correct
