### ISSUE TITLE
Invalid hint when using NamedFieldPun field updates

### ISSUE THREAD

**Issue by yairchu** [ndmitchell/hlint#1453]
When trying out modernizing Haskell I've changed [some code](https://github.com/Peaker/git-mediate/blob/a991d32a5922cc7ac1821db84e69a642115f022e/src/Conflict.hs#L36) to:

```Haskell
-- traversal
bodies :: Applicative f => (Sides [String] -> f (Sides [String])) -> Conflict -> f Conflict
bodies f c = (\cBodies -> c{cBodies}) <$> f c.cBodies
```

To which hlint gives a wrong hint:

```Haskell
Use const
Found:
  \ cBodies -> c {cBodies}
Why not:
  const c {cBodies}
```

Note that `\cBodies -> c {cBodies}` with `NamedFieldPun` is equivalent to `\cBodies -> c {cBodies=cBodies}` so it does use the lambda parameter (not a const).

**Comment by batkot** [comment]
Looking into it
