### ISSUE TITLE
Can't install hlint using Cabal commands

### ISSUE THREAD

**Issue by GasparB123** [ndmitchell/hlint#1461]
It builds and installs all packages until it reaches yaml. It throws 

cabal: Failed to build yaml-0.11.10.0 (which is required by exe:hlint from hlint-3.5).

[yaml-0.11.10.0-7d59f7f03fe8860bf4be7c1ac491e49f6393805181c3d97e5492597cefab6391.log](https://github.com/ndmitchell/hlint/files/10819164/yaml-0.11.10.0-7d59f7f03fe8860bf4be7c1ac491e49f6393805181c3d97e5492597cefab6391.log)

here is the log file in which it says apparently it has a conflict with Aeson

If anyone can help it would be great.

**Comment by shayne-fletcher** [comment]
aeson 2.1.2.0 released yesterday and broke yaml 0.11.10.0 which uses unqualified imports. it was only that way for a few hours before yaml 0.11.11.0 was released which fixed it.
