### ISSUE TITLE
Suggest explicit brackets to mitigate counter-intuitive prefix negation precedence

### ISSUE THREAD

**Issue by kostmo** [ndmitchell/hlint#1484]
# Motivation
The operator precedence of "prefix minus" can be surprising to unsuspecting Haskell programmers.

For example, in the REPL:
```
ghci> -1 ^ 2
-1
```
and
```
ghci> -5 + 3
-2
ghci> plus = (+)
ghci> -5 `plus` 3
-8
```
The case that prompted the filing of this issue was:
```
ghci> -5 `mod` 3
-2
```
which led to inferring incorrect semantics of Haskell's `mod` function, illustrated in [this thread](https://github.com/swarm-game/swarm/pull/1181#discussion_r1151156655).  As it happens, unlike some other languages, `mod a b` in Haskell is  non-negative for all positive `b`.

There is an enlightening [thread on the Haskell mailing list](https://mail.haskell.org/pipermail/haskell-prime/2010-July/003229.html) from July 2010 that discusses fixity of the prefix minus and references (defunct?) proposals to make it bind more tightly.  This corroborates the notion that the current precedence of prefix negation can be counter-intuitive.

# Proposal

In contrast with existing `hlint` rules that suggest to remove redundant brackets, I propose that `hlint` suggest to *add* redundant brackets to disambiguate (for human readers) negation precedence.

Such a rule could catch bugs; when an author writes:
```
 -5 `mod` 3
```
`hlint` would suggest instead to write:
```
 -(5 `mod` 3)
```
which would cause the author to realize that their expression is being parsed differently than intended and update their code to:
```
(-5) `mod` 3
```

# Implementation
The rule should fire whenever the operand of "unary minus" is an **infix operation** of **higher precedence**.

For reference, unary negation is fixity 6, the same as binary subtraction.  Multiplication, division, and modulus have fixity 7, and exponentiation has fixity 8.

**Comment by ndmitchell** [comment]
Sounds like a good idea, given this is quite a foot gun. Patch welcome!

**Comment by kostmo** [comment]
I just came across [this reddit post](https://www.reddit.com/r/haskell/comments/187gw5z/comment/kbg29dt/?context=3) as more empirical evidence that the negation precedence can be "baffling" and a good demonstration of the value that this lint rule will provide.

**Comment by 9999years** [comment]
This lint seems to fire even with `NegativeLiterals`/`LexicalNegation` enabled, which mitigates the issue being linted for. It'd be nice to add a special case here.
