### ISSUE TITLE
traverse/mapM for sequence and `<$>` 

### ISSUE THREAD

**Issue by Lev135** [ndmitchell/hlint#1508]
Hlint suggests to replace `sequence . fmap f`  and `sequence (fmap f a)` with `mapM`, but it doesn't for `sequence (f <$> a)`. Is there any reason not to do so or this case is just accidently missed?

**Comment by batkot** [comment]
Hi @Lev135 

I tried to recreate it, but it seems to work fine with `hlint 3.5` :thinking: 

Sample file:
```haskell
module MapM (foo, foo2, foo3) where

foo f x = sequence (fmap f x)

foo2 f = sequence . fmap f

foo3 f x = sequence (f <$> x)
```

```bash
$ stack exec -- hlint MapM.hs

MapM.hs:3:11-29: Warning: Use mapM
Found:
  sequence (fmap f x)
Perhaps:
  mapM f x

MapM.hs:5:10-26: Warning: Use mapM
Found:
  sequence . fmap f
Perhaps:
  mapM f

MapM.hs:7:12-29: Warning: Use mapM
Found:
  sequence (f <$> x)
Perhaps:
  mapM f x

3 hints
```

**Comment by zliu41** [comment]
HLint 3.4.1 indeed suggests `mapM` for `sequence (f <$> a)`. Closing the issue.

**Comment by Lev135** [comment]
Sorry for disturbing you. I really have an old version.
