### ISSUE TITLE
`apply-refact` removes parens in the whole module 

### ISSUE THREAD

**Issue by MangoIV** [ndmitchell/hlint#1513]
In definitions like the following: 
```haskell
data instance (f * g) a where
``` 
, when applying *any* hint, it just removes the parens around `f * g` which makes `apply-refact` unusable for modules that have such a definition.

**Comment by ndmitchell** [comment]
CC @zliu41

**Comment by zliu41** [comment]
This must be an apply-refact bug since it occurs on any hint. Moving to https://github.com/mpickering/apply-refact/issues/146.
