### ISSUE TITLE
Binaries not provided with 3.6 release

### ISSUE THREAD

**Issue by koterpillar** [ndmitchell/hlint#1526]
Previous releases used to provide binaries as assets on GitHub releases, but 3.6 does not, perhaps because of [this action failure](https://github.com/ndmitchell/hlint/actions/runs/5378287094/jobs/9757883616#step:4:10).

I realize [Installing and running HLint](https://github.com/ndmitchell/hlint#installing-and-running-hlint) recommends `cabal` but standalone binaries are a very convenient way that works independently of any individual projects, so would be nice to have them back.

**Comment by ndmitchell** [comment]
Yep, working on bringing them back. Various changes in the setup between now and then meant they broke, and unfortunately, it's the kind of thing I only get to see at release time.

**Comment by ndmitchell** [comment]
They are available with the 3.6.1 release.

**Comment by phadej** [comment]
https://github.com/ndmitchell/hlint/issues/1532
