### ISSUE TITLE
Add aeson < 2.2 upper bound to Hackage

### ISSUE THREAD

**Issue by brandonchinn178** [ndmitchell/hlint#1527]
`aeson-2.2.0.0` was released yesterday, and it removed `Data.Aeson.Internal`, which breaks hlint when doing a plain `cabal install hlint-3.5`. Can you make a Hackage revision to hlint 3.5 + 3.6 that bounds `aeson < 2.2`? Thanks!

**Comment by ndmitchell** [comment]
I don't think hlint itself uses Data.Aeson.Internal, but presumably one of its dependencies. When I just tried to cabal install it, Cabal picked aeson 2.1, so I guess whatever dependency HLint relied upon added some version bounds?

**Comment by brandonchinn178** [comment]
Yes, you're right. Apologies
