### ISSUE TITLE
Empty 'where' clause in case alternative causes parse error

### ISSUE THREAD

**Issue by Peaker** [ndmitchell/hlint#169]
GHC parses it fine, but hlint gets a parse error.

Haven't tested with other empty 'where' clauses.

It's probably worth its own hlint warning.

**Comment by mpickering** [comment]
Can you please post the exact code which was failing? I think I know which bug you are talking about in HSE but can't be sure until then. The next version of HLint will probably warn about empty where clauses as the blocking issue in HSE has been fixed.

**Comment by Peaker** [comment]
Here is where it failed: https://github.com/Peaker/lamdu/blob/c136e998753ffca2b1dd4ddeb610dbb94637af2d/Lamdu/Sugar/RedundantTypes.hs#L41

**Comment by mpickering** [comment]
I'm fairly sure this it https://github.com/haskell-suite/haskell-src-exts/issues/228 

Should be fixed in the next version I think.

**Comment by Peaker** [comment]
Great, thanks!

On Wed, Aug 19, 2015 at 5:52 PM, Matthew Pickering <notifications@github.com
> wrote:

> I'm fairly sure this it haskell-suite/haskell-src-exts#228
> <https://github.com/haskell-suite/haskell-src-exts/issues/228>
>
> Should be fixed in the next version I think.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ndmitchell/hlint/issues/169#issuecomment-132626222>.
>



-- 
Eyal

**Comment by ndmitchell** [comment]
Seems reasonable to add as a hint, as soon as I can parse/test it - thanks for the idea.

**Comment by ndmitchell** [comment]
Seems HSE now chokes on this file, so I've raised https://github.com/haskell-suite/haskell-src-exts/issues/282. As it happens, if you massage the file to not get the parse errors, HLint does spot both redundant cases - so just an HSE issue now.

**Comment by ndmitchell** [comment]
Confirmed works with HEAD that doesn't use HSE for parsing, so fixed in the next release.
