### ISSUE TITLE
Use string literal suggestion is wrong when using OverloadedStrings

### ISSUE THREAD

**Issue by niteria** [ndmitchell/hlint#174]
```
Warning: Use string literal
Found:
  ['.', '_', '-']
Why not:
  "._-"
```

If you use `OverloadedStrings` and `default (Text)` then `"._-" :: Text` and `['.', '_', '-'] :: String`.

**Comment by simonmar** [comment]
What's more, if you have `c `elem` "abc"` and `OverloadedStrings`, you get an ambiguity error now that `elem` is overloaded on `Foldable`. (defaulting doesn't apply in this case)

**Comment by ndmitchell** [comment]
Following 5 years using a language which doesn't even have character literals I now see a list of characters and a string as two entirely independent things. With overloaded strings, and overloaded Prelude, these kind of changes are a lot less simple, so I've disabled these hints.
