### ISSUE TITLE
ANN pragma and OverloadedStrings

### ISSUE THREAD

**Issue by ivan-m** [ndmitchell/hlint#180]
I'm not sure if this is really HLints problem or not, but if I try to add an `ANN` pragma such as
```haskell
{-# ANN module "HLint: ignore Use camelCase" #-}
```
to a module where `OverloadedStrings` is enabled, then GHC complains with:
```
No instance for (Data.Data.Data a0) arising from an annotation
The type variable ‘a0’ is ambiguous
...

No instance for (IsString a0)
arising from the literal ‘"HLint: ignore Use camelCase"’
The type variable ‘a0’ is ambiguous
```

**Comment by ndmitchell** [comment]
If you add :: String to the string in the ignore does it still ignore properly? If not, that is an hlint bug. If yes, you have a solution.

**Comment by ivan-m** [comment]
Using this seems to work:
```haskell
{-# ANN module ("HLint: ignore Use camelCase" :: String) #-}
```
It's a bit clunky but will suffice, ta :)
