### ISSUE TITLE
Allow "test_" prefix in function names

### ISSUE THREAD

**Issue by expipiplus1** [ndmitchell/hlint#183]
`test_` is the prefix used by tasty-th for test groups.

https://hackage.haskell.org/package/tasty-th-0.1.3/docs/Test-Tasty-TH.html

I imagine that this will have more change of false-negatives on real code compared to `case_` or `prop_`; whether this is a significant amount I do not know.

**Comment by ndmitchell** [comment]
I'm not too worried about false-negatives - far more worried about false positives. I've put `test_` on the safe list.

**Comment by expipiplus1** [comment]
Cool stuff! Thanks!
