### ISSUE TITLE
Redundant parentheses on record patterns

### ISSUE THREAD

**Issue by asr** [ndmitchell/hlint#188]
Running hlint on

```haskell
data A = A Int Int Int

foo :: A -> Bool
foo (A{}) = True
```

there are not suggestions, but I would expect something like

```bash
Warning: Redundant bracket
Found:
  (A{})
Why not:
  A{}
```

**Comment by ndmitchell** [comment]
Thanks for the suggestion. https://github.com/ndmitchell/hlint/issues/113 captures some of this, but I think it's clear that brackets round an atomic pattern seems both simpler and valuable in its own right, so I may try that first.

**Comment by ndmitchell** [comment]
I've handled the case of brackets around something atomic specially, so this is now done.

**Comment by asr** [comment]
Thanks!
