### ISSUE TITLE
Building with stack is broken since the haskell-src-exts update

### ISSUE THREAD

**Issue by expipiplus1** [ndmitchell/hlint#190]
`lts-3.9` doesn't issue `haskell-src-exts-1.17.0` and the in repository version is out of date.

**Comment by expipiplus1** [comment]
Whoops! None of this is in the hlint repo, I was mistakenly on my own branch!

**Comment by ndmitchell** [comment]
Yes, it's a bit unfortunate that the current hlint can't build with stack - hopefully the haskell-src-exts Stack nightly will be out soon.
