### ISSUE TITLE
Explain how to use apply-refact

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/hlint#191]
Link to http://mpickering.github.io/posts/2015-11-22-hlint-refactor.html in the manual, or perhaps integrate some of the content into the hlint manual. Any thoughts from @mpickering most welcome.

**Comment by mpickering** [comment]
I added a little section to the README already which explains the basics. Maybe just adding the link would be sufficient?

**Comment by ndmitchell** [comment]
Yep. Although I'd be happier linking to the content of it was a we page for refact, rather than a blog post which I wouldn't expect to be updated with future info.

**Comment by ndmitchell** [comment]
Covered by #504

**Comment by ndmitchell** [comment]
There is a bit more content there now.
