### ISSUE TITLE
"openFile: resource busy (file is locked)" when refactoring in place

### ISSUE THREAD

**Issue by sinelaw** [ndmitchell/hlint#207]
I'm running:

    hlint --refactor --refactor-options="-i"  bla.hs

and I'm consistently getting:

    refactor: bla.hs: openFile: resource busy (file is locked)

Does hlint close the file before handing it over to refactor?

**Comment by ndmitchell** [comment]
I can't reproduce this, but I was indeed not closing the file properly, so sometimes it could have leaked (would have depended on when GC ran most likely). Can you try again with the git version?

**Comment by sinelaw** [comment]
Just tried latest master, still happens...

**Comment by ndmitchell** [comment]
Hmm. What OS/GHC version? Does it happen for all files? What about a simple file `foo = concat . map succ`?

**Comment by sinelaw** [comment]
GHC 7.10.3 installed using stack setup
Linux Mint / Ubuntu 14.04

Will do more tests later...

**Comment by ndmitchell** [comment]
Can you try running just refactor, without involving hlint, by calling refactor with the hlint output separately. I have a suspicion this might be a refactor only bug, cc @mpickering.

**Comment by sinelaw** [comment]
I tried doing that but couldn't figure out the right way. Do you run:

    hlint file.hs | refactor

...or what?

**Comment by ndmitchell** [comment]
hlint Sample.hs --serialise | refactor Sample.hs -i

(I had to look that up from the source code)

**Comment by sinelaw** [comment]
Yeah, looks like refactor fails even then. Still getting: `openFile: resource busy (file is locked)`

Opened issue https://github.com/mpickering/apply-refact/issues/21
