### ISSUE TITLE
Properly integrate refact

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/hlint#211]
Things I can think of:
- Explain how to use it without the built-in refactor running support.
- Add tests for the refactorings, that they produce the right results, specifically the output on the console should be the same.
- Ideally change the API so the way I generate refact hints and my own pretty print is identical - that way the refact stuff is correct by construction.

At the moment refact support is clearly a second-class addon. To have a hope of making it not break it needs to be more tightly integrated (not necessarily linking wise, just design wise).

Cc @mpickering, although to have it keep working going forward, I expect to do most/all of the work.

**Comment by mpickering** [comment]
I agree that the support is an add-on but when adding the support it seemed clear to me there were two different priorities. I needed very exact positional information to make sure that the hints were getting applied to the right places whereas the normal suggestions focused a bit more on giving sensible context to display to the user. 

Happy to help with refactoring if you come up with a concrete design which satisifies both needs.

**Comment by ndmitchell** [comment]
Covered by #504

**Comment by ndmitchell** [comment]
It's well integrated and tested now.
