### ISSUE TITLE
Incorrect fold hints on tuple accumulators

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/hlint#220]
Move from https://github.com/ndmitchell/hlint/pull/219#issuecomment-189177150, since I want to have an open bug not a merged pull request to track this.

@Athas  - no, this seems entirely wrong - it should be checking if the final argument is a tuple, not the penultimate one. Specifically:

    warn "Using foldr on tuple"   = foldr   f (x,b) z ==> f b z

Should be:

    warn "Using foldr on tuple"   = foldr   f z (x,b) ==> f b z

And similarly for all other fold functions. @bartavelle, are you able to fix that up? If not I'll fix it tonight and make a release.

**Comment by bartavelle** [comment]
This is embarrassing!
