### ISSUE TITLE
different suggestion to preserve `select $ from $`

### ISSUE THREAD

**Issue by wolftune** [ndmitchell/hlint#224]
given the esqueleto common situation `select $ from $` (and a few variants of that), hlint is fine with this, *but* if the code is `(select $ from $ … )` then hlint says to change it to `select (from $ … )` when the correct fix is to remove the parentheses and leave both of the `$`

**Comment by wolftune** [comment]
actually, I found cases where removing the parens causing compile errors, so that's not a working solution necessarily

**Comment by ndmitchell** [comment]
Can you give a complete example? (ideally just the full source you started from) Are you saying that HLint's suggestion is correct but goes against the convention of the library? Or that HLint is giving an invalid suggestion?

**Comment by wolftune** [comment]
The Snowdrift code has several such cases, and I'm saying that HLint is going against the convention of the library, not that it gives invalid suggestion. Ideally we could set it to respect certain cases like `$ from $` as the thing to leave alone in this case.

Example: src/Model/User/Internal.hs in Snowdrift

**Comment by ndmitchell** [comment]
Yep, that seems entirely reasonable - just a case of adding a special case somewhere and testing it.

**Comment by ndmitchell** [comment]
Done, and tested on the example from Snowdrift. `select` on the left is now a special case.

**Comment by wolftune** [comment]
great!
