### ISSUE TITLE
Suggest lookupDefault

### ISSUE THREAD

**Issue by expipiplus1** [ndmitchell/hlint#233]
`warn "lookupDefault" = fromMaybe d lookup n m ==> lookupDefault d n m`

Where `lookup` and `lookupDefault` are from Data.Map

**Comment by ndmitchell** [comment]
My only concern is that several Map like packages have at various points made the second form strict in d, which breaks many instances of this replacement. As a result, it's not as advantageous as it otherwise would be.

**Comment by expipiplus1** [comment]
Ah, that's a pain. Which map packages do this, `Data.Map.Strict` is lazy in it's default argument.

**Comment by ndmitchell** [comment]
`unordered-containers` used to have that property, but it's since been fixed: https://github.com/tibbe/unordered-containers/issues/57 - maybe that means this is a reasonable hint once more.

**Comment by ndmitchell** [comment]
lookupDefault doesn't seem to exist on Data.Map, only the unordered-containers version.

**Comment by expipiplus1** [comment]
weird, perhaps it existed in 2016 or I was imagining things.
