### ISSUE TITLE
Warn about unnecessary usages of `void`

### ISSUE THREAD

**Issue by MHova** [ndmitchell/hlint#235]
If some function `foo` returns `m ()`, but it is invoked with `void foo` somewhere, warn the user that `void` is unnecessary.

**Comment by ndmitchell** [comment]
In general I don't know the type of arbitrary functions, so don't know if the void is required. For the common cases where I do know I already warn, see #229. Anything further you can think of?

**Comment by MHova** [comment]
Ah okay I see. Thanks for the quick response!
