### ISSUE TITLE
does not support CPP macros like MIN_VERSION_x ?

### ISSUE THREAD

**Issue by simonmichael** [ndmitchell/hlint#239]
In the hledger repo, I see:
```
$ hlint --no-exit-code --json /Users/simon/src/hledger/hledger-lib/Hledger/Read/CsvReader.hs
hlint: Cannot expand #if directive in file /Users/simon/src/hledger/hledger-lib/Hledger/Read/CsvReader.hs  at line 36 col 1:
    MIN_VERSION_time(a,b,c) is not a defined macro
```
Should this be working ?

**Comment by ndmitchell** [comment]
Which version of cpphs are you using? Which version of hlint? As far as I'm aware this got fixed with the cpphs upgrade as part of #53. I believe hlint 1.9.32 and cpphs 1.20.1 are required.

**Comment by simonmichael** [comment]
Oops, thank you! Time to upgrade my global stackage snapshot to lts-6.0.

**Comment by ndmitchell** [comment]
I added a test for this specific pattern so closing. Please reopen of it's still a problem.
