### ISSUE TITLE
Parse error on TypeApplications

### ISSUE THREAD

**Issue by acowley** [ndmitchell/hlint#250]
I erroneously [filed this with Intero](https://github.com/commercialhaskell/intero/issues/126), but it is an hlint issue.

**Comment by ndmitchell** [comment]
Raised upstream at https://github.com/haskell-suite/haskell-src-exts/issues/312.

**Comment by acowley** [comment]
Thanks, I should have originally raised this issue with emacs just to boost my wrong blame assignment stats.
