### ISSUE TITLE
Add hint for early monadic let

### ISSUE THREAD

**Issue by SeanRBurton** [ndmitchell/hlint#251]
It might be nice to suggest moving monadic let bindings closer to their first use; I can take a crack at this if you think it would be worthwhile.

**Comment by ndmitchell** [comment]
I'm not sure how useful this would be - often people care about the order of definitions a lot. I can think of many instances where the let binding is deliberately not near the use, and relatively few where it would be improved by being so but isn't already. Did you have a particular fragment of code that made you think this would help?

**Comment by SeanRBurton** [comment]
I don't have a particular code snippet, I was just thinking of instances where code develops over time and the structure becomes muddled. Maybe this is best handled manually.

**Comment by ndmitchell** [comment]
The general pattern is that given a set of statements you can sometimes reorder them or separate them to group related concepts. I certainly do that with code I refactor, but usually more on bigger scales - eg. moving whole functions nearer to each other, or to a separate module. I can imagine a tool that analysed use patterns and suggested tighter clusterings would be valuable - but I suspect it's too far away from what HLint does to make sense integrated into HLint.
