### ISSUE TITLE
Type operators in pattern synonym signature gives parse error

### ISSUE THREAD

**Issue by PkmX** [ndmitchell/hlint#259]
With the latest commits of `hlint` and `haskell-src-exts`, the following:

``` haskell
{-# LANGUAGE TypeOperators, PatternSynonyms, MultiParamTypeClasses #-}

class (>?) a b

pattern P :: a >? b => ()
pattern P <- ()
```

gives:

```
Error: Parse error: =>
Found:
    class (>?) a b

  > pattern P :: a >? b => ()
    pattern P <- ()


1 hint
```

**Comment by PkmX** [comment]
It appears that it is not caused by `TypeOperators`, but infix operators in general. The following also gives a parse error:

```haskell
{-# LANGUAGE PatternSynonyms, MultiParamTypeClasses #-}

class F a b

pattern P :: a `F` b => ()
pattern P <- ()
```

**Comment by ndmitchell** [comment]
Thanks for the report. This is an issue in the haskell-src-exts library, so I've raised it for them: https://github.com/haskell-suite/haskell-src-exts/issues/323

**Comment by ndmitchell** [comment]
Confirmed works with HEAD that doesn't use HSE for parsing, so fixed in the next release.
