### ISSUE TITLE
GADTs, record and constraints altogether gives `parse error`

### ISSUE THREAD

**Issue by y-usuzumi** [ndmitchell/hlint#261]
(hlint-1.9.35 and haskell-src-exts-1.17.1)

The following source:

``` haskell
{-# LANGUAGE GADTs #-}

data X where
  X :: Show a => { x :: a } -> X


main = putStrLn "Hello"
```

leads to the following error:

```
X.hs:4:18: Error: Parse error: {
Found:
    data X where
  >   X :: Show a => { x :: a } -> X


1 hint
```

Any idea?

**Comment by ndmitchell** [comment]
Thanks for the report. Raised upstream at https://github.com/haskell-suite/haskell-src-exts/issues/324.

**Comment by dmalikov** [comment]
Is there any way to ignore it with pragma?

**Comment by ndmitchell** [comment]
You can ignore all parse errors out of HLint `--ignore=Parse error`, I think. However, you won't get any hints in the rest of the file.

**Comment by ndmitchell** [comment]
Confirmed works with HEAD that doesn't use HSE for parsing, so fixed in the next release.
