### ISSUE TITLE
argsSettings doesn't honor user-supplied HLint.hs file

### ISSUE THREAD

**Issue by lierdakil** [ndmitchell/hlint#263]
As far as I can tell, `readSettingsFile` used in `argsSettings` (https://github.com/ndmitchell/hlint/blob/master/src/Language/Haskell/HLint3.hs#L78) always looks for `HLint.hs` in `datadir`, while when run from CLI, hlint check for `HLint.hs` in current directory. I believe this is not expected behavior.

Related issue:
https://github.com/DanielG/ghc-mod/issues/826

**Comment by ndmitchell** [comment]
Looks like a bug to me - thanks for the hint. Should be easy to fix (pull requests welcome, or I'll probably get to it in the next week).

**Comment by lierdakil** [comment]
ETIMEDOUT. Didn't use HLint3 interface for a while, so can't comment if it's fixed or not. A quick glance on the source code suggest that it is, so closing. Feel free to reopen if necessary.
