### ISSUE TITLE
Parse error with comma-separated GADT constructors

### ISSUE THREAD

**Issue by robrix** [ndmitchell/hlint#266]
Comma-separating GADT constructors is a convenient way to declare each of them with the same type signature:

``` haskell
{-# LANGUAGE GADTs #-}
module Example where

data Example where
  X, Y :: Example
```

But this makes hlint sad:

```
$ hlint ~/Desktop/Example.hs 
/Users/rob/Desktop/Example.hs:5:4: Error: Parse error: ,
Found:
    data Example where
  >   X, Y :: Example


1 hint
```

**Comment by ndmitchell** [comment]
Thanks for the report. This is an issue with the underlying haskell-src-exts library, which I've raised upstream as https://github.com/haskell-suite/haskell-src-exts/issues/330.

**Comment by robrix** [comment]
Thank you! :bow:

**Comment by ndmitchell** [comment]
Confirmed works with HEAD that doesn't use HSE for parsing, so fixed in the next release.
