### ISSUE TITLE
Failed to install hlint. Possible Error?

### ISSUE THREAD

**Issue by romanlarionov** [ndmitchell/hlint#268]
Just downloaded Haskell via:

```
brew cask install haskell-platform
```

Followed by:

```
cabal install happy
cabal install hlint
```

I get the following error:

> Resolving dependencies...
> Configuring hlint-1.9.37...
> Building hlint-1.9.37...
> Failed to install hlint-1.9.37
> Build log ( /Users/roman/.cabal/logs/hlint-1.9.37.log ):
> cabal: Entering directory '/var/folders/p8/41kg47m97xdcvft_zqxhfry00000gn/T/cabal-tmp-20731/hlint-1.9.37'
> Configuring hlint-1.9.37...
> Building hlint-1.9.37...
> Preprocessing library hlint-1.9.37...
> [ 1 of 46] Compiling Test.Util        ( src/Test/Util.hs, dist/build/Test/Util.o )
> [ 2 of 46] Compiling Test.InputOutput ( src/Test/InputOutput.hs, dist/build/Test/InputOutput.o )
> [ 3 of 46] Compiling HSE.Type         ( src/HSE/Type.hs, dist/build/HSE/Type.o )
> [ 4 of 46] Compiling HSE.FreeVars     ( src/HSE/FreeVars.hs, dist/build/HSE/FreeVars.o )
> [ 5 of 46] Compiling HSE.Util         ( src/HSE/Util.hs, dist/build/HSE/Util.o )
> [ 6 of 46] Compiling HSE.Match        ( src/HSE/Match.hs, dist/build/HSE/Match.o )
> [ 7 of 46] Compiling HSE.Scope        ( src/HSE/Scope.hs, dist/build/HSE/Scope.o )
> [ 8 of 46] Compiling HsColour         ( src/HsColour.hs, dist/build/HsColour.o )
> [ 9 of 46] Compiling Parallel         ( src/Parallel.hs, dist/build/Parallel.o )
> [10 of 46] Compiling Paths_hlint      ( dist/build/autogen/Paths_hlint.hs, dist/build/Paths_hlint.o )
> [11 of 46] Compiling Util             ( src/Util.hs, dist/build/Util.o )
> [12 of 46] Compiling CmdLine          ( src/CmdLine.hs, dist/build/CmdLine.o )
> [13 of 46] Compiling HSE.Bracket      ( src/HSE/Bracket.hs, dist/build/HSE/Bracket.o )
> [14 of 46] Compiling HSE.Evaluate     ( src/HSE/Evaluate.hs, dist/build/HSE/Evaluate.o )
> [15 of 46] Compiling HSE.All          ( src/HSE/All.hs, dist/build/HSE/All.o )
> [16 of 46] Compiling Settings         ( src/Settings.hs, dist/build/Settings.o )
> [17 of 46] Compiling Idea             ( src/Idea.hs, dist/build/Idea.o )
> [18 of 46] Compiling Report           ( src/Report.hs, dist/build/Report.o )
> [19 of 46] Compiling Test.Proof       ( src/Test/Proof.hs, dist/build/Test/Proof.o )
> [20 of 46] Compiling Refact           ( src/Refact.hs, dist/build/Refact.o )
> [21 of 46] Compiling Hint.Type        ( src/Hint/Type.hs, dist/build/Hint/Type.o )
> [22 of 46] Compiling Hint.List        ( src/Hint/List.hs, dist/build/Hint/List.o )
> [23 of 46] Compiling Hint.Monad       ( src/Hint/Monad.hs, dist/build/Hint/Monad.o )
> [24 of 46] Compiling Hint.Bracket     ( src/Hint/Bracket.hs, dist/build/Hint/Bracket.o )
> [25 of 46] Compiling Hint.Naming      ( src/Hint/Naming.hs, dist/build/Hint/Naming.o )
> [26 of 46] Compiling Hint.Pattern     ( src/Hint/Pattern.hs, dist/build/Hint/Pattern.o )
> [27 of 46] Compiling Hint.Import      ( src/Hint/Import.hs, dist/build/Hint/Import.o )
> [28 of 46] Compiling Hint.Pragma      ( src/Hint/Pragma.hs, dist/build/Hint/Pragma.o )
> [29 of 46] Compiling Hint.Extensions  ( src/Hint/Extensions.hs, dist/build/Hint/Extensions.o )
> [30 of 46] Compiling Hint.Duplicate   ( src/Hint/Duplicate.hs, dist/build/Hint/Duplicate.o )
> [31 of 46] Compiling Hint.Comment     ( src/Hint/Comment.hs, dist/build/Hint/Comment.o )
> [32 of 46] Compiling Hint.Unsafe      ( src/Hint/Unsafe.hs, dist/build/Hint/Unsafe.o )
> [33 of 46] Compiling Hint.Util        ( src/Hint/Util.hs, dist/build/Hint/Util.o )
> [34 of 46] Compiling Hint.ListRec     ( src/Hint/ListRec.hs, dist/build/Hint/ListRec.o )
> [35 of 46] Compiling Test.Translate   ( src/Test/Translate.hs, dist/build/Test/Translate.o )
> [36 of 46] Compiling Hint.Match       ( src/Hint/Match.hs, dist/build/Hint/Match.o )
> [37 of 46] Compiling Hint.Lambda      ( src/Hint/Lambda.hs, dist/build/Hint/Lambda.o )
> [38 of 46] Compiling Hint.All         ( src/Hint/All.hs, dist/build/Hint/All.o )
> [39 of 46] Compiling Apply            ( src/Apply.hs, dist/build/Apply.o )
> [40 of 46] Compiling Language.Haskell.HLint2 ( src/Language/Haskell/HLint2.hs, dist/build/Language/Haskell/HLint2.o )
> [41 of 46] Compiling Grep             ( src/Grep.hs, dist/build/Grep.o )
> [42 of 46] Compiling Test.Annotations ( src/Test/Annotations.hs, dist/build/Test/Annotations.o )
> [43 of 46] Compiling Test.All         ( src/Test/All.hs, dist/build/Test/All.o )
> <command line>: can't load .so/.DLL for: /Users/roman/.cabal/lib/x86_64-osx-ghc-8.0.1/text-1.2.2.1-9Yh8rJoh8fO2JMLWffT3Qs/libHStext-1.2.2.1-9Yh8rJoh8fO2JMLWffT3Qs-ghc8.0.1.dylib (dlopen(/Users/roman/.cabal/lib/x86_64-osx-ghc-8.0.1/text-1.2.2.1-9Yh8rJoh8fO2JMLWffT3Qs/libHStext-1.2.2.1-9Yh8rJoh8fO2JMLWffT3Qs-ghc8.0.1.dylib, 5): Library not loaded: /usr/local/opt/ghc/lib/ghc-8.0.1/binary-0.8.3.0/libHSbinary-0.8.3.0-ghc8.0.1.dylib
>   Referenced from: /Users/roman/.cabal/lib/x86_64-osx-ghc-8.0.1/text-1.2.2.1-9Yh8rJoh8fO2JMLWffT3Qs/libHStext-1.2.2.1-9Yh8rJoh8fO2JMLWffT3Qs-ghc8.0.1.dylib
>   Reason: image not found)
> cabal: Leaving directory '/var/folders/p8/41kg47m97xdcvft_zqxhfry00000gn/T/cabal-tmp-20731/hlint-1.9.37'
> cabal: Error: some packages failed to install:
> hlint-1.9.37 failed during the building phase. The exception was:
> ExitFailure 1

```
ghc --version
```

> The Glorious Glasgow Haskell Compilation System, version 8.0.1 

```
cabal --version
```

> cabal-install version 1.24.0.0
> compiled using version 1.24.0.0 of the Cabal library

**Comment by ndmitchell** [comment]
What does `ghc-pkg check` say? It looks like your text install is borked by a broken binary install.

**Comment by ndmitchell** [comment]
I'm assuming its a general setup issue, not HLint specific, because HLint doesn't really have control over how it is linked itself.
