### ISSUE TITLE
Parse error: *

### ISSUE THREAD

**Issue by Saulzar** [ndmitchell/hlint#269]
I'm seeing this, something to do with the type operator I guess?

test1 :: forall n. KnownNat n => Proxy n -> Proxy (n \* 3)

/home/oliver/Projects/hDNN/src/HDNN/Exp.hs: 206, 54
Parse error: *

**Comment by ndmitchell** [comment]
Thanks for the bug report. This looks a lot like https://github.com/haskell-suite/haskell-src-exts/issues/298, which was originally reported at https://github.com/ndmitchell/hlint/issues/227. If you pass `-XHaskell98` or `-XHaskell2010` to HLint does that fix it? You may need to enable other extension, or pass them on the command line.

**Comment by ndmitchell** [comment]
Closing this as a dupe of #227.
