### ISSUE TITLE
Suggest replacing 'data' with 'newtype' when possible

### ISSUE THREAD

**Issue by 23Skidoo** [ndmitchell/hlint#279]
When you have a definition like

```
data Foo = Foo Int
```

it's usually a good idea to replace it with

```
newtype Foo = Foo Int
```

even though the semantics is not 100% identical. I was surprised to find out that HLint doesn't already suggest this.

**Comment by ndmitchell** [comment]
Good idea!

**Comment by ndmitchell** [comment]
Done in #282.

**Comment by 23Skidoo** [comment]
Awesome, thanks!
