### ISSUE TITLE
Confusing reporting of "(-w/2)"

### ISSUE THREAD

**Issue by DougBurke** [ndmitchell/hlint#29]
With

~~~~
% cat Delme.hs 
module Foo where
foo p = case p of
  A -> 0
  B w -> -w
  C w -> (-w/2)
~~~~

I get 

~~~~
% hlint Delme.hs 
Delme.hs:2:9: Warning: Redundant bracket
Found:
  case p of
      A -> 0
      B w -> -w
      C w -> (-(w / 2))
Why not:
  case p of
      A -> 0
      B w -> -w
      C w -> -(w / 2)

1 suggestion
~~~~

Note that it claims it found the text `(-(w/2))` when it is actually `(-w/2)`. This is not a particularly serious issue, but I thought I'd note it here. If I change the line to use `-(w/2)` then hlint accepts it.

I am using

~~~~
% hlint --version
HLint v1.8.57, (C) Neil Mitchell 2006-2014
~~~~

**Comment by ndmitchell** [comment]
This has been fixed with haskell-src-exts 1.16.0.1 (probably got fixed before that, but I've only just retested).
