### ISSUE TITLE
sequence/sequenceA $ map/fmap ==> traverse

### ISSUE THREAD

**Issue by Alok** [ndmitchell/hlint#290]
^ I think `traverse` is generally more readable when you want to compose `sequence` and `fmap` as it conveys the *intention* pretty well.

**Comment by ndmitchell** [comment]
So concretely you are suggesting `sequenceA (map f x) ==> traverse f x` ? I already have rules for `sequence (map f x) ==> mapM f x`, so you are suggesting I add for `fmap` as well as `map` (seems reasonable) and for `sequenceA (map f x) ==> traverse f x` - also reasonable. I'd prefer to stick to `sequence` being replaced by `mapM` as those functions "go together", and are defined in terms of each other, in the same way `sequenceA` and `traverse` are a matched pair.

**Comment by ndmitchell** [comment]
Added all the combinations.
