### ISSUE TITLE
Warn when the OverloadedStrings extension is unused

### ISSUE THREAD

**Issue by expipiplus1** [ndmitchell/hlint#303]
Similarly to https://github.com/ndmitchell/hlint/issues/299 this can't catch all cases, but we can be sure that this extension isn't in use when there are no string literals in the file.

**Comment by ndmitchell** [comment]
I'm a bit more sceptical here - how many files don't have any string literals?

**Comment by expipiplus1** [comment]
What made me think of this is this: I was moving some functions out of one module and into another, to save some time I copied over all the imports and extensions too, and got the computer to remove the redundant lines. This file happened to contain no string literals but `OverloadedStrings` wasn't removed.

Of the 501 haskell files in our codebase at least 187 have no string literals in. Hastily tested using `ag -G '\.hs$' '"' -l | wc -l` and `ag -G '\.hs$' '"' -L | wc -l`. Although this might be a little higher than average as lots of our code is destined for the FPGA where strings are not representable.

I've just realised that this extension might break in the presence of template Haskell generating string literals, this goes for lots of other redundant language extension warnings too though.

**Comment by expipiplus1** [comment]
Testing a larger sample, of the haskell files in `/nix/store` on my machine 25905 files ending in `.hs` do not contain `"` and 36259 do.

**Comment by ndmitchell** [comment]
Hmm, maybe strings aren't as common as I thought! I'll compare to my code base and see if it's similar.

**Comment by ndmitchell** [comment]
Hmm, in my repos its easily 90+% which have string literals...

**Comment by expipiplus1** [comment]
How interesting!

**Comment by ndmitchell** [comment]
Done.
