### ISSUE TITLE
Warn when the DataKinds extension is unused (partial)

### ISSUE THREAD

**Issue by expipiplus1** [ndmitchell/hlint#313]
I don't think that this extension can be in use when there are no type constructors in a program!

This is probably the least useful partial warning I've come up with!

**Comment by ndmitchell** [comment]
Can't you go far better and say it's unused when you don't have any `:: *-> *` declarations of similar? I imagine that's most programs. Or when do you see data kinds required for type constructors?

**Comment by expipiplus1** [comment]
I'm not quite sure what you mean by "`:: * -> *` declarations or similar"

This program for examples uses DataKinds: `main = print (Proxy @ True)`

**Comment by ndmitchell** [comment]
I thought that program used type application. I guess my understanding of data kinds is very different from yours - first step is to concretely have some examples of programs that require the `DataKinds` extension, so we can figure out where the boundary is.

**Comment by expipiplus1** [comment]
Well, it uses DataKinds as the `True` term constructor has been promoted to be used at the type level. Sorry, the use of TypeApplication was gratuitous!

**Comment by ndmitchell** [comment]
Ah, so it really is "no data types" - my thoughts are that is probably just too many false positives to add.

**Comment by expipiplus1** [comment]
I don't think there should be any false positives, but it'll certainly miss cases where the extension is actually redundant.

**Comment by ndmitchell** [comment]
OK, given how general it is I'm not going to add a warning.
