### ISSUE TITLE
Configuring --cpp-include and other flags in HLint.hs or new yaml format

### ISSUE THREAD

**Issue by bergmark** [ndmitchell/hlint#314]
Is there a way to do this or a recommended practice? I'd rather avoid doing this externally with a Makefile if possible.

**Comment by ndmitchell** [comment]
Excellent idea, and not one I'd already thought of. I'll see what I can do.

**Comment by ndmitchell** [comment]
Done. See `hlint --default` for examples of all the things in the new config format. The only thing on my todo list before a release is to update the readme, so if you see anything else you think is worse or could be improved, please let me know.

**Comment by bergmark** [comment]
Thank you thank you!
