### ISSUE TITLE
Confusing error message when passing single dashed option to executable

### ISSUE THREAD

**Issue by bergmark** [ndmitchell/hlint#315]
Can this be improved?

```
$ hlint -cpp-include include/ .
Could not read, expected one of: never always auto
```

**Comment by ndmitchell** [comment]
You would imagine it could say at least `got: pp-include` which should give you a hint as to why it has failed.

**Comment by ndmitchell** [comment]
Using cmdargs-0.10.6 as a dependency I get:

```
C:\Neil\hlint>hlint -cpp-include include/ .
Could not read "pp-include", expected one of: never always auto
```

Does that seem sufficient?

**Comment by bergmark** [comment]
Are never always auto valid arguments to -c? If so this is great, otherwise still a big improvement!

**Comment by ndmitchell** [comment]
They are indeed valid arguments to --color, and -c is the short flag of that.

**Comment by bergmark** [comment]
Thanks you Neil!
