### ISSUE TITLE
Documentation for Yaml side

### ISSUE THREAD

**Issue by nponeccop** [ndmitchell/hlint#317]
Currently I could only find documentation in source code:

https://github.com/ndmitchell/hlint/blob/9d630199f69a2852cee918fa463cc3956d270ee4/src/Hint/Match.hs#L4

**Comment by ndmitchell** [comment]
Is https://github.com/ndmitchell/hlint#customizing-the-hints enough? The idea is that default.yaml has enough in it that you will learn everything, see https://github.com/ndmitchell/hlint/blob/master/data/default.yaml which is the output of `--default`.

**Comment by nponeccop** [comment]
My point is that neither of this files mentions `side:` key and the mini-language within it.

**Comment by ndmitchell** [comment]
True, and I never mentioned that for the Haskell format that came before. My reasoning was that for most hints it's not required, and where it is, learning by example from the `hlint.yaml`/`HLint.hs` that ships with HLint is the best approach. Should I say it exists and point people at `hlint.yaml`? Should I do something more? The `side:` language is pretty adhoc and changes at my whim, so not keen to advertise it that widely.

**Comment by nponeccop** [comment]
Ah, my impression was that the `side:` language is a new feature. If it's an old feature that is not officially exposed to end users it's another story. The desision not to expose it is completely reasonable.

**Comment by ndmitchell** [comment]
Yep, it's an old feature. I've added a few notes in the readme on where the additional documentation and examples live.
