### ISSUE TITLE
hlint-2.0 and custom settings

### ISSUE THREAD

**Issue by RyanGlScott** [ndmitchell/hlint#320]
I noticed that the `lens` library's `hlint` test suite started experiencing lots of failures (see https://github.com/ekmett/lens/issues/723) after upgrading to `hlint-2.0`. What's odd is that many of the new `hlint` suggestions (e.g., Redundant lambda) are things which should be ignored, [according to `lens`'s `HLint.hs`](https://github.com/ekmett/lens/blob/9baeed0a8b38cbb310925c86d622b5775d8aa194/HLint.hs#L4)!

This has made me wonder: did `hlint` stop reading from `HLint.hs` in 2.0? I noticed that the [current `README`](https://github.com/ndmitchell/hlint/blob/736d477596e08814c6426c8673a2c96cc6cdb83b/README.md#customizing-the-hints) mentions that you should be using YAML nowadays to specify these configurations, but it doesn't say anything about whether support for `HLint.hs` is being maintained. If `HLint.hs` isn't used anymore in 2.0, is there a migration story for transitioning `HLint.hs` over to YAML? I imagine we'll need to support both configurations for a bit, so being able to change one and update the other automatically would be very helpful.

**Comment by ndmitchell** [comment]
Sorry, it's a bug, it's meant to have worked. I'll get a 2.0.1 out.

**Comment by ndmitchell** [comment]
HLint stopped reading from `./HLint.hs` by default - that was an oversight. I've fixed it, 2.0.1 will be out in 10 mins or so.

The YAML is preferred, rewriting it is pretty easy, run `hlint --default` to see what the YAML should look like. I suggest you stick with `HLint.hs` until you're ready to demand `hlint > 2` and then switch entirely to the YAML.
