### ISSUE TITLE
redundant bracket: lots of such `suggestions` but always also 1 `warning`

### ISSUE THREAD

**Issue by metaleap** [ndmitchell/hlint#321]
Thanks to my own peculiar, previously-unlinted coding style, any file I send to `hlint` yields multiple dozens of `redundant bracket` notices. Fine! What I do notice: there is always exactly **1 and only 1** "redundant bracket" that is annotated with a `severity` of `Warning`, while all others to follow are `Suggestion`.

(Invocation from VScode basically uses `hlint` args: `--color=never -j --cross --json` plus a list of file paths.) 

Is this by design? How to interpret this difference? The cases seem all interchangably/equally (un)"serious" at first glance. Possibly some off-by-one / State bug as there is always exactly 1 warning preceding in all files of my project (Use module export list)?

Happy to provide a repro json output with a few corresponding .hs files if needed

**Comment by ndmitchell** [comment]
The intended difference is that if the term is atomic (never requires bracketing) then it's a warning, and if the context means you don't need brackets then its a suggestion. For example, `"test"`, `1`, `[x,y,z]` are all terms that never require brackets. In comparison, `(f x y) + z` doesn't require brackets but there are certainly places where `f x y` alone would. Does that make sense?

**Comment by metaleap** [comment]
It does! Thanks for clarifying
