### ISSUE TITLE
Clarify when severity=Error and how to ignore errors in --json outputs, plus: "erroneous" json when error is present

### ISSUE THREAD

**Issue by metaleap** [ndmitchell/hlint#323]
Under what circumstances is a severity of `Error` ever reported? I'm *presuming* only parse/syntax errors, but any `hlint`-specific "error" conditions one might expect?

When hlinting multiple files at once and one has a syntax error (producing for that file a single severity="Error" hlint record), **currently the entire json output is rendered unparseable** (see below). Ideally is there a flag to just ignore errors (for folks whose editor tooling will handle those separately on-save anyway) and silently skip further processing of that one file ie simply just output nothing for such files?

Here's what I mean by "unparsable": *actual* linebreaks (incorrect) each preceeding one (correct) `\n` escape-sequence. Which is both redundant and invalid (broadly speaking, usually unparsable) JSON:

![screenshot from 2017-04-08 02-46-12](https://cloud.githubusercontent.com/assets/22109/24824054/c416378e-1c05-11e7-8480-7a9c5f1d838f.png)

Easy to workaround of course by stripping linebreaks off the `--json` output before parsing.

**Comment by metaleap** [comment]
Closed as inconsequential. Severities are actually explained in readme. Fixing JSON output for unmarshaling is trivial. Then ignoring errors also becomes trivial.

**Comment by ndmitchell** [comment]
Outputting incorrect JSON is never acceptable. I'll switch to using aeson for generating the JSON since that's now a dependency anyway.

**Comment by ndmitchell** [comment]
Which version of HLint were you using? I don't believe the JSON output is ever malformed in recent versions, but if you think it is please let me have a test case.

**Comment by metaleap** [comment]
`--version` gives 2.0.1 and I did in fact just clone it some ~2-3 days ago

**Comment by ndmitchell** [comment]
Ok, that should work. Do you have a way to reproduce? I'll try experimenting as well.

**Comment by metaleap** [comment]
Heh, seems like a slightly insidious bug! Just re-cloned / rebuilt `hlint` and did a very simplistic test case with a minimal-module-with-syntax-error and `hlint`'s JSON output was correct (oddly enough, no `severity="Error"` elements were emitted *at all* here, though --- that's fine for a linter however IMHO)

The only next thing I could try was to reproduce the original situation that lead to the OP screenshot. To do so, you'd have to:

* temporarily put [this src folder](https://github.com/metaleap/haxtatic/tree/master/src) somewhere
* provoke the same syntax error by [removing the equals sign in Posts.hs#239](https://github.com/metaleap/haxtatic/blob/master/src/Posts.hs#L239)
* a few folder-levels up from `src`, run with all these args and only these:

        [~/.../foo]$ hlint --color=never --json -j --cross --no-exit-code -XHaskell2010 dir/with/src/Posts.hs dir/with/src/Pages.hs > hlintfoo.json

You should see a similarly erroneous json as in the above screenshot: indeed that just occured at my end with the current hlint I just cloned+rebuilt half an hour ago! If not, it must be something super-obscure such as "only happening on German-keyboard Dell laptops with Korora 25 installed"   😁

**Comment by metaleap** [comment]
Just occurred to me are the faulty lines being printed to stderr by any chance? I'm reading both pipes [combined](https://golang.org/pkg/os/exec/#Cmd.CombinedOutput) (a bad idea anyway) and the same might be happening when one does `hlint --args > file.json`. Worth investigating I reckon

**Comment by ndmitchell** [comment]
No luck reproducing from that repo. When you do `>` alone you aren't combining the pipes, and capturing stderr explicitly gives me nothing, so don't see what that can be. With cpphs it does sometimes write to stdout, so that could mess things up, but doesn't seem to be here.

**Comment by metaleap** [comment]
How strange indeed! I can't imagine what random quantum quirk might be causing this at my end then. Building with stack? ghc 8.0.2? Nevermind, when it does occur it is eassily handled.

**Comment by ndmitchell** [comment]
Windows GHC 7.10.2 with Cabal - so plenty different. I have a guess about `\r` characters - can you try HEAD.

**Comment by ndmitchell** [comment]
To be concrete, I now escape `\r` in HEAD, so try that and confirm.

**Comment by metaleap** [comment]
Your hunch was spot-on, that fixed it! Must be carry-over Windows

**Comment by ndmitchell** [comment]
Thanks for testing. I just release hlint-2.0.2 with this fix in it.
