### ISSUE TITLE
Minor quirk with "Eta reduce": position-range exceeds actual refactor-suggestion range

### ISSUE THREAD

**Issue by metaleap** [ndmitchell/hlint#326]
(Not sure whether this is only-for-Eta-reduce or only-for-top-level-definitions, but the example should be enough to repro if interested.)

By "position-range" I mean the span between `StartLine`/`StartColumn` and `EndLine`/`EndColumn` in `--json` output. By "refactor-suggestion range" I mean the span of text actually captured by the `From`/`To` fields. Here's the picture story.

The `Eta reduce` suggestions typically span sub-expressions (let/where) in terms of position-range:

![screenshot from 2017-04-11 08-42-16](https://cloud.githubusercontent.com/assets/22109/24896295/8b0241cc-1e94-11e7-9321-80aae138db27.png)

However, their `From` snippet (in the tooltip, "current code") doesn't:

![screenshot from 2017-04-11 08-42-54](https://cloud.githubusercontent.com/assets/22109/24896352/ca0ab39a-1e94-11e7-9657-1c09680516e2.png)

This means if one were to naively apply the suggestion without sanitizing the range to match the `From` length..

![screenshot from 2017-04-11 08-43-07](https://cloud.githubusercontent.com/assets/22109/24896439/39fcb482-1e95-11e7-91c1-79ebe5f2b6df.png)

..one could lose the sub-expressions!

![screenshot from 2017-04-11 08-46-29](https://cloud.githubusercontent.com/assets/22109/24896458/52226d4a-1e95-11e7-856c-dc3c3338274c.png)

Client code could work around this by ditching the `EndLine`/`EndColumn` info and recompute these based on the length of `From` (if the editor API assists in translating txtlen-vs-poscol-pairs --- right now I'll skip this entirely as it's just not a constantly recurring use-case in reality ;)  --- but been wondering about this since pretty much nigh-all other hlint suggestions, far as I can tell so far, seem to readily provide a `To`/`From` pairing properly consistent with the given start-to-end position-range

**Comment by ndmitchell** [comment]
Fixed in HEAD.

**Comment by metaleap** [comment]
Fixed indeed! Much obliged =)
