### ISSUE TITLE
Detecting spurious uses of fail

### ISSUE THREAD

**Issue by tekul** [ndmitchell/hlint#328]
I just ran into a bug where I was trying to get Attoparsec to fail [if some text wasn't Base64](https://github.com/tekul/jose-jwt/blob/5fff7166bf932cc9cfa60b0a6ef7005d24b2b6f6/Jose/Internal/Parser.hs#L142). I would generally avoid`fail` but it seemed like the only option, and I didn't notice the (now painfully obvious) mistake.

I thought it might be a useful enhancement to detect calls to `fail` within inappropriate contexts, notably monads which will raise an exception if it is called.

**Comment by ndmitchell** [comment]
This is very much type-driven, and HLint doesn't have a clue which type you are in, so I don't think it could be particularly helpful. I would also say that I personally only use fail in contexts where I'm expecting it to raise an exception, so I've gone the other way to you. I would certainly agree that "raise an exception" and "backtrack" probably shouldn't have the same name!

**Comment by tekul** [comment]
Ok, I see. Would detecting `either (fail e) ...` be a possibility, (as opposed to `either (const (fail e))`, which is what I meant) ?  I guess it's not a common thing, so feel free to close the issue (not a mistake I will make again anyway :-)).

I couldn't find any other way to tell Attoparsec to give up at that point,  other than to call `fail`. I would definitely have avoided it otherwise.

**Comment by ndmitchell** [comment]
Detecting `either (fail e)` is possible. I guess the real issue here is that the `Reader` monad has an instance of `fail`, which I imagine is never what people actually expect. Happy to detect `either (fail e)` if you think it is common/plausible for someone else to fall into the same trap.

I don't have anything different for attoparsec other than `fail`, which is a shame.

**Comment by tekul** [comment]
Thanks a lot for the speedy responses. I don't think it's likely to be very common (it's just rather nasty), so I'll leave it up to you to decide.

**Comment by ndmitchell** [comment]
I'm glad I know about it, but I don't think any pattern I write in HLint will regularly detect much, so I'm going to leave it for now.
