### ISSUE TITLE
Standard input gone, can we get it back?

### ISSUE THREAD

**Issue by lunaryorn** [ndmitchell/hlint#342]
According to the changelog hlint 2.0 removes standard input, i.e. you can no longer pass "-" to make hlint lint the standard input.  

Unfortunately the Visual Studio Code extension for hlint used this feature to lint the buffer and is silently broken now, see https://github.com/hoovercj/vscode-haskell-linter/issues/19.

Would it be possible to add this feature back?

**Comment by ndmitchell** [comment]
Certainly. I'll have a release out tonight - sorry to hear it caused problems for you - I had (incorrectly) assumed no one was using it.

**Comment by ndmitchell** [comment]
Released as hlint 2.0.8.

**Comment by lunaryorn** [comment]
@ndmitchell Thanks a lot.  :+1:
