### ISSUE TITLE
argsSettings is still looking for HLint.hs in the data dir

### ISSUE THREAD

**Issue by alanz** [ndmitchell/hlint#344]
It seems that `readSettingsFile` is still looking for the ".hs" extension.

See https://github.com/ndmitchell/hlint/blob/master/src/Language/Haskell/HLint3.hs#L77 and following

It results in a file does not exist error for `.../share/x86_64-linux-ghc-8.0.2/hlint-2.0.8/HLint.hs`

**Comment by alanz** [comment]
@ndmitchell hlint 2.0.8 is now in https://www.stackage.org/nightly-2017-06-12, this is likely to start hitting more users.

I do not know enough about the innards of this to attempt a fix.

**Comment by ndmitchell** [comment]
Thanks for the ping @alanz - I've now fixed it and released 2.0.9. The old API still won't pick up a user `.hlint.yaml` file, which is one of the big advantages of the new HLint version, and I'm hoping will integrate into IDE's. Do you have any suggestions as to what the "ideal" API would look like for an IDE?

**Comment by alanz** [comment]
At this stage we are finding that using `argSettings` and the `Hlint3` API works fine, but have not really tested it in the wild, especially with config files.

I dare say as usage picks up we will be able to give more constructive feedback.

Thanks for the update.
