### ISSUE TITLE
Suggestions for LambdaCase

### ISSUE THREAD

**Issue by nikomi** [ndmitchell/hlint#35]
The next version of haskell-src-exts will support LambdaCase - the current HEAD already does - see https://github.com/haskell-suite/haskell-src-exts/commit/ce195e50129313c5bfdf6cf6d4aff5b6d7f2666e

A future version of HLint could add suggestions for LambdaCase like:

found:
`do { foo <- bar; case foo of ... }`
why not:
`bar >>= \case`

found:
`f x = case x of ...`
why not:
`f = \case`

What do you think?

**Comment by ndmitchell** [comment]
See #377, where lambda case was implemented. You get that hint on:

```haskell
foo = bar $ \ x ->
    case x of
        A -> a
        B -> b
```
