### ISSUE TITLE
Add fromMaybe foo $ fmap f x

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/hlint#352]
Should be `maybe foo f x`. Also spot `<$>` as an alias for `fmap`.

**Comment by mitchellwrosen** [comment]
This already works for `fromMaybe foo (fmap f x)` and `fromMaybe foo $ fmap f x`, but not `fromMaybe foo (f <$> x)`

**Comment by ndmitchell** [comment]
The `$` vs brackets is built into the matcher automatically. I added a special extra case for `<$>` instead of fmap.
