### ISSUE TITLE
Detect _ <- mapM

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/hlint#353]
Sometimes people suppress the warning about discarding monadic values in a bad way. Should detect that.

**Comment by mitchellwrosen** [comment]
This is a `Stmt -> Stmt` rule, which can't currently be defined. I wonder, should there be a new syntax for such rules, or should they more cleverly re-use the `lhs`/`rhs` keys?

**Comment by ndmitchell** [comment]
I was imagining it would be custom code in Monad.hs, where we already have a list of the functions with `_` equivalents. See https://github.com/ndmitchell/hlint/blob/master/src/Hint/Monad.hs#L52

**Comment by ndmitchell** [comment]
Note that we already detect `do mapM f xs; return 1` for example, in Monad.hs, so `do _ <- mapM f xs; return 1` is just a generalisation of that.

**Comment by joneshf** [comment]
In a similar vein, how would you feel about similar detection for `for`/`traverse`?

**Comment by ndmitchell** [comment]
@joneshf - delighted! I've done it for those, and also `sequenceA` - will be in the next release.

**Comment by joneshf** [comment]
Awesome! thanks!
