### ISSUE TITLE
Per module ignore in `HLint.hs` erroneously applies to whole project

### ISSUE THREAD

**Issue by bitemyapp** [ndmitchell/hlint#354]
Cf. https://github.com/ndmitchell/hlint/issues/117#issuecomment-307928186

```
{-# ANN module "HLint: ignore" #-}

module HLint where
```

```
$ make hlint
hlint -XQuasiQuotes .
No hints (179 ignored)
```

If I comment it out:

```
-- {-# ANN module "HLint: ignore" #-}

module HLint where
```

(tons of output, stuff that needs cleaned up)

The ability to ignore files (`HLint.hs` in this case) would solve my problem and I am not sure why the annotation gets scoped to the entire HLint run. Something to do with `hint` perhaps? I do not know.

**Comment by ndmitchell** [comment]
Now we use .yaml files that whole issue of colliding with a real module has gone.
