### ISSUE TITLE
Suggest using Control.Monad.State.gets when possible

### ISSUE THREAD

**Issue by link2xt** [ndmitchell/hlint#356]
See https://github.com/jgm/pandoc/commit/39a8359b571ba0aa1e193b0ff9ef6252acc7a754

**Comment by ndmitchell** [comment]
Thanks, seems like a good idea - provided we don't clash with `get` due to `Binary` too much.

**Comment by mitchellwrosen** [comment]
Would these rules be added to `data/default.yaml`, or is that for `base` only?

**Comment by ndmitchell** [comment]
See #14 for a discussion about how to do linters for libraries. Basic answer is that I have little to no idea how to do it - putting it into `data/default.yaml` is probably the pragmatic short-term solution and then worry about it if it gets too big.

**Comment by ndmitchell** [comment]
We have state monad hints now.
