### ISSUE TITLE
Github API rate limit exceeded

### ISSUE THREAD

**Issue by mitchellwrosen** [ndmitchell/hlint#366]
Not an `hlint` bug, but I didn't quite know were to file this :)

When running in Travis with the one-liner from the `README`, I would occasionally get annoying `curl: no URL specified` errors. Turns out, the build machine is hitting a Github API rate limit for calls to `api.github.com` from [this script](https://raw.githubusercontent.com/ndmitchell/neil/master/misc/travis.sh), which ends up setting `URL=`, and the script finally crashes when running something like `curl --progress-bar --location -o.hlint-P6HBN/hlint.tar.gz` (notice the lack of a URL argument at the end).

Perhaps this deserves a mention in the README? Thanks!

**Comment by ndmitchell** [comment]
I got this error from Appveyor all the time, so rewrote the appveyor script to avoid it. But I've never seen it from my Travis instances, and I run this HLint script on 10+ projects and 4-8 GHC versions each. Is it still occuring? Why am I not seeing it?

**Comment by mitchellwrosen** [comment]
Oh! It's probably because I'm building a private repo.

**Comment by ndmitchell** [comment]
How often does it occur? When did it last occur? As long as it's still a real issue, I'm happy to fix it. Looking at the appveyor approach, it isn't really any more complex than the travis one, and doesn't use the API so isn't going to hit the limit.

**Comment by dzhus** [comment]
I see this all the time ever since switching to a prebuilt `hlint`. Recent examples:

https://travis-ci.org/dzhus/csg/jobs/268300056#L316
https://travis-ci.org/dzhus/snaplet-redis/jobs/268304007#L320
https://travis-ci.org/dzhus/simple-vec3/jobs/268300176#L308

It can usually be "fixed" by restarting the build job.

**Comment by ndmitchell** [comment]
Fixed in https://github.com/ndmitchell/neil/commit/e0288a2b9f4d3637d9f1cb1df7f7be2c88d132ec - let me know if it reoccurs.
