### ISSUE TITLE
HLint Skip the Main Function Check 

### ISSUE THREAD

**Issue by wisn** [ndmitchell/hlint#379]
I knew that HLint is a tool for code improvement in Haskell. It would be great if HLint check the main function first then suggest a code improvement. Please take a look on [this issue](https://github.com/coala/coala-bears/issues/2011) on coala HaskellLintBear.

**Comment by ndmitchell** [comment]
The idea is that you run your code through the compiler first. HLint doesn't attempt to catch errors.

**Comment by wisn** [comment]
I see...

In the future, is it possible to implement [this one](https://ghc.haskell.org/trac/ghc/ticket/13190) on HLint?

**Comment by ndmitchell** [comment]
Hlint can already dump errors to JSON. However, it can't do anything relating to GHC errors.

**Comment by Makman2** [comment]
> The idea is that you run your code through the compiler first. HLint doesn't attempt to catch errors.

If that's the case you should improve the message to suggest this imo. Otherwise I would think that `hlint` would do this itself as a linter at least to some degree (like it has some syntax error detection to avoid weird parsing errors).

**Comment by ndmitchell** [comment]
The code you wrote isn't a syntax error, and with suitable libraries, you could even make it do what you are expecting. Only a compiler knows it isn't correct.

**Comment by Makman2** [comment]
That's why I suggest to extend the message to something like this: :smile:

> Check Haskell code for possible problems by running the Haskell compiler again.

**Comment by ndmitchell** [comment]
Are you suggesting I extend the message when HLint has nothing to report to also say "beware, you might want to compile your code too"? I would have thought that was obvious given the intended audience... Maybe if that's suitable for users of HaskellLintBear then it should be adding that message? Or perhaps even actually compiling the code with GHC before running the linter (certainly Haskell IDE's do that).

**Comment by wisn** [comment]
It's all clear for me now, @ndmitchell. Thank you!
Are you still on this, @Makman2?

**Comment by Makman2** [comment]
> Are you suggesting I extend the message when HLint has nothing to report to also say "beware, you might want to compile your code too"?

Oh man sorry my bad... I've totally misunderstood the original issue (https://github.com/coala/coala-bears/issues/2011). The phrase `Check Haskell code for possible problems` is our documentation of `HaskellLintBear.py`, I thought this message was emitted by our bear running over some Haskell code with `hlint`.
Nvm then :+1:

> Or perhaps even actually compiling the code with GHC before running the linter (certainly Haskell IDE's do that).

Yeah that's something we have to consider from coala-side :)
