### ISSUE TITLE
Print refactorings as JSON in JSON output

### ISSUE THREAD

**Issue by lunaryorn** [ndmitchell/hlint#380]
`hlint --json` output currently looks as follows:

```
[
  {
    "module": "Main",
    "decl": "",
    "severity": "Warning",
    "hint": "Use fewer imports",
    "file": "-",
    "startLine": 31,
    "startColumn": 1,
    "endLine": 31,
    "endColumn": 29,
    "from": "import Data.String (unlines)\nimport Data.String (unlines)\n",
    "to": "import Data.String (unlines)\n",
    "note": [],
    "refactorings": "[Delete {rtype = Import, pos = SrcSpan {startLine = 32, startCol = 1, endLine = 32, endCol = 29}}]"
  }
]
```

I'm interested in the `refactorings` field to map the Hlint suggestions to VSCode text edits in my [lhlint extension](https://github.com/lunaryorn/vscode-hlint).  

Currently I'm feeding the contents of this field to `apply-refact` but that has a couple of issues.  It's rather slow for individual refactorings, and doesn't map well to VSCode's internal way of applying code suggestions because it always replaces the entire document.

The underlying type from refact however maps quite well to VSCode text edit actions so I'd prefer to directly turn refactorings into "native" text edits.

Unfortunately the current format of `refactorings` is not too easy to parse from Javascript.  

Would it be possible to convert this field to JSON? I can prepare a PR but I'm absolutely not familiar with the Hlint code base and would need some guidance.

**Comment by ndmitchell** [comment]
That seems like an excellent idea, question is how to integrate with apply-refact as well. One option would be for the redact-types module to expose a JSON conversion then everyone could use the same JSON.

@mpickering - any thoughts?

**Comment by ndmitchell** [comment]
@lunaryorn - are you closing this because it's no longer interesting to you?

@zliu41 as the refactor guru at this point.

**Comment by lunaryorn** [comment]
@ndmitchell Yeah, I don't care for this anymore.
