### ISSUE TITLE
Parse error on file accepted by ghc

### ISSUE THREAD

**Issue by pjljvandelaar** [ndmitchell/hlint#386]
The following example file

```
module Case

where

example :: Int -> IO (Int)
example n  =  do
     case n of
     { 0 -> return 0
     ; _ -> return 1
     }
```

gives on windows the following response with hlint:

```
C:\TorXakisSandbox\hlint>hlint Case.hs
Case.hs:8:6: Error: Parse error
Found:
    example n  =  do
         case n of
  >      { 0 -> return 0
         ; _ -> return 1
         }

1 hint
```

Yet is accepted by ghc:

```
C:\TorXakisSandbox\hlint>ghc Case.hs
[1 of 1] Compiling Case             ( Case.hs, Case.o )
```
I assume this is a bug.

**Comment by ndmitchell** [comment]
This is a bug in the underlying haskell-src-exts library that HLint builds upon. I've raised it at https://github.com/haskell-suite/haskell-src-exts/issues/381.

**Comment by Anabra** [comment]
Another bug, but in a different context:

```
{-# LANGUAGE BangPatterns #-}
module RecordPattern where

data Rec = Rec { num :: Int }

f :: Rec -> Int
f Rec { num = !num } = num
```

HLint cannot parse the last line.

**Comment by ndmitchell** [comment]
Thanks @Anabra, raised upstream again https://github.com/haskell-suite/haskell-src-exts/issues/382

**Comment by Anabra** [comment]
Another one:

```
{-# LANGUAGE TypeApplications #-}
module TypeApp where

f = show @Integer (read "5")
```
HLint cannot parse the last line. I guess HSE is the culprit again.

**Comment by ndmitchell** [comment]
@Anabra - which version of hlint are you using? And which haskell-src-exts library version is installed? Testing your example, it works for me. Looking at the [changelog](http://hackage.haskell.org/package/haskell-src-exts-1.19.1/changelog), I suspect haskell-src-exts1.18.2 fixes the bug.

**Comment by vlatkoB** [comment]
With `hlint 2.1.11`, `haskell-src-exts-1.20.3`, getting parse error on `hoistServerWithContext api (Proxy @a) convertApp` if LANGUAGE pragma is not inside the file. 
Tried putting `TypeApplications` explicitely in `.hlint.yaml` 
```
- extensions:
  - name: [ TypeApplications ]
```
but no change

**Comment by ndmitchell** [comment]
@vlatkoB - it's really a separate issue, so I've moved it to #572

**Comment by ndmitchell** [comment]
Confirmed works with HEAD that doesn't use HSE for parsing, so fixed in the next release.
