### ISSUE TITLE
pattern matching prevents "use let"-hint to trigger

### ISSUE THREAD

**Issue by pjljvandelaar** [ndmitchell/hlint#387]
When hlint is applied to the following file:
```
module UseLet
where
function :: [Int] -> [(Int,Int)] -> IO [Int]
function a b = do
    h <- return $ head a
    (x,y) <- return $ unzip b
    return $ x ++ [h] ++ y
```
only one hint is provided:
```
UseLet.hs:6:16: Suggestion: Use let
Found:
  do h <- return $ head a
     (x, y) <- return $ unzip b
     return $ x ++ [h] ++ y
Why not:
  do let h = head a
     (x, y) <- return $ unzip b
     return $ x ++ [h] ++ y

1 hint
```
When one fixes this hint, hlint provides no more hints.

I would however like to end up with:
```
module UseLet
where
function :: [Int] -> [(Int,Int)] -> IO [Int]
function a b = do
    let h = head a
    let (x,y) = unzip b
    return $ x ++ [h] ++ y
```
Is this a bug? Is this a new feature request?

**Comment by ndmitchell** [comment]
The second transformation wouldn't be correct. Specifically:

```haskell
do (x,y) <- return undefined
   print "hello"
```

That returns undefined, but if you do the `let` transformation it prints `hello`. It's generally the right thing to do, but HLint just doesn't know enough to be sure they are the same.
