### ISSUE TITLE
Suggest "fmap f m" from "m >>= pure . f" and "pure . f =<< m"

### ISSUE THREAD

**Issue by contivero** [ndmitchell/hlint#393]
Hlint currently suggests that when using `return` instead of `pure`, but there is no equivalent hint for `pure`. I personally prefer `f <$> m`, but since `fmap` is what's currently being suggested, I stuck with that.

**Comment by ndmitchell** [comment]
Makes a lot of sense. FWIW, recommended fmap since it was in the Prelude but <$> wasn't. Now that is no longer the case I'd welcome a PR to suggest <$> in return and pure cases.
