### ISSUE TITLE
Suggest x $> y for x *> pure y, and similar expressions.

### ISSUE THREAD

**Issue by contivero** [ndmitchell/hlint#395]
The suggestions would be:

| LHS          |   RHS |
| ----------------- |:----------:|
| `x *> pure y`    | `x $> y` |
| `x >> return y` | `x $> y` |
| `return x << y` | `x <$ y` |
| `pure x <* y`    | `x <$ y` |

Although I guess the following are also valid:

| LHS          |   RHS |
| ----------------- |:----------:|
| `x >> pure y`  | `x $> y` |
| `x *> return y` | `x $> y` |
| `return x <* y` | `x <$ y` |
| `pure x << y`  | `x <$ y` |

If you are ok with them, I'll work on a PR.

**Comment by ndmitchell** [comment]
All look like a great idea. Only thing to note is you should write `Data.Functor.$>` so it tells people where to find the operator, if the module is in scope HLint unqualifies it automatically.

**Comment by ndmitchell** [comment]
In fact, it feels like maybe suggesting this for *> makes sense, but >> seems to change the "intent" of the program, purely in how it feels, not the actual semantics. Am tempted to say start with *> only for now.
