### ISSUE TITLE
Allow module wildcards

### ISSUE THREAD

**Issue by eborden** [ndmitchell/hlint#402]
In large projects you often want to enforce explicit silos of modules. These layers reduce the chance of circular dependencies and keep things a bit more sane. The module restriction feature could work perfectly for this if it had wildcards.

```
- modules:
  - {name: [Foo.Bar.*], within: [Foo.Bar.*, Foo]}
  - {name: [Foo.Qux.*], within: [Foo.Qux.*, Foo]}
```

This is likely a weaker form of the intention behind https://github.com/ndmitchell/lasagna

**Comment by ndmitchell** [comment]
I like the idea. Only question is what is the semantics of module wildcards? Does it match 0, 1 or many? Should the valid wildcards the * (0 or more), + (1 or more), ? (exactly 1) to match regex? Or should it be * and ** ?

**Comment by eborden** [comment]
Good question. My original intention was that `*` acts like a glob with 0 to many.

`Foo.Bar.*` matches multiple segments
```
Foo.Bar.Baz
Foo.Bar.Baz.Qux
...
```

`Foo.Bar*` matches:
```
Foo.Bar
Foo.BarBaz
Foo.Bar.Baz
Foo.Bar.Baz.Qux
...
```

However, a more complicating matching grammer might be better or just falling back to regex proper.

**Comment by ndmitchell** [comment]
Are there any existing semantics in some well used module matching tool we can fall back on?

**Comment by eborden** [comment]
Hmm not that I'm aware of, but it is worth the research.

**Comment by pbrisbin** [comment]
My proposal would be to mimic shell path expansion. It's probably well-defined and shell nerds like myself would find it perfectly intuitive.

For example,

```
Foo.* matches
Foo.Bar, and
Foo.Baz, but not
Foo.Bar.Baz

Foo.**.* matches all of the above

Foo.**.*Spec mathes Spec modules at any depth.
```

**Comment by eborden** [comment]
That seems pretty reasonable since modules are essentially just paths.

**Comment by eborden** [comment]
@ndmitchell Any thoughts on this path? I can start on a PR if we have a path.

**Comment by ndmitchell** [comment]
My thoughts are probably the right way to go is take the `FilePattern` library that is in Shake, extract it out to a standalone library, and then use it for both this and for #334. Of course, that makes it a fairly reasonably sized chunk of work which involves pulling apart a lot of Shake...

**Comment by eborden** [comment]
That sounds like a sane approach. I'll open an issue over at `shake` in case I lose steam, so this path is at least documented.

**Comment by tfausak** [comment]
Sorry to revive an old issue, but I am also interested in this feature. Is there anything that I can do to move things along? @eborden extracted the file pattern library mentioned above and opened a PR to use it in Shake (https://github.com/ndmitchell/shake/pull/551). Even if that PR doesn't land, it seems like we could use the file pattern library to get this done. Is that right?

**Comment by eborden** [comment]
I was just thinking of this the other day. We could atleast get `filepattern` up on hackage.

**Comment by eborden** [comment]
Opened an issue here: https://github.com/eborden/filepattern/issues/3

**Comment by ndmitchell** [comment]
I don't disagree. This is my main open source project at the moment - I was hacking on it last night. I think I've got down to one open design question, and am looking towards a release soon.

**Comment by ndmitchell** [comment]
Now filepattern is on Hackage at https://hackage.haskell.org/package/filepattern.

It should be possible to just use `?==` and `replace "." "/"` to get it working.

**Comment by peti** [comment]
I am curious about the current state of affairs of this PR. Is anyone actively working on this feature? (My guess is that the answer is "no" given the rather extensive time-line.)

**Comment by ndmitchell** [comment]
I'm unaware of any progress. The prerequisite of getting filepattern on Hackage has been complete, but nothing since.

**Comment by tfausak** [comment]
I made a PR for this: <https://github.com/ndmitchell/hlint/pull/1149>.

**Comment by ndmitchell** [comment]
Note the comment on https://github.com/ndmitchell/hlint/pull/1149#issuecomment-704471359 alludes to some bits that aren't yet complete.

**Comment by tfausak** [comment]
I've got a PR for the rest of this: #1221.
