### ISSUE TITLE
Catch redundant brackets around overloaded labels

### ISSUE THREAD

**Issue by 3noch** [ndmitchell/hlint#403]
Hlint says nothing about `(#label)` when it could/should be `#label`.

**Comment by ndmitchell** [comment]
It's an issue in the underlying version of haskell-src-exts-util (although totally a bug I wrote). I've submitted a PR upstream.

**Comment by 3noch** [comment]
Very prompt! Thanks.

**Comment by 3noch** [comment]
Feel free to close here.
