### ISSUE TITLE
Unnecessary hiding hint fires unnecessarily

### ISSUE THREAD

**Issue by dzhus** [ndmitchell/hlint#404]
HLint version: `HLint v2.0.10, (C) Neil Mitchell 2006-2017`
GHC: `The Glorious Glasgow Haskell Compilation System, version 8.0.2`

Consider this example:

```haskell
{-# LANGUAGE RecordWildCards #-}

import Control.Arrow hiding (first)
import Types

whoIsOnFirst :: BaseInfo -> String
whoIsOnFirst _ = "Who"

main :: IO ()
main = print $ whoIsOnFirst BaseInfo{..}
  where
    first = "blah"
```

where `Types.hs` is
```haskell
module Types

where

newtype BaseInfo = BaseInfo { first :: String }
```

If I hide `first` from `Control.Arrow`, I get «Unnecessary hiding» suggestion from hlint:
```
./src/Main.hs:3:1: Suggestion: Unnecessary hiding
Found:
  import Control.Arrow hiding (first)
Why not:
  import Control.Arrow

1 hint
```

Hiding is in fact necessary here to avoid name clash while using `RecordWildCards` with a record type imported from a different module. If I don't hide `first`, I get name shadowing warning from GHC:

```
/Users/dmitrydzhus/projects/hlint-repro/src/Main.hs:12:5: warning: [-Wname-shadowing]
    This binding for ‘first’ shadows the existing binding
      imported from ‘Control.Arrow’ at src/Main.hs:3:1-20
```

Here's a repo to reproduce this with `hlint`/`stack build`: https://github.com/dzhus/hlint-unnecessary-hiding-bug-example.

In a real-world example I might be using other functions from `Control.Arrow`, so «Redundant import» warning may be ignored.

**Comment by JoeMShanahan** [comment]
Has this issue been approved as a genuine bug?

**Comment by ndmitchell** [comment]
Sorry, I read but forgot to comment. It is a genuine issue, and I can’t think of a good way round it. I may just remove the hiding hint.

**Comment by DevJac** [comment]
I'm experiencing this bug because I do `import GI.Gtk hiding (main)` in the `Main` module. HLint tells me that hiding `main` is unnecessary, even though I also have `main :: IO ()` as the entry point to my program (as most Haskell programs do). If I don't hide `main` from `Gi.Gtk` the two functions are ambiguous.

I mention this because it is a slightly different case, and because it might help others find this issue when searching.

**Comment by ndmitchell** [comment]
@DevJac - can you point at a file that has exactly this issue? From what I understand, that shouldn't happen.

**Comment by DevJac** [comment]
Sure. First, note that I am using `HLint v2.0.11`. I confirmed this is happening on an early version of my project here: https://github.com/DevJac/go-review-tool/tree/d670439af3d414100e7a02468e54bd81736fb346

When I run `hlint src/Main.hs` in a shell, I get:
```
src/Main.hs:2:1: Suggestion: Unnecessary hiding
Found:
  import GI.Gtk hiding (main)
Why not:
  import GI.Gtk

1 hint
```

**Comment by ndmitchell** [comment]
Thanks, the more I look at this code the less I recognise it... I need to git blame, and then start thinking about why/what/how it was meant to do.

**Comment by JonnyRa** [comment]
I _think_ in the cases I've seen it (sorry I can't be more concrete) that it will work correctly if you hide something that conflicts with something defined in the file you are currently in, but not if you are importing two different things with conflicting names.

eg:
```
import A hiding (x)
import B -- also has x
```
reports the hiding of x as unecessary.

but where you have

```
import A hiding (x)

data Something = Something { x :: String }
```

the warning (correctly) won't be triggered.

I'm running `HLint v2.0.11, (C) Neil Mitchell 2006-2017`

**Comment by ndmitchell** [comment]
This reverts most of #360 by @mitchellwrosen, but unfortunately there's no realistic way to keep this hint and have warning freedom. Shame :(

**Comment by ip1981** [comment]
Make it suggest "do not use `hiding`" :)

**Comment by ip1981** [comment]
As well as `RecordWildCards`. There is always a nice way to write the same code without it.

**Comment by ndmitchell** [comment]
@ip1981 opinions vary on both of those things, you can certainly make use of `RecordWildCards` a failure using the restriction feature: https://github.com/ndmitchell/hlint#restricting-items
