### ISSUE TITLE
"Parse error" on function type signature

### ISSUE THREAD

**Issue by jasonstolaruk** [ndmitchell/hlint#412]
Hlint v2.0.10 is giving me the following parse error, although the code does compile.

```
./lib/Mud/Cmds/Util/Pla.hs:1849:1: Error: Parse error
Found:
  > helperGiveEitherCoins :: HasCallStack => Id
                                          -> Desig
                                          -> ToId
```

The full function may be found [here](https://github.com/jasonstolaruk/CurryMUD/blob/e3e0db8cc26cf0a1dc8d31459368bbd4a1e2466d/lib/Mud/Cmds/Util/Pla.hs#L1849).

Thanks!

**Comment by ndmitchell** [comment]
See https://github.com/haskell-suite/haskell-src-exts/issues/386, it's an upstream bug in haskell-src-exts. You can fix it by removing the totally redundant where at https://github.com/jasonstolaruk/CurryMUD/blob/e3e0db8cc26cf0a1dc8d31459368bbd4a1e2466d/lib/Mud/Cmds/Util/Pla.hs#L1841 (which ironcially is a hint HLint would have made, it if had been able to parse it in the first place!).

**Comment by jasonstolaruk** [comment]
Wow, good find! I didn't know I had a redundant `where` there. I removed it and it fixed the parse error. Thanks!

**Comment by ndmitchell** [comment]
Confirmed works with HEAD that doesn't use HSE for parsing, so fixed in the next release.
