### ISSUE TITLE
"Parse error" on multi-way if.

### ISSUE THREAD

**Issue by jasonstolaruk** [ndmitchell/hlint#414]
Hlint v2.0.11 is giving me the following parse error, although the code does compile.

```
./lib/Mud/TheWorld/Zones/AdminZone.hs:147:43: Error: Parse error
Found:
            calcCanCarryMouthfuls amt = let (myWeight, myMaxEnc) = (calcWeight `fanUncurry` calcMaxEnc) (i, ms)
                                        in if | myWeight + (amt * mouthfulWeight) > myMaxEnc
  >                                           , margin <- myMaxEnc - myWeight
                                              -> floor (margin `divide` mouthfulWeight :: Double)
                                              | otherwise -> amt
```

The full function may be found [here](https://github.com/jasonstolaruk/CurryMUD/blob/b130f0d81e5ba769b0d5c861b4d101d7b99d200b/lib/Mud/TheWorld/Zones/AdminZone.hs#L145).

Thanks!

**Comment by ndmitchell** [comment]
Thanks! Reported upstream at https://github.com/haskell-suite/haskell-src-exts/issues/391.

**Comment by ndmitchell** [comment]
Confirmed works with HEAD that doesn't use HSE for parsing, so fixed in the next release.
