### ISSUE TITLE
Support operator fixities from lens out of the box

### ISSUE THREAD

**Issue by yairchu** [ndmitchell/hlint#416]
I believe `lens` became pretty prevalent, and occasionally `hlint` (out of the box, without telling it the fixities) gives wrong hints, like this one:

    Suggestion: Use >=>
    Found:
      \x -> a <&> f .~ x >>= b
    Why not:
      ((.~) (a <&> f) >=> b)

Here's such a hint file that works for me:
https://github.com/lamdu/lamdu/blob/master/tools/hlint-rules.hs

**Comment by ndmitchell** [comment]
Excellent idea! I also noted that the `baseFixities` I use from haskell-src-exts are missing a few of the newer ones. I'll wait for them to respond then figure out how I move forward (whether they go upstream, in the HLint source file, or in a `hlint.yaml` file) - but they should go somewhere.

**Comment by ndmitchell** [comment]
I raised a final set at https://github.com/haskell-suite/haskell-src-exts/issues/395. Let's confirm those go in, then add the lens ones to HLint.

**Comment by ndmitchell** [comment]
I now have a PR to fix up haskell-src-exts, but in the meantime I observe the lens fixities list has moved and now gives an error. Any idea where the file lives now? If it's going to move again, perhaps put the contents in a gist?

**Comment by yairchu** [comment]
> I observe the lens fixities list has moved and now gives an error

oops, updated the link.. and here's a gist: https://gist.github.com/yairchu/ca6b2ab2abad542e327dd63062bd2548

**Comment by ndmitchell** [comment]
Great, I just baked them in the source code for now (you could argue they should be in the hlint.yaml, but in practice, it doesn't make a huge amount of difference for maintaining).
