### ISSUE TITLE
Using HLint binary on Stack Travis

### ISSUE THREAD

**Issue by lwm** [ndmitchell/hlint#417]
Hey there! I was trying to speed up the HLint matrix build over at the Stack repository since I saw [the 'Running with Continuous Integration' documentation](https://github.com/ndmitchell/hlint#running-with-continuous-integration). As noted in https://github.com/commercialhaskell/stack/issues/3674, we run HLint a bunch of times there with different options - so I changed your script into [etc/scripts/get-hlint.sh](https://github.com/lwm/stack/blob/e07b591147c1c6d1fcf75cc00edf8ce773989eb9/etc/scripts/get-hlint.sh) and then tried to just [rip out the exe and run it on the Travis setup](https://github.com/commercialhaskell/stack/pull/3676/files#diff-354f30a63fb0907d4ad57269548329e3). I got [the following error](https://travis-ci.org/commercialhaskell/stack/jobs/318733054#L605):

``` BASH
++case "$BUILD" in
++./hlint src/
hlint: user error (Failed to find requested hint files:
  /home/travis/build/commercialhaskell/stack/data/hlint.yaml
)
```

That stumped me - I tried to `./hlint -h .hlint.yaml src` but got the same error.

Is there any way to get the binary to accept our custom `.hlint.yaml` through this method?

Sorry for the essay ;) Thanks!

**Comment by ndmitchell** [comment]
Hlint will look for the data files adjacent to the executable so moving it breaks that. You could move more, or leave it where it is.

However, even if you are running HLint multiple times, why not use the provided script? You’ll download HLint a bunch of times but you preserve the abstraction and it probably isn’t that much time anyway. If it is a big deal I can look for ways of dealing with it on my side - eg an install flag to my script.

**Comment by lwm** [comment]
Ah, I see. Well, the whole motivation is to get the fastest possible feedback from Travis. Downloading the same script 3 times over the network probably won't get my patch merged ;) It'd be great to see an install flag, and I think it makes sense, since some HLint options need to be run separately.

**Comment by ndmitchell** [comment]
If you want to argue something on performance grounds you need to measure it. Perhaps the second download is cached and takes a few milliseconds? Perhaps the first download is quick anyway and the entire time is negligible? If you measure it takes a non trivial amount of time and doing it 3 times is 3 times that non trivial value then I’m happy to fix it. I’d go for the simple/obvious solution first.

**Comment by lwm** [comment]
I agree I'd have more of a case if this was taking ages to download - it is not.

I'll rig something up on my end. Thanks.

**Comment by ndmitchell** [comment]
If it’s taking long enough for you to rig something on your end I’ll certainly put something on my side instead.
