### ISSUE TITLE
Make HLint able to comment on Github PRs

### ISSUE THREAD

**Issue by lwm** [ndmitchell/hlint#418]
I'd love if plain HLint could spit back comments onto Github pull requests with hints. 

I saw that the danger gem can do this but I'd like to avoid the ruby environment.  I assume you wouldn't accept this into HLint core - do you have any ideas for 'plugins' or how they might interact? Do you already have 'contrib' modules?

Looking into how this might be possible, it seems to be just a plain old HTTP request after reading some environment variables (as I saw in [this python bot](https://github.com/koddsson/travis-github-pr-bot/blob/master/travis_bot/travis_bot.py)).

**Comment by ndmitchell** [comment]
How many dependencies would it add? That's my only hesitation around accepting it into the core - given that github is the main repo, and PR reviewing is a significant purpose, it seems like an important thing to have. If you still think it should be outside there is a `misc/` directory where a few contributed scripts live.

**Comment by lwm** [comment]
I'll take a look and if it drags in too much, I'll write back here and let's see. Thanks!

**Comment by ndmitchell** [comment]
My suggestion would be build something on top of the HLint API, and consider it a separate tool, HLint-with-github, since it feels like these integrations don't necessarily belong in the core. Closing from here, but if you do produce anything, let me know and I'll link to it.
