### ISSUE TITLE
`!!` in restricted functions does not seem to work.

### ISSUE THREAD

**Issue by NorfairKing** [ndmitchell/hlint#432]
I tried these:

```
 - {name: '!!', within: []}
 - {name: '(!!)', within: []}
```

Both don't find `!!`.

**Comment by ndmitchell** [comment]
Are you using HLint HEAD? For me it works following #429 with `'!!'` on:

```haskell
foo = neil !! 12
```

**Comment by ndmitchell** [comment]
Please reopen if you see this happening with the release I'm going to make in 10 minutes.
