### ISSUE TITLE
Ignoring duplication hints in specs

### ISSUE THREAD

**Issue by pbrisbin** [ndmitchell/hlint#433]
This seems related to #370. I'm finding it difficult to ignore duplication within specs.

Given:

```yaml
---
- ignore: {name: "Redundant do", within: spec}
- ignore: {name: "Reduce duplication", within: spec}
```

And:

```hs
module Spec where

spec :: Spec
spec = describe $ do
    it "has a redundant do here" $ do
      2 `shouldBe` 2

    it "has duplicated setup for the sake of clarity here" $ do
        x <- fromY
        z <- fromX x
        x `shouldBe` z

    it "and here" $ do
        x <- fromY
        z <- fromX x
        x `shouldBe` z

    it "and here" $ do
        x <- fromY
        z <- fromX x
        x `shouldBe` z
```

The redundant-do ignore works, but the reduce-duplication does not.

After a fair amount of confusion, I believe I understand why: because duplication is a cross-function issue, it can't be ignored at the function level.

This makes technical sense. However, as a naive end-user, I believe that if all the duplication _happens to be_ within a single function, it should be ignorable at that level as well. So I think my example should produce no hints. And in fact, the common "duplication across spec examples" case would almost always be contained within a single `spec` function, so I wouldn't consider it an edge-case.

In the reproduction example, I can make it work by changing the ignore to:

```yaml
---
- ignore: {name: "Reduce duplication", within: Spec}
```

But that won't work in any real-world project, where spec modules are named after the modules they test, not just one giant `Spec.hs`.

If #402 were implemented, we would do this:

```yaml
---
- ignore: {name: "Reduce duplication", within: "**.*Spec"}
```

But at present, that's not available (and is apparently a parse error).

I can see a few directions to take this Issue:

- Is there a gap in documentation that ignores work this way for specific hints?
- Is it a valid feature request that hints like duplication can be ignored by function if the cases found happen to be function-local?

Please let me know your thoughts.

**Comment by ndmitchell** [comment]
Thanks, all cleaned up now - and I found similar issues in the restrict hints which I solved too.

**Comment by pbrisbin** [comment]
Awesome! I didn't expect such a quick fix -- thank you!

**Comment by pbrisbin** [comment]
Closing as this was fixed back in 2018 (!). Thanks.
