### ISSUE TITLE
Add fixity for (Data.Monoid.<>)

### ISSUE THREAD

**Issue by yairchu** [ndmitchell/hlint#438]
`<>` is a popular operator that's lacking the fixity definition for it (`infixr 6 <>`). This can cause rules to misfire.

I'm not sure if the right place to add it is a PR to [haskell-src-exts](https://github.com/haskell-suite/haskell-src-exts/blob/master/src/Language/Haskell/Exts/Fixity.hs#L162) or in hlint.

**Comment by yairchu** [comment]
On it :)

**Comment by yairchu** [comment]
Created a PR there - https://github.com/haskell-suite/haskell-src-exts/pull/400

Got some more rules for lens but for me some of them misfired without this fixity. I guess I'll contribute those once this fixity is fixed?

**Comment by ndmitchell** [comment]
Happy to take a PR adding them in a new section "base not yet in HSE" - otherwise you'll have to wait for a new HSE release, which can take a while.

**Comment by ndmitchell** [comment]
Fixed by #439.
