### ISSUE TITLE
Suggest simplifying `join (x <$> y)` to `x >>= y`

### ISSUE THREAD

**Issue by 3noch** [ndmitchell/hlint#443]
Suggest simplifying `join (x <$> y)` to `x >>= y`

**Comment by ndmitchell** [comment]
Done! With `x =<< y`, because that's semantically correct :)

Thanks for the idea.

**Comment by 3noch** [comment]
Oops. Yes :) Thank you!

**Comment by 3noch** [comment]
cc. @alexfmpe (your idea!)
