### ISSUE TITLE
Better `--help` for enabling extra hint groups.

### ISSUE THREAD

**Issue by yairchu** [ndmitchell/hlint#444]
The `--help` text has nothing about enabling or disabling hint groups.

The `-w` option seems to be for individual hints only.

**Comment by ndmitchell** [comment]
Do you know how to enable extra hint groups? I'm not sure I do, but if you do, I'll put it in the docs. I think you can do it with a `.hlint.yaml` somehow... Putting extra docs are a good idea.

**Comment by yairchu** [comment]
I forgot for a moment that in Haskell projects and common DRY style usually used the `--help` text reflects the existing options by constructions. So this means groups can only be enabled with a `.hlint.yaml` file? Are you in favor of a patch to add a command line option to enable/disable groups too? If so I'll make one.

**Comment by ndmitchell** [comment]
Yep, a flag to enable groups sounds like a good idea.
