### ISSUE TITLE
HLint Parse error

### ISSUE THREAD

**Issue by LeanderK** [ndmitchell/hlint#450]
(i am using Haskell IDE Engine)

```haskell
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE GADTs                  #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE TypeInType #-}
module Test where

import           Data.Singletons.Prelude
import           Data.Singletons.TypeLits
import           Data.Type.Equality            ((:~:) (..), (:~~:) (..))

data instance Sing (z :: (a :~: b)) where
    SRefl :: Sing Refl
```

resulting in:
```
[hlint]
Parse error: :~:
```

**Comment by ndmitchell** [comment]
Thanks for the bug report, I've raised it upstream in the parser I use as https://github.com/haskell-suite/haskell-src-exts/issues/402.

**Comment by LeanderK** [comment]
I have another, looks like I am using crazy features 🙂 I have opened a bug report on HSE
haskell-suite/haskell-src-exts#403

**Comment by ndmitchell** [comment]
Thanks @LeanderK !

**Comment by ndmitchell** [comment]
Confirmed works with HEAD that doesn't use HSE for parsing, so fixed in the next release.
