### ISSUE TITLE
False warning for Data.Binary.get

### ISSUE THREAD

**Issue by yairchu** [ndmitchell/hlint#452]
https://github.com/ndmitchell/hlint/commit/7a415316b46f5595dac4d0e83b23800161b62ace introduced new rules for `Control.Monad.State.get`, but those also catch other `get`s like that from `Data.Binary` and give irrelevant suggestions.

Example case: https://github.com/lamdu/lamdu/blob/master/src/System/Random/Utils.hs#L14

**Comment by ndmitchell** [comment]
Thanks, I restrict it, but then we get into problems with having to match `get` from lots of different state-like modules. If only there was a way to specify equivalent functions... #434
