### ISSUE TITLE
Check comments are well formed for Haddock

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/hlint#456]
Sometimes people write comments that won't go through haddock due to a syntax error in Haddock world. Checking that in HLint would be useful.

**Comment by ndmitchell** [comment]
Goes wrong with:

```
cmd = cmdArguments mempty -- ^ [bob]
```

**Comment by ndmitchell** [comment]
```
data Bob = Bob
    Int -- ^ field
    Int -- ^ field 2
```

**Comment by ndmitchell** [comment]
It would be much nicer if GHC did this.

**Comment by ndmitchell** [comment]
https://gitlab.haskell.org/ghc/ghc/-/merge_requests/2377 is working on it, so let's leave it to them.

**Comment by shayne-fletcher** [comment]
> https://gitlab.haskell.org/ghc/ghc/-/merge_requests/2377 is working on it, so let's leave it to them.

It's fair to say Vlad is working his heart out on this one.
