### ISSUE TITLE
Document restriction feature, especially around extensions

### ISSUE THREAD

**Issue by mightybyte** [ndmitchell/hlint#458]
Would you consider the addition of a feature that allows HLint to enforce user-defined policies on the use of language extensions?  For instance, you might want to have a project where certain language extensions are banned (perhaps `IncoherentInstances`) and for large teams you want to have stronger enforcement than just hoping that peer review catches it.

**Comment by ndmitchell** [comment]
HLint actually already has this feature - see https://github.com/ndmitchell/hlint/blob/master/.hlint.yaml#L10-L16 for an example where I use it on HLint itself. I default extensions to false, then turn on the ones I want, and for CPP only turn it on in selected files.

Works really nicely in large commercial projects, which is what I wrote it for. Unfortunately, in common with large commercial projects, it's inadequately documented 😉. I'll use this ticket to document it.

**Comment by mightybyte** [comment]
Perfect!

**Comment by ndmitchell** [comment]
Documented! https://github.com/ndmitchell/hlint#restricting-items
