### ISSUE TITLE
Parse error on type splices in TH

### ISSUE THREAD

**Issue by pikajude** [ndmitchell/hlint#46]
``` haskell
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE QuasiQuotes #-}

import Language.Haskell.TH

test :: ()
test = $(do
    let ty = return $ ConT ''()
    [| () :: $(ty) |])
```

hlint reports a parse error on line 9 at `$(`, despite the presence of the QuasiQuotes and TemplateHaskell pragmas.

**Comment by ndmitchell** [comment]
Just tested and fixed in haskell-src-exts-1.16.0.1. Probably got fixed before that.
