### ISSUE TITLE
Ridiculous memory requirements

### ISSUE THREAD

**Issue by mcandre** [ndmitchell/hlint#463]
Hi, I'm trying to install HLint via Cabal in a HardenedBSD VM, but it looks like with even 4GB of RAM, GHC is still unable to compile HLint due to the strain on memory while compiling its many dependencies. Can we improve this situation, perhaps by selecting more minimalist dependencies that are easier to compile?

**Comment by ndmitchell** [comment]
If you do `cabal install hlint -j1` at what point does it fall down? My guess is the `haskell-src-exts` package, but it would be good to confirm. Once you know which package it is I suggest investigating with that specific package is the way forward (turning down optimisation, disabling profiling etc).

**Comment by mcandre** [comment]
Yes, haskell-src-exts is one place where cabal runs out of memory. I'll try some of the cabal options for disabling features and see if that helps.

**Comment by ndmitchell** [comment]
Oh, and I regularly install haskell-src-exts on 32bit Windows, which is limited to 4Gb RAM by construction.

**Comment by ndmitchell** [comment]
I suggest just trying `cabal install haskell-src-exts` as that's a smaller test case.

FWIW my instructions for installing on a RAM limited machine are at https://github.com/ndmitchell/hoogle/blob/master/docs/Haskell.org.md (that's for Hoogle, but it also depends on haskell-src-exts, so may well be the same).

**Comment by mcandre** [comment]
So this turns out to be an issue specifically on UNIX hosts with `W^X` enabled, such as HardenedBSD and OpenBSD.

**Comment by ndmitchell** [comment]
Not directly an HLint issue, so closing.
