### ISSUE TITLE
"Use ." rule confused by Esqueleto expression

### ISSUE THREAD

**Issue by pbrisbin** [ndmitchell/hlint#466]
(HLint v2.1)

Example expression, a pretty standard Esqueleto join of parent/child:

```hs
myJoin =
  on $ child ^. ChildParentId ==. parent ^. ParentId
```

Suggestion:

```
example.hs|2 col 8 warning| Warning: Use .. Found: child ^. ChildParentId ==. parent ^. parentId Why not: (child ^. ((ChildParentId ==. parent) . parentId))
```

So, with that update:

```hs
myJoin =
  on $ child ^. ((ChildParentId ==. parent) . parentId)
```

Which is a bit gibberish, AFAICT :)

I can't really follow what the rule is attempting to do, so I can't say if this is a general pattern worth fixing or just an edge-case of Esqueleto expressions, which I'm happy to work around via ignore in my own code base.

**Comment by ndmitchell** [comment]
This is fallout from the lens rules that @yairchu added, partly because HLint doesn't parse the fixity of `==.` properly.

One option is to restrict to only matching `^.` if you have imported the lens library. Another is to add the fixity of `==.`.

**Comment by jezen** [comment]
For future readers: I managed to silence hlint with these lines in my `.hlint.yaml`.

```
- fixity: "infix 4 ==."
- fixity: "infixl 9 ^."
```

**Comment by ndmitchell** [comment]
Thanks, given that works, and given at least 3 users seem to be putting thumbs on things, I added the ==. fixity to HLint as standard.
