### ISSUE TITLE
Define __GLASGOW_HASKELL__

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/hlint#476]
When doing CPP I should define __GLASGOW_HASKELL__ to the version HLint was compiled with (an approximation for what suits the user)

**Comment by benbellick** [comment]
Hey @ndmitchell! I am looking to get involved with the open source Haskell community. Is this still an open issue? I see that it is from 5 years ago. Maybe that's old enough that you don't even remember 😄

**Comment by zliu41** [comment]
@benbellick I added the `good first issue` tag to a few more issues. Feel free to take on any of them (or any other open issue that interests you).

**Comment by benbellick** [comment]
@zliu41 Thank you! I will take a look at these.

**Comment by juhp** [comment]
Any hints or sketch for this?

**Comment by zliu41** [comment]
@juhp HLint currently defines `__HLINT__` when running CPP (see CmdLine.hs). Neil is suggesting to also define `__GLASGOW_HASKELL__`, so that if the module contains `#if __GLASGOW_HASKELL__ > ...`, the (hopefully) correct branch is taken.

**Comment by juhp** [comment]
Thanks that is helpful :-)

The only tricky thing seems to be how/where to do the CPP: hlint hardly seems to use CPP itself (obviously it can't be used in `CmdLine.hs` itself).

**Comment by juhp** [comment]
Okay I opened a PR for this
