### ISSUE TITLE
mistake use const for hamlet template haskell code

### ISSUE THREAD

**Issue by ncaq** [ndmitchell/hlint#483]
example code.
[hlint-use-const-mistaken.hs](https://gist.github.com/ncaq/f8133e14fe64f68f99738c1cd647d0c5)

run hlint this code, hlint `Suggestion: Use const`.
However, URL argument is needed.

`#{foo}` ok.
`@{foo}` ng.

**Comment by ndmitchell** [comment]
Thanks for the bug report, reproducing the relevant lump I see:

```haskell
{-# LANGUAGE QuasiQuotes #-}
main = f (\url -> [hamlet|foo @{url}|])
```

A tricky one. I use the free variables to check that a hint is safe, but in this instance I can't see inside the quasi-quote. I need to be conservative here, but a lot of hints don't care about free variables at all, so I don't want to penalise them. I'll have a think.

**Comment by ndmitchell** [comment]
I went for the broad rule of if you have a lambda in the LHS of the hint, and a quasi quote before substitution, just skip the rule. Pretty targeted but catches the ones that potentially have a problem.
