### ISSUE TITLE
Parse error when using @ notation with space in pattern matching

### ISSUE THREAD

**Issue by Bubba** [ndmitchell/hlint#492]
Currently trying to parse a pattern match @ with a space following the variable name causes a parse error:
```
foo :: Maybe Int -> Bool
foo a @(Just _) = False
```
It looks funny but compiles fine

**Comment by ndmitchell** [comment]
Which version of HLint and which underlying haskell-src-exts? I just tried this with the latest versions and it works fine for me.

**Comment by Bubba** [comment]
Can't seem to reproduce it anymore!
