### ISSUE TITLE
sequence/fmap

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/hlint#496]
Should that always just be mapM? e.g. `sequence (fmap f xs)`

**Comment by contivero** [comment]
If you want to maintain the `Monad` constraint, then `mapM` it is. I'd rather have it generalized to `traverse`, but maybe you want to save that for `sequenceA . fmap`

**Comment by ndmitchell** [comment]
To me, that sounds like two rules - you want the above rule, and also `mapM => traverse`, which is certainly plausible, but still not something I'm ready to add by default just yet.

**Comment by ndmitchell** [comment]
Turns out we already had the rule `- warn: {lhs: sequence (fmap f x), rhs: traverse f x}`, so just adding the one mentioned originally.
