### ISSUE TITLE
hlint defaults to using $bindir/data/hlint.yaml

### ISSUE THREAD

**Issue by juhp** [ndmitchell/hlint#503]
Not sure when this changed but recent hlint seems to fallback to looking for `$bindir/data/hlint.yaml` (where bindir is the dir where hlint is located).  At least on Linux this is not the right location of course.

I was meaning to come up with a patch, but didn't find time so I thought I better just report it first.

**Comment by ndmitchell** [comment]
It was a few versions ago when I wanted to be able to run HLint out of a downloaded binary which was not installed but merely extracted to /tmp. It tries the right locations first, so does the extra fallback causes issues?

**Comment by juhp** [comment]
Ah yeah sorry, I forgot to mention the actual problem or reproducer, doh.
Actually it may never have worked correctly in my case - I think I only tested my builds on the machine where I am building hlint.

The problem is I use a cabal sandbox to build latest hlint (this is not for official Fedora builds but for my Fedora Copr ("ppa") repo), and then install the files by hand - then I think the embedded datadir points in the wrong place and then hlint falls back to `$bindir/data/hlint.yaml`... Not sure the best way to solve this. I should probably open a cabal RFE too... ;)

**Comment by juhp** [comment]
https://github.com/fedora-haskell/hlint/blob/master/hlint.spec is the build script - yeah not nice.

**Comment by juhp** [comment]
Nevermind sorry I think I fixed this now but just doing `cabal install --only-dependencies`
and doing build and install.

**Comment by ndmitchell** [comment]
Awesome!
