### ISSUE TITLE
Test and fix refactorings

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/hlint#504]
To get the refactorings working properly it is necessary for:

* Neil to actually start using it (so it gets documented)
* Add automated tests to all operations (so they are correct)

This ticket is expected to be the overarching ticket for many refactoring tickets.

**Comment by ndmitchell** [comment]
@zliu41 - it feels like this is mostly done now? I might not be using it, but I think I will be when support comes to my IDE, and you are certainly cleaning it up pretty well with tests. Time to close this ticket, or something else you think would be good to include?

**Comment by zliu41** [comment]
@ndmitchell Looks like the reasons for the remaining @NoRefactors are
1. not supported (e.g., reduce duplication, eta reduce)
2. apply-refact bugs
3. apply-refact requires GHC extensions
4. scoping issues (e.g., should suggest `CM.forM` but suggest `forM`)
5. other hlint bugs (e.g., `f (Just a) = \a -> a + a`)

I think 1 should not prevent this ticket from being closed, but it would be nice to document which hints are not supported. 2 to 5 should probably be fixed before closing this ticket. Among these, 3 and 5 should be easy; 4 is tricky; 2 is not difficult but depends on apply-refactor maintainers [being responsive](https://github.com/mpickering/apply-refact/pull/51). (maybe you can have them add you  as a maintiner?)

**Comment by ndmitchell** [comment]
Thanks for the summary. On the basis of that I revised the README at https://github.com/ndmitchell/hlint/blob/master/README.md#automatically-applying-hints.

1. I think 1 is fine, and is a documented invariant of HLint - not everything can get automatic replacements.
2. The apply-refact bugs are problematic, and I would actually suggest they add _you_ as the maintainer since you are way more active in this area than I am and have shown great taste and development in your patches to HLint. I'll make some enquiries.
3. I see you've already got this one in hand.
5. We can fix these up as they happen.

So it sounds like we're well on our way to getting there.

**Comment by ndmitchell** [comment]
I think the refactorings are sufficiently in control that there is no longer any need for an overarching ticket. We have testing and it works very well. Thanks for all your hard work @zliu41
