### ISSUE TITLE
“Use const” suggested for lambda with quasi-quotes

### ISSUE THREAD

**Issue by dahlia** [ndmitchell/hlint#506]
It's quite similar to #427, except hlint suggests “Use const” instead.  For example:

```
Suggestion: Use const
Found:
  \ x -> [shamlet|#{x}|]
Why not:
  const [shamlet|#{x}|]
```

**Comment by ndmitchell** [comment]
Thanks for the report - I confirm that's a bug - I'll need to take quite a different approach to the previous bug though...

**Comment by ndmitchell** [comment]
Dupe of https://github.com/ndmitchell/hlint/issues/483 so will use that to track it.
