### ISSUE TITLE
HTML report interactions don't work on Firefox 59

### ISSUE THREAD

**Issue by chreekat** [ndmitchell/hlint#511]
Repro:

1. Use Firefox 59
2. Visit http://databrary.github.io/databrary/hlint.html and click on an item in the left bar
3. :
    ![image](https://user-images.githubusercontent.com/538538/42473084-8ed9ba7e-8391-11e8-824e-6e7ba1cabb99.png)

I'm not convinced this isn't an issue with Firefox itself. The trouble seems to be caused by an interpretation of the CSS Object Model spec:

> The deleteRule(index) method must run the following steps:
> 
> 1.  If the origin-clean flag is unset, throw a SecurityError exception.
> 2.  Remove a CSS rule in the CSS rules at index. 

—  https://www.w3.org/TR/cssom-1/#dom-cssstylesheet-deleterule

> origin-clean flag
> *   Set if response is CORS-same-origin, or unset otherwise. 

— https://www.w3.org/TR/cssom-1/#ref-for-concept-css-style-sheet-origin-clean-flag-5

I can't imagine why CORS would be involved when both the script and the CSS are inline, but there you have it.

**Comment by ndmitchell** [comment]
Seems like it works with Firefox 61 - can you retest to confirm I wasn't just missing it?

**Comment by chreekat** [comment]
Same behavior on 61.0.1. :/

I'm running on NixOS, which probably makes me an outlier.

**Comment by ndmitchell** [comment]
I'm on Windows. Would be great to get a third opinion if anyone is watching this thread, so we can see which of us is the outlier.

**Comment by justinwoo** [comment]
Clicking around on left bar on Ubuntu 16 LTS FF 61.0, Chrome 65.0, nothing comes up when I click around the leftbar items.

**Comment by ndmitchell** [comment]
Thanks @justinwoo !

@chreekat  I guess NixOS has turned on a super security feature, so perhaps report to NixOS?

**Comment by chreekat** [comment]
Happily, the sidebar links/filters *do* work for me on Chromium 65, so I can still use the page. :)

Thanks to both of you. I'll look into the NixOS angle.

**Comment by ndmitchell** [comment]
Thanks, closing for now as it seems elsewhere.

**Comment by chreekat** [comment]
A NixOS update fixed this problem for me. :)
