### ISSUE TITLE
Refactoring for "Redundant bracket" with <$> not applied

### ISSUE THREAD

**Issue by martin-drhu-da** [ndmitchell/hlint#529]
Given
```
f x = (g . h) <$> x
```
`hlint` tells you
```
A.hs:1:7: Suggestion: Redundant bracket
Found:
  (g . h) <$> x
Perhaps:
  g . h <$> x
```
but `hlint --refactor` does not remove the brackets but leaves the original file unchanged.

**Comment by ndmitchell** [comment]
Thanks, the refactoring isn't properly tested, so no real surprise...
