### ISSUE TITLE
Cannot expand #if directive: MIN_VERSION_Cabal(a,b,c) is not a defined macro

### ISSUE THREAD

**Issue by juhp** [ndmitchell/hlint#53]
Not quite how/when this started happening or if it might be due to newer haskell-src-exts perhaps, but anyway with recent hlint and haskell-src-exts I started seeing eg:

```
[cabal-rpm/src:master]$ hlint .
hlint: Cannot expand #if directive in file ./Commands/Spec.hs  at line 326 col 1:
    MIN_VERSION_Cabal(a,b,c) is not a defined macro
```

This doesn't happen with slightly older hlint/haskell-src-exts, eg with the hlint-1.8.50 in Fedora 20.

**Comment by Kasceh** [comment]
Guess this hasn't been fixed? Still struggling with this issue now.

**Comment by ndmitchell** [comment]
I've pinged @malcolmwallace by email, let's see what he says (I entirely forgot to talk to him when he got back).

**Comment by ndmitchell** [comment]
@malcolmwallace, concretely, running `cpphs` v1.19.3 over:

    #if defined(MIN_VERSION_Cabal) && MIN_VERSION_Cabal(1,20,0)
    #endif

Produces the error:

    cpphs: Cannot expand #if directive in file Sample.hs  at line 1 col 1:
        MIN_VERSION_Cabal(a,b,c) is not a defined macro

Is that a bug? Or does the CPP spec say that is how it should be?

However, I always do a dummy define of the CPP macros with a sensible default. e.g. in Shake I have https://github.com/ndmitchell/shake/blob/master/src/Development/Shake/FileInfo.hs#L136:

    #ifndef MIN_VERSION_unix
    #define MIN_VERSION_unix(a,b,c) 0
    #endif

And at https://github.com/ndmitchell/shake/blob/master/src/Development/Shake/FilePath.hs#L3 I have:

    #ifndef MIN_VERSION_filepath
    #if __GLASGOW_HASKELL__ >= 709
    #define MIN_VERSION_filepath(a,b,c) 1
    #else
    #define MIN_VERSION_filepath(a,b,c) 0
    #endif
    #endif

Both these are designed to work in ghci, but have a happy side effect of working in HLint as well.

**Comment by asr** [comment]
> Since HLint 1.8.60 there is the --cpp-file file flag, point that at the generated Cabal macros file and it will be included and do the right thing.

I can confirm this behaviour. I have no problems using the `--cpp-file` option.

```
$ cpphs --version
cpphs 1.19.3

$ hlint --version
HLint v1.9.29, (C) Neil Mitchell 2006-2016
```

**Comment by DougBurke** [comment]
I have a file where I've said

```
#if defined(MIN_VERSION_base) && MIN_VERSION_base(4, 7, 0)
_iType :: FiniteBits b => a -> b -> DbType
...
#endif
```

and I get

```
% hlint --cpp-file=dist/build/autogen/cabal_macros.h  lib/Types.hs 
hlint: macro MIN_VERSION_base expected 3 arguments, but was given 0
```

This is with

```
% hlint --version
HLint v1.9.28, (C) Neil Mitchell 2006-2016
% cpphs --version
cpphs 1.19.3
```

I don't have time to update to the latest hlint just now, as I have to go see Deadpool.

**Comment by asr** [comment]
I don't  use `defined(MIN_VERSION_base)`.

**Comment by juhp** [comment]
Is it possible for hlint to determine/find `cabal_macros.h` automatically?

**Comment by ndmitchell** [comment]
@juhp - that seems sensible and simple, yes, I'll definitely do that - very good idea.

**Comment by asr** [comment]
> that seems sensible and simple

I'm not sure if it is simple. Keep in mind that Cabal sandboxes don't use the default directory `dist/build` for creating the `cabal_macros.h` file. In addition, the default directory can be changed using  the `--builddir` option of cabal-install.

**Comment by asr** [comment]
From the [CHANGELOG](http://hackage.haskell.org/package/cpphs-1.20.1/changelog) of cpphs, the issue related to `#if defined(FOO) && FOO(a,b)` was fixed in cpphs 1.20.

**Comment by asr** [comment]
FYI, the bug tracker for cpphs is [here](https://github.com/malcolmwallace/cpphs).

**Comment by malcolmwallace** [comment]
Yes, cpphs-1.20.1 has the bugfixes for most of the issues mentioned in this thread.  Please try it out.

**Comment by DougBurke** [comment]
I can confirm that upgrading did seem to fix the issues for me:

* old

```
% hlint --version
HLint v1.9.28, (C) Neil Mitchell 2006-2016
% cpphs --version
cpphs 1.19.3
% hlint tools/ObsCat.hs
hlint: Cannot expand #if directive in file tools/ObsCat.hs  at line 71 col
1:
    MIN_VERSION_time(a,b,c) is not a defined macro
```

* new

```
% hlint --version
HLint v1.9.31, (C) Neil Mitchell 2006-2016
% cpphs --version
cpphs 1.20.1
% hlint tools/ObsCat.hs
tools/ObsCat.hs:244:3: Suggestion: Redundant bracket
Found:
... and a few more
```

The new version also worked on a file that was afflicted with the complaint
about containing lines like

    #if defined(MIN_VERSION_base) && MIN_VERSION_base(4, 7, 0)

So thanks to everyone for this.

**Comment by ndmitchell** [comment]
I now require cpphs-1.20.1, which hopefully fixes these issues, and also added a test specifically for this common case to hlint.

**Comment by juhp** [comment]
Thank you!  hlint-1.9.32 is working well for me so far.
