### ISSUE TITLE
Can't install with GHC 8.6.1

### ISSUE THREAD

**Issue by LeventErkok** [ndmitchell/hlint#530]
Admittedly, the issue here is with `polyparse` and not `hlint`; but I had no luck finding an issue tracker with polyparse. This makes `hlint` unusable with the `new-install` route, unfortunately.

See below for traces for both regular install and also with `--alow-newer`; both of which fail.

```
$ cabal new-install hlint
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: hlint-2.1.10 (user goal)
[__1] trying: uniplate-1.6.12 (dependency of hlint)
[__2] trying: cpphs-1.20.8 (dependency of hlint)
[__3] trying: polyparse-1.12 (dependency of cpphs)
[__4] next goal: base (dependency of hlint)
[__4] rejecting: base-4.12.0.0/installed-4.1... (conflict: polyparse =>
base<4.12)
[__4] rejecting: base-4.11.1.0, base-4.11.0.0, base-4.10.1.0, base-4.10.0.0,
base-4.9.1.0, base-4.9.0.0, base-4.8.2.0, base-4.8.1.0, base-4.8.0.0,
base-4.7.0.2, base-4.7.0.1, base-4.7.0.0, base-4.6.0.1, base-4.6.0.0,
base-4.5.1.0, base-4.5.0.0, base-4.4.1.0, base-4.4.0.0, base-4.3.1.0,
base-4.3.0.0, base-4.2.0.2, base-4.2.0.1, base-4.2.0.0, base-4.1.0.0,
base-4.0.0.0, base-3.0.3.2, base-3.0.3.1 (constraint from non-upgradeable
package requires installed instance)
[__4] fail (backjumping, conflict set: base, hlint, polyparse)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: polyparse, cpphs, base, hlint,
uniplate
```

If one tries:

```
cabal new-install hlint --allow-newer
```

It also fails with:

```
src/Text/Parse.hs:308:36: error:
    • No instance for (Control.Monad.Fail.MonadFail (Parser Char))
        arising from a do statement
        with the failable pattern ‘'K'’
    • In a stmt of a 'do' block: 'K' <- next
      In the first argument of ‘wrap’, namely
        ‘do 'C' <- next
            'K' <- next
            return '\ACK'’
      In the expression:
        do 'C' <- next
           'K' <- next
           return '\ACK'
          `wrap` "'\\ACK'"
    |
308 |     mnemonic 'A' = do 'C' <- next; 'K' <- next; return '\ACK'
    |                                    ^^^^^^^^^^^
cabal: Failed to build polyparse-1.12 (which is required by exe:hlint from
hlint-2.1.10). See the build log above for details.
```

The issue is with the new monad-fail-proposal moving `fail` out of the `Monad` class being enforced now.

**Comment by ndmitchell** [comment]
Ping @malcolmwallace

**Comment by templateK** [comment]
@LeventErkok As temporary workaround,  You may merge this commit https://github.com/bergmark/polyparse/commit/8a69ee7e57db798c106d8b56dce05b1dfc4fed37
or use https://github.com/bergmark/polyparse.git directly.

disclaimer: I don't have any relationship with this repo and I just found this repo with google.

**Comment by ndmitchell** [comment]
Is @bergmark going to release that?

**Comment by LeventErkok** [comment]
@templateK Yes, that's precisely what I did a few weeks ago when I had this problem. It's quite unfortunate though, to say the least.

**Comment by bergmark** [comment]
I'm not the maintainer of polyparse, but you can file an issue to request a non-maintainer upload at https://github.com/haskell-infra/hackage-trustees if Malcolm isn't reachable.

**Comment by ndmitchell** [comment]
Ping @malcolmwallace

**Comment by peti** [comment]
I've tried several times to contact Malcom by e-mail and otherwise over the last couple of weeks and I think it's fair to say that his packages are now unmaintained. Neither polyparse, nor cpphs, nor HaXml has received any updates for months despite being known to be broken. :disappointed:

**Comment by ndmitchell** [comment]
@peti I got a response from him on whatsapp, he was going to try and take a look, but that was a few weeks ago. I assume the changes to polyparse and cpphs are minor? Can we get a hackage maintainer to grant someone temporary permission to just fix the minor stuff? Who can take the lead on it? I'd be keen to see @bergmark 's version uploaded.

**Comment by peti** [comment]
@ndmitchell, the easiest solution would be for Malcolm to give someone -- i.e. me (http://hackage.haskell.org/user/PeterSimons) -- maintainer access to his packages on Hackage. I'd take care of uploading the new version. If you can reach him via instant messaging, then maybe you could convince him to do that?

**Comment by ndmitchell** [comment]
@peti just ping'd via WhatsApp.

**Comment by kozross** [comment]
Any news on this? Is using @bergmark's version of ``polyparse`` the recommended option for those of us who want to use GHC 8.6?

**Comment by ndmitchell** [comment]
Malcolm is AWOL. We're following the Hackage Trustees policy at https://github.com/haskell-infra/hackage-trustees/issues/186

**Comment by ndmitchell** [comment]
My personal recommendation for now is use a binary from an older GHC, if you are only using HLint as a tool. There are binaries under the release tab of GitHub. Otherwise, the polyparse fork is probably the best option.

**Comment by kozross** [comment]
Now that we have [this NMU][1] of ``polyparse``, I can confirm that ``hlint-2.1.10`` builds with GHC 8.6.

[1]: http://hackage.haskell.org/package/polyparse-1.12.1

**Comment by ndmitchell** [comment]
Worked for me and all my CI's have gone green. It's back!

**Comment by peti** [comment]
I suppose this ticket can be closed now?
