### ISSUE TITLE
Windows release builds missing

### ISSUE THREAD

**Issue by dten** [ndmitchell/hlint#534]
Have they gone on purpose? the last two releases are missing windows versions
https://github.com/ndmitchell/hlint/releases

**Comment by ndmitchell** [comment]
My bad - the Linux/Mac releases are automated, but the Windows one I do myself, and I forgot. I went back and added them. Not sure what to do going forward, other than trying to remember.

**Comment by dten** [comment]
Can't it be automated on appveyor? What needs a human touch?

**Comment by ndmitchell** [comment]
I once tried automating it on AppVeyor, and quickly came to the conclusion that it was easier to do it by hand that to do it via hand. I should probably take another go at some point...
