### ISSUE TITLE
Incorrect "Use const" when using named field puns

### ISSUE THREAD

**Issue by alex-rozenshteyn-leapyear** [ndmitchell/hlint#536]
Related to #483:

```haskell
{-# LANGUAGE NamedFieldPuns #-}
data Foo = Foo {x :: Int, y :: Int}
foo = \x -> Foo{x, y=1}
```
```
Suggestion: Use const
Found:
  \ x -> Foo{x, y = 1}
Perhaps:
  const Foo{x, y = 1}
```

**Comment by ndmitchell** [comment]
Thanks for the report! A bug in an upstream dependency - I raised a PR at https://github.com/pepeiborra/haskell-src-exts-util/pull/11 (while it's an upstream dependency, it was my bug that got moved into a separate repo, so entirely my fault!)

**Comment by ndmitchell** [comment]
Interestingly a bug I just came across and fixed as part of a different ticket. I've checked your code and it works now.
