### ISSUE TITLE
cabal install hlint ghc 8.4.3 ExitFailure 1/ExitFailure 77

### ISSUE THREAD

**Issue by AmberElferink** [ndmitchell/hlint#538]
Hi,
The "cabal install hlint" seems to give an error. I am a computer science student learning functional programming. I do not know the basic structure of the haskell installation, so I have no clue how to fix this. This is the standard error, changing nothing after the haskell installation:
![image](https://user-images.githubusercontent.com/32518317/46544291-81672a80-c8c3-11e8-9c54-98c6ac6cdd46.png)
After searching around, I tried changing the config file:
This is the original: 
![image](https://user-images.githubusercontent.com/32518317/46544675-89739a00-c8c4-11e8-90c0-fa98de4e6778.png)
I tried a ';' instead of ',' for the multiple paths. This gives the following error when I run cabal install hlint:
![image](https://user-images.githubusercontent.com/32518317/46544473-faff1880-c8c3-11e8-97b8-208abe9681d6.png)

Does not seem to get any better, so I changed it back. Any clue how to fix this? My whole class has this, like 100 students. Would be a huge help if you could provide a fix, because we need it to improve our coding style.

**Comment by ndmitchell** [comment]
Installing using the Haskell Platform rarely works - it pins things to really old versions - it is discouraged. Given your use case, I wonder if the precompiled binary would be easier for you? See the GitHub releases tab.

**Comment by AmberElferink** [comment]
Thank you so much! I have found a solution. I am posting for other people who need a reference in the future. My goal was to get hlint for Visual Studio Code. I took the following steps to make that work:
![image](https://user-images.githubusercontent.com/32518317/46552039-b5e5e100-c8d9-11e8-98ec-efbc6cd3e9f7.png)

**Comment by ndmitchell** [comment]
I think given you are using Windows switching to `stack` might be easier - at the moment installing packages like `old-time` is very hard with Cabal since you have to configure your environment properly (I struggle doing that, and usually use stack to configure the environment for Cabal). Using the binary sidesteps all these issues, which is probably the right thing, especially for beginners on Windows.
