### ISSUE TITLE
force newline after `where`

### ISSUE THREAD

**Issue by marcosh** [ndmitchell/hlint#544]
I would like to add a new custom hint to enforce the presence of a newline after the `where` keyword. I have two issues with this.

If I try to add a dumb hint like

```
- error : {lhs: "where a", rhs: "where a", name: "my own error"}
```

I get an error like

```
hlint: user error (Failed to read YAML configuration file /home/marcosh/projects/aql/.hlint.yaml
  Aeson exception:
Error in $: Error when decoding YAML, Failed to parse Parse error: where, when parsing:
  where a
Along path: root 0 error lhs
When at: String
- error:
    lhs: where a
    name: my own error
    rhs: where a
)
```

Moreover, if I try with `do` instead of `where` for example, I see that the hint does not consider the presence or absence of a newline. Is there a way to make a hint aware of the presence/absence of the newline, or is it out of scope for `hlint`?

**Comment by ndmitchell** [comment]
For the lhs/rhs stuff they must both be expressions, and they are matched at the syntax tree, without reference to whitespace - so the route you've gone down definitely won't work. I guess I'd probably push people more towards stylish-haskell or one of the other whitespace-modifying Haskell tools. However, it's not totally infeasible as a default-off hint in HLint, only question is how popular would it be?

**Comment by ndmitchell** [comment]
Given the rise in auto-formatters like Ormulu, I'm quite happy to now say that HLint won't ever deal with spacing/formatting, and people should just run their code through a formatter, so closing this issue.

**Comment by tysonzero** [comment]
@ndmitchell

This seems like a reasonable decision. The one unfortunate aspect is that it doesn't seem like there are any formatters in the same rule-based style of hlint.

I'm a huge fan of that style as it makes it easier to get going by just auto-ignoring all rules that are currently being violated, and adding back just the desired ones.

Current formatting tools seem like they'd instead require a huge initial commit changing the styling of a ton of the codebase, perhaps in ways we don't agree with.

It also tends to make it easier to find new stylistic things to catch, that the original authors may not have cared about.

**Comment by ndmitchell** [comment]
@tysonzero Having used auto-formatters in the Rust world, the big initial change is a pain, but well worth it. I'm not sure I'd choose to use a rules based formatter having used the automatic ones (a handful of configuration options is useful), so maybe the market just isn't there?

**Comment by tysonzero** [comment]
That's a fair point. I just wish there was one that I agreed with the styling of. There's always some code that they make look pretty ugly, be it long types in records (servant generic stuff), or multiline associative operator chains or whatever it may be.

**Comment by ndmitchell** [comment]
@tysonzero if you have a set of examples that you think look awful, perhaps create a github repo with them formatted the way you want, then check in the formatted version by each of the tools, and use that to drive progress? Haskell is fairly late to the auto formatting game, so I think there's plenty of opportunity to improve things.

**Comment by tysonzero** [comment]
That's not a bad idea.

Some cases that might be a little more awkward to model are those where I don't necessarily have specific "wrong" code in mind that should be fixed to the desired code, but where I just want the desired code to at least be left alone. Many of those cases are technically possible with some formatters, but largely by disabling various formatting options that are pretty useful to have, to the point where not that much formatting ends up being done.
