### ISSUE TITLE
HLint is confused by DerivingVia

### ISSUE THREAD

**Issue by kozross** [ndmitchell/hlint#549]
Any use of the ``DerivingVia`` extension is reported as an error by HLint, even if the compiler would accept it. Passing ``-XDerivingVia`` doesn't help.

**Comment by ndmitchell** [comment]
Yep, will be an upstream bug in haskell-src-exts. Can you produce a small standalone file which does parse with GHC, but not with hlint? (I don't have a sufficiently recent ghc to try it myself)

**Comment by kozross** [comment]
[This example I filed with hindent will do I think][1]. I've also pinged [haskell-src-exts][2].

[1]: https://github.com/commercialhaskell/hindent/issues/523
[2]: https://github.com/haskell-suite/haskell-src-exts/issues/419

**Comment by ndmitchell** [comment]
Perfect! I'll leave this issue to watch that ticket then (not much I can do, but HLint will probably work automatically once it is there).

**Comment by kozross** [comment]
I can confirm that as of the most current HLint version (due to [this commit][1] to ``haskell-src-exts``), this is no longer a problem. Closing the issue.

[1]: https://github.com/haskell-suite/haskell-src-exts/commit/6ee0ccc74c2f09fac9ed7f46552d5dda5ace6f5d

**Comment by ndmitchell** [comment]
Awesome, thanks for double checking!
