### ISSUE TITLE
hlint cannot parse type synonym

### ISSUE THREAD

**Issue by augustss** [ndmitchell/hlint#551]
This fails:

  type AExprMatch = (?bindMap :: BindMap)

**Comment by ndmitchell** [comment]
Thanks, an issue with the upstream Haskell-src-exts - tracked at https://github.com/haskell-suite/haskell-src-exts/issues/317

**Comment by ndmitchell** [comment]
Confirmed works with HEAD that doesn't use HSE for parsing, so fixed in the next release.
