### ISSUE TITLE
hlint does not define a symbol when running CPP

### ISSUE THREAD

**Issue by augustss** [ndmitchell/hlint#553]
Most programs using CPP define a symbol so there can be program dependent expansions.  Hlint should define __HLINT__.

**Comment by ndmitchell** [comment]
Agreed, it should! `#define HLINT 1` by default seems reasonable.

**Comment by augustss** [comment]
I actually had two underscores on each side of the symbol, but they disappeared.

**Comment by ndmitchell** [comment]
Very sensible - added!
