### ISSUE TITLE
The verbose flag doesn't do much

### ISSUE THREAD

**Issue by augustss** [ndmitchell/hlint#554]
Using -v doesn't seem to make much difference.  I would have expected to at least see how cpphs is invoked.

**Comment by ndmitchell** [comment]
`cpphs` isn't shelled out to, so it's not such an obvious verbosity tracing point. That said, there are a lot of places that should have more verbosity, so I'll do that.

**Comment by ndmitchell** [comment]
It turned out I had a timing mechanism that gets called for pretty much exactly what you'd want verbosity, so I hooked it up to that.
