### ISSUE TITLE
Parse error on ! operator

### ISSUE THREAD

**Issue by gilgamec** [ndmitchell/hlint#557]
This one seems pretty rudimentary for getting a parse error from, but hlint does error on:
```
module MyModule where

import qualified Data.Map as M

newtype MyMap k a = MyMap (M.Map k a)

(!) :: Ord k => MyMap k a -> k -> a
(MyMap m) ! k = m M.! k
```

**Comment by ndmitchell** [comment]
The issue here is bang patterns, which is an extension HLint turns on by default. If you compile with `-XNoBangPatterns` then it should compile.

**Comment by gilgamec** [comment]
Thanks!  I wan't aware that there were commonly-used extensions that made previously legal syntax illegal.
