### ISSUE TITLE
Parse error when using (~)

### ISSUE THREAD

**Issue by yairchu** [ndmitchell/hlint#559]
This line:

https://github.com/lamdu/syntax-tree/blob/master/src/AST.hs#L31

Causes this error:

    src/AST.hs:31:49: Error: Parse error
    Found:
        monoChildren ::
            forall expr child n m.
      >     ( Children expr, ChildrenConstraint expr ((~) child)
            , Functor n, Functor m
            ) =>

When playing around with things looks like the trigger to the error is using `(~)`. It might be a `haskell-src-exts` issue, but I don't know so asking here first..

**Comment by ndmitchell** [comment]
Almost certainly an upstream haskell-src-exts error.  Would you like to raise a ticket for them?

**Comment by yairchu** [comment]
Opened ticket there - https://github.com/haskell-suite/haskell-src-exts/issues/421

**Comment by ndmitchell** [comment]
Confirmed works with HEAD that doesn't use HSE for parsing, so fixed in the next release.

**Comment by yairchu** [comment]
Fantastic, thanks!
