### ISSUE TITLE
Is it possible to install hlint via stack?

### ISSUE THREAD

**Issue by luochen1990** [ndmitchell/hlint#563]
I'm using stack and find it very convenient, so I no longer install standalone ghc now, is there any way to install hlint via stack?

I tried the following but not works:

> $ cabal install hlint
> cabal: The program 'ghc' version >=6.11 is required but it could not be found.
> 
> $ cd ~/.stack/global-project  
> $ stack exec -- cabal install hlint
> cabal: Use of GHC's environment variable GHC_PACKAGE_PATH is incompatible with
> Cabal. Use the flag --package-db to specify a package database (it can be used
> multiple times).

**Comment by ndmitchell** [comment]
`stack install hlint` would be the recommended way with `stack`.

**Comment by luochen1990** [comment]
use `stack install hlint` directly works, thanks
