### ISSUE TITLE
parse error on code that ghc accepts just fine

### ISSUE THREAD

**Issue by manpacket** [ndmitchell/hlint#570]
```hs
module Foo where

derp1 :: IO [[Int]]
derp1 = do
    return $ do
        let bar = id where
        return $ map bar []

derp2 :: [Int] -> [Int]
derp2 = map id
```

% hlint foo.hs                                                                                                                                        foo.hs:9:1: Error: Parse error
Found:
            return $ map bar []
    
  > derp2 :: [Int] -> [Int]
    derp2 = map id
  

1 hint

% hlint --version                                                                                                                                     
HLint v2.1.12, (C) Neil Mitchell 2006-2018

**Comment by ndmitchell** [comment]
Confirmed works with HEAD that doesn't use HSE for parsing, so fixed in the next release.
