### ISSUE TITLE
Parse error on TypeApplication with .hlint.yaml

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/hlint#572]
With `hlint 2.1.11`, `haskell-src-exts-1.20.3`, getting parse error on `hoistServerWithContext api (Proxy @a) convertApp` if LANGUAGE pragma is not inside the file. 
Tried putting `TypeApplications` explicitely in `.hlint.yaml` 
```
- extensions:
  - name: [ TypeApplications ]
```
but no change

_Originally posted by @vlatkoB in https://github.com/ndmitchell/hlint/issues/386#issuecomment-448682501_

**Comment by ndmitchell** [comment]
@vlatkoB - if you write `- arguments: [ "-XTypeApplications"]` does that work?

**Comment by vlatkoB** [comment]
No, same error. Tried with both (`arguments` and `extensions`) and with each one alone, but same error.

**Comment by ndmitchell** [comment]
What about `-XTypeApplications` as a flag on the command line?

**Comment by vlatkoB** [comment]
Reinstalled all with new lts and now it is working with `arguments` and `-XTypeApplications`. 
Thanks for the help. If you agree, this issue can be closed.
