### ISSUE TITLE
Parse error on importing `@:`

### ISSUE THREAD

**Issue by jml** [ndmitchell/hlint#573]
hlint seems to fail to parse the import of the `@:` operator from scalpel (see [docs](https://hackage.haskell.org/package/scalpel-0.5.1/docs/Text-HTML-Scalpel.html#v:-64-:))

```haskell
src/Sitesucker.hs:28:33: Error: Parse error
Found:
    import qualified Network.Wreq.Session as S
    import qualified Options.Applicative as Opt
  > import Text.HTML.Scalpel.Core ((@:), (//), hasClass)
    import qualified Text.HTML.Scalpel.Core as Scalpel
```

```console
$ hlint --version
HLint v2.1.6, (C) Neil Mitchell 2006-2018
```

I've tried running `hlint` with a bunch of different extensions, including all the ones in my cabal file, but no joy.

**Comment by theGhostJW** [comment]
Hi 
As a FYI I have a similar problem with an @ symbol in a code block. I assume it is the same issue:


## Source Code

```haskell
module MemberReflection where

import Foundation
import Control.Monad.Freer
import Type.Reflection
import Control.Monad

newtype WithEffects_ es0 es1 a = WithEffects { unWithEffects :: Members es0 es1 => a }

class ShowTypes (es :: [* -> *]) where
  showTypes :: [String]

instance ShowTypes '[] where
  showTypes = []

instance (Typeable e, ShowTypes es) => ShowTypes (e ': es) where
   showTypes = show (typeRep @e) : showTypes @es

showEffs2 :: forall es0 es1 a. ShowTypes es0 => WithEffects_ es0 es1 a -> [String]
showEffs2 _ = showTypes @es0

```

## Error 
```
Hlint Error: Parse error
showEffs2 :: forall (es0 :: [* -> *]) (es1 :: [* -> *]) a.
ShowTypes es0 =>
WithEffects_ es0 es1 a -> [String]
```

## Version
```
HLint v2.1.5, (C) Neil Mitchell 2006-2018
```

**Comment by ndmitchell** [comment]
Actually @theGhostJW I think your issue can be solved by putting `{-# LANGUAGE TypeApplications #-}` at the top of the file, or passing `-XTypeApplications` to HLint, or putting it in the .hlint.yaml file.

**Comment by theGhostJW** [comment]
Thanks @ndmitchell,

Putting `{-# LANGUAGE TypeApplications #-}` at the top of the file as you suggested solved the problem.

I actually have this option in defaultExtensions in my my `package.yaml` which then generates an entry in the `default-extensions` in the cabal file. 

I notice adding the entry to default extensions is not one of the options you mentioned for solving this problem so is this expected behavior, a bug or a potential feature request?

**Comment by ndmitchell** [comment]
HLint currently doesn't look at `.cabal` or `package.yaml` files. It's something it could do, and I think there even is a feature request for it, but it doesn't yet.

**Comment by ndmitchell** [comment]
Confirmed works with HEAD that doesn't use HSE for parsing, so fixed in the next release.
