### ISSUE TITLE
Suggest NumericUnderscores

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/hlint#578]
As per https://github.com/haskell/haskell-ide-engine/issues/1029 by @alanz - requires #577 to be implemented first (or to remain on the pile for about 3 years first)

**Comment by ndmitchell** [comment]
True, happy to support that already.

**Comment by dustin** [comment]
I argue that this should only be used for longer numbers.  I see this was also mentioned in https://github.com/haskell/haskell-ide-engine/issues/1029

Having applied this to a codebase with a lot of dates, it's suggested underscores in all of the years in our codebase and satisfying the hint was quite invasive.

Would it be possible to limit this to a minimum number of digits?  Years (below 10,000) never use a thousands separator and style guides often suggest that (at least in American styles), comma separators aren't used for four-digit numbers.

**Comment by ndmitchell** [comment]
@dustin - that seems very sensible - making 2023 turn in to 2_023 seems horrible. Are you interested in writing a patch?

**Comment by dustin** [comment]
@ndmitchell do you have any reservations for my PR?

**Comment by ndmitchell** [comment]
Sorry @dustin, was between computers, this looks great and is all now merged. Would a release be useful? Or shall I just roll it into the next one?

**Comment by dustin** [comment]
Thanks so much.  It sounds like we are fine without a release, so nothing urgent here.
