### ISSUE TITLE
Feature request: Support `ExplicitNamespaces` extension

### ISSUE THREAD

**Issue by unclechu** [ndmitchell/hlint#584]
`hlint` always fails on parsing for every explicit `type` in explicit imports, an example:
```
λ hlint src/Process/Keyboard.hs
src/Process/Keyboard.hs:12:35: Error: Parse error
Found:
    import "base" System.IO (IOMode (WriteMode), withFile)
  > import "base" GHC.IO.Handle (type Handle)
    import qualified "process" System.Process as P
    import qualified "linux-evdev" System.Linux.Input.Event as EvdevEvent


1 hint
```

**Comment by ndmitchell** [comment]
This is a feature not supported in haskell-src-exts. I might have a short term plan to get around this though, will have a think.

**Comment by ndmitchell** [comment]
Confirmed works with HEAD that doesn't use HSE for parsing, so fixed in the next release.
