### ISSUE TITLE
having a parameter called `via` results in parse error

### ISSUE THREAD

**Issue by dten** [ndmitchell/hlint#586]
the following file

```
module Nothing where

nothing via = undefined
```

results in 
```
File.hs:3:9: Error: Parse error
Found:
    module Nothing where

  > nothing via = undefined

1 hint
```

but it should not mind

**Comment by sol** [comment]
@ndmitchell I think it could be neat if you could tell `hlint` to only use the language extensions that you specified explicitly.  Or is this already possible by any chance?

**Comment by ndmitchell** [comment]
@sol put -XHaskell98 or -XHaskell2010 on the command line and that turns off all extensions not specified in that standard. Then you can turn on additional extensions explicitly.

**Comment by ndmitchell** [comment]
Confirmed works with HEAD that doesn't use HSE for parsing, so fixed in the next release.
