### ISSUE TITLE
JSON output of `Use fewer imports`

### ISSUE THREAD

**Issue by rikvdkleij** [ndmitchell/hlint#589]
When I have redundant imports like for example here on line 6 and 7:
```
...
import qualified Data.Vector as DV
import qualified Data.Vector as DV(fromList)
...
```

HLint JSON gives:
```
[
  {
    "module": [
      "Debug"
    ],
    "decl": [],
    "severity": "Warning",
    "hint": "Use fewer imports",
    "file": "/home/rik/projects/quicksort/src/Debug.hs",
    "startLine": 6,
    "startColumn": 1,
    "endLine": 6,
    "endColumn": 35,
    "from": "import qualified Data.Vector as DV\nimport qualified Data.Vector as DV (fromList)\n",
    "to": "import qualified Data.Vector as DV\n",
    "note": [],
    "refactorings": "[Delete {rtype = Import, pos = SrcSpan {startLine = 7, startCol = 1, endLine = 7, endCol = 45}}]"
  }
]
```

But I would expect:
```
[
  {
    "module": [
      "Debug"
    ],
    "decl": [],
    "severity": "Warning",
    "hint": "Use fewer imports",
    "file": "/home/rik/projects/quicksort/src/Debug.hs",
    "startLine": 6,
    "startColumn": 1,
    "endLine": 7,
    "endColumn": 45,
    "from": "import qualified Data.Vector as DV\nimport qualified Data.Vector as DV (fromList)\n",
    "to": "import qualified Data.Vector as DV\n",
    "note": [],
    "refactorings": "[Delete {rtype = Import, pos = SrcSpan {startLine = 7, startCol = 1, endLine = 7, endCol = 45}}]"
  }
]
```

Notice `endLine` and `endColumn`.
The `refactorings` field contains the right instructions.

Is this behavior intended?.

**Comment by rikvdkleij** [comment]
Forgot to mention the HLint version: v2.1.10,

**Comment by ndmitchell** [comment]
That's intentional - I only point at the first line. The reason is that the second line might not be adjacent to the first line, so highlighting all the lines in between would seem odd. I guess you are asking in the context of an IDE? Perhaps if they imports are adjacent I should have a special case and highlight both lines? What should I do if they aren't adjacent?

**Comment by rikvdkleij** [comment]
Yes, I'm asking this in the context of the IDE.

As for all HLint suggestions, the line numbers are used to find the code in which the `from` has to be replaced by `to`.

Ok, I see your point. Maybe better solution is that IDE uses the `refactorings` field (for all HLint suggestions) but I do not know what to expect there besides in this example a `Delete` instruction. 

This issue is also solved if I know how to parse the `refactorings` field in general. Some work for me, but okay 😄 

> Perhaps if they imports are adjacent I should have a special case and highlight both lines? What should I do if they aren't adjacent?

I did not know that the line numbers are mentioned for highlighting and are independent from the `from` and `to` fields. Btw, in this example it would be more appropriate to only highlight the second line, line 7 because that one is redundant.

**Comment by rikvdkleij** [comment]
> Perhaps if they imports are adjacent I should have a special case and highlight both lines? What should I do if they aren't adjacent?

On a second thought. Maybe only highlight the file which is redundant. And mention in the `note` the other import.  Or use a second pair of line start/ends which indicates the other line.

Can you give me a pointer to the description of the `refactorings` field?

**Comment by ndmitchell** [comment]
The refactorings are described at https://hackage.haskell.org/package/refact-0.3.0.2/docs/Refact-Types.html

In general HLint doesn't know which one is redundant, merely that together they are redundant.

**Comment by rikvdkleij** [comment]
Thanks!
