### ISSUE TITLE
Invalid Byte Sequence When Reading from Standard Input

### ISSUE THREAD

**Issue by Krantz-XRF** [ndmitchell/hlint#591]
My source file contains Unicode characters, and I get an error message `hlint.EXE: <stdin>: hGetContents: invalid argument (invalid byte sequence)`. 

My file is correctly saved in UTF-8 encoding. This only happens when I pass the file contents from the standard input, i.e. using `hlint - < file.hs`. When I use `hlint file.hs`, I get no error message. 

However, when I save the file in native locale encoding (on my system is GBK), Things got flipped, it works when I use the standard input but not when I directly use that file. 

I guess this has something to do with the operating system, for I only get this error on Windows, but things work well on Linux (Fedora 29).

**Comment by ndmitchell** [comment]
Thanks, I was reading stdin without setting an encoding. I now set it to UTF8 when assuming it has a Haskell file, so that should fix it. Any chance you can test from Git? I tried reproducing, but it didn't error on my machine. It's probably due to locale settings, so it probably can fail on all OS's, but Windows is more likely configured to fail.

**Comment by Krantz-XRF** [comment]
I would love to test from git, but I use `stack`, and I have just found out that HLint requires `haskell-src-exts >= 1.21 && < 1.22`, and that version is only provided in the nightly resolver of `stack`. 

Is it safe to modify the `cabal` file to use an older version of these packages?

**Comment by ndmitchell** [comment]
That sounds like more effort than is necessary. I'm fairly sure the changes will fix it, so when I next release, and you next upgrade, please reopen the ticket if you still have problems. Thanks for the report!

**Comment by Krantz-XRF** [comment]
I have manually downloaded source code `HLint-2.1.11` and applied your change to the corresponding files. It seems that the patch does fix the problem. Thanks for your timely response!
