### ISSUE TITLE
Feature request: Re-export all used definitions

### ISSUE THREAD

**Issue by pjljvandelaar** [ndmitchell/hlint#596]
When working in a large project, I don't want to duplicate the dependencies of files/packages I use.

For example, assume a package defines X.
Another package defines a Producer and Consumer of X (and thus depends on the package defining X).
A third package, which wants to use the Producer and Consumer in a decoupled way needs to store the results in buffer of type X.
When the package of the Producer and Consumer does NOT re-export X, the third package must also depends on the package defining X. I consider this dependency unwanted: you must be able to use an interface as is, i.e., in a context where Producer is defined also X must be defined.

However, I was unable to find any tool, including hlint, that performs such a check!

So my question: can HLint check that all necessary definitions are include in the export of a file / package?

**Comment by ndmitchell** [comment]
No, HLint can't, and it doesn't have nearly enough information about what comes from where to figure that out.

**Comment by pjljvandelaar** [comment]
That is unfortunately...
It would really be a feature I would love!

**Comment by ndmitchell** [comment]
There's a chance it could be in Weeder, since it is closer to having the info you need, but you probably need  to investigate.

**Comment by pjljvandelaar** [comment]
Thanks for the suggestion: https://github.com/ndmitchell/weeder/issues/48
