### ISSUE TITLE
Detect that `KindSignatures` isn't used (syntactically)

### ISSUE THREAD

**Issue by yairchu** [ndmitchell/hlint#598]
When TH isn't enabled, hlint could detect whether kind signatures are used or not and warn about the unused extension.

**Comment by ndmitchell** [comment]
Yep, seems a good idea. PR welcome :)

**Comment by yairchu** [comment]
It looks like [the code for this is already there](https://github.com/ndmitchell/hlint/commit/9be66db38a41544730c1486f39be8b2c1336bde1#diff-d7f6b0f2f43a8f41a46ceb349442b621R38), but I'm pretty sure I also had a specific situation where it didn't detect it not being needed, but sadly I didn't put a code example in this report. I guess if I stumble on such a situation again and have a failing case I'll re-open the issue..
