### ISSUE TITLE
Detect old-style uninhabited type definitions

### ISSUE THREAD

**Issue by taktoa** [ndmitchell/hlint#599]
In much older versions of GHC, before `-XEmptyDataDecls`, the accepted way to define a type with no inhabitants looked like:
```haskell
newtype Void = Void Void
```
Now, with `-XEmptyDataDecls`, we can write this as the much simpler
```haskell
data Void
```
I think this is a reasonable hint to add to HLint; I just came across the old-style definition in some code that definitely wasn't aiming to support GHC 6.

**Comment by ndmitchell** [comment]
While HLint could detect this, it would have to be a specially coded Haskell rule, and my guess is that the number of instances of this in still useful code is incredibly small. Or do you think it's more common?

**Comment by taktoa** [comment]
It's probably pretty rare. If the cost-benefit doesn't make sense, feel free to close this.
