### ISSUE TITLE
Infix precedence not respected

### ISSUE THREAD

**Issue by brandon-leapyear** [ndmitchell/hlint#617]
We added a custom hlint rule
```
error:
  lhs: \a b -> g (h a b)
  rhs: g .: h
```
using our `infixr 9 .:` function. Hlint suggested the following replacement
```haskell
\x t -> (:&) <$> x <*>+ t
-- to:
(<$>) (:&) .: (<*>+)
```
Which, in addition to being messier, is wrong. Our custom operation `<*>+` has the precedence `infixl 4 <*>+` (the same as `<$>`), so the original expression is equivalent to
```haskell
\x t -> ((:&) <$> x) <*>+ t
```
whereas the second one is equivalent to
```haskell
\x t -> (:&) <$> (x <*>+ t)
```
The original expression is being falsely matched with the hlint rule because hlint seemed to match `g = ((:&) <$>)` and `h = (x <*>+ t)` which doesn't follow the infix precedence set.

**Comment by ndmitchell** [comment]
In general HLint has little idea of the precedences of operators - if they aren't defined in the same file, or one of the standard ones in the Prelude, it just guesses. Normally those guesses are good enough for HLint purposes, but sometimes they go astray. See https://github.com/ndmitchell/hlint#why-doesnt-hlint-know-the-fixity-for-my-custom--operator. (I've improved the docs slightly to make it a bit clearer)

**Comment by brandon-leapyear** [comment]
ah I have read that in the README before, but I didn't connect the dots. Thanks!
