### ISSUE TITLE
Move guards forward confused by RecodWildCards

### ISSUE THREAD

**Issue by phadej** [ndmitchell/hlint#619]
HLint suggests to move guards forward, which doesn't work.

`HLint v2.1.15, (C) Neil Mitchell 2006-2019`

```
src/HaskellCI/Travis.hs:452:9: Suggestion: Move guards forward
Found:
  [pkgJobs | Pkg{pkgGpd, pkgJobs} <- pkgs,
   not $ null $ C.condTestSuites pkgGpd]
Perhaps:
  [pkgJobs | not $ null $ C.condTestSuites pkgGpd,
   Pkg{pkgGpd, pkgJobs} <- pkgs]
```

**Comment by ndmitchell** [comment]
Thanks for the report. An issue with one of the libraries I use - PR submitted upstream: https://github.com/pepeiborra/haskell-src-exts-util/pull/12. Hopefully I can get a release soon and then pin that as a minimum version.

**Comment by ndmitchell** [comment]
Fixed upstream, new release, and I'm constraining to the higher version with bounds.
