### ISSUE TITLE
Parse error for cost center annotations

### ISSUE THREAD

**Issue by mbeidler** [ndmitchell/hlint#621]
With the SCC annotation present, the following code gives a parse error.
```haskell
foo :: IO ()
foo = print "foo"
{-# SCC foo #-}
```

It seems like hlint should ignore pragmas it doesn't understand.

**Comment by ndmitchell** [comment]
See https://github.com/haskell-suite/haskell-src-exts/issues/392 - it's an upstream bug in haskell-src-exts. If you put quotes around the `foo` in the `SCC` it should work.

**Comment by mbeidler** [comment]
Interestingly, I had tried adding the quotes and that didn't fix it, but it's clear the issue isn't with hlint so I'll follow up there. Thanks!

**Comment by ndmitchell** [comment]
Confirmed works with HEAD that doesn't use HSE for parsing, so fixed in the next release.

**Comment by mbeidler** [comment]
@ndmitchell I see you've moved to the GHC parser. Sweet! Thanks!
