### ISSUE TITLE
More aggressive "avoid lambda" rules.

### ISSUE THREAD

**Issue by yairchu** [ndmitchell/hlint#624]
Currently the `\x -> x + a ==> (+ a)` rule has the limitation of "heuristic, a must be a single lexeme, or gets too complex".

It would be nice if that limitation could be turned off to get more such suggestions.

**Comment by ndmitchell** [comment]
I'd prefer to go the route of #623 if that's fine by you.

**Comment by yairchu** [comment]
LGTM :)
