### ISSUE TITLE
PVP: 2.1.18 should not have been a point release, for the API

### ISSUE THREAD

**Issue by alanz** [ndmitchell/hlint#636]
There are a number of changes to the API, including the return type from `parseModuleEx` and the `ParseError` data type.

**Comment by ndmitchell** [comment]
Yes, I think that was a mistake I noticed an hour or so ago. I am just about to try and put out a 2.1.19 which puts them back to how they were.

**Comment by ndmitchell** [comment]
BTW, apologies!

**Comment by alanz** [comment]
Thanks, I will wait for that then, for haskell-ide-engine update.

**Comment by ndmitchell** [comment]
2.1.19 now out with an identical API - let me know if it causes any problems. I have marked 2.1.18 as deprecated on Hackage. Apologies for the trouble - I owe you a beer!
