### ISSUE TITLE
Version 2.1.20 API change on parse fail

### ISSUE THREAD

**Issue by alanz** [ndmitchell/hlint#637]
We have a test in haskell-ide-engine where we invoke hlint via the API on a GHC file that does not parse at all.

For version 2.1.17 and before, this returns errors which we can turn into diagnostics.  For version 2.1.20 we get an error exit, with code -11.

The test is at https://github.com/haskell/haskell-ide-engine/blob/master/test/unit/ApplyRefactPluginSpec.hs#L92, and the (incomplete) file being parsed in this instance is

```haskell
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE GADTs                  #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE TypeInType #-}
module Test where

import           Data.Singletons.Prelude
import           Data.Singletons.TypeLits
import           Data.Type.Equality            ((:~:) (..), (:~~:) (..))

data instance Sing (z :: (a :~: b)) where
    SRefl :: Sing Refl +
```

**Comment by shayne-fletcher-da** [comment]
Hmmm. Oddly, I can't reproduce this with the 2.1.20 executable.
```
Building executable 'hlint' for hlint-2.1.20..
Running hlint...
/Users/shaynefletcher/HLintParseFail.hs:14:1: Error: Parse error
Found:
    data instance Sing (z :: (a :~: b)) where
        SRefl :: Sing Refl +
  > 
  

1 hint
```
Anything more you can tell me that might help us diagnose what's up here?

**Comment by alanz** [comment]
This is using API calls only, simplest is to take haskell-ide-engine master
and bump hlint in a stack file. The test that fails is in

stack test haskell-ide-engine:unit-test

**Comment by shayne-fletcher-da** [comment]
Have reproduced the problem using the hie repo and unit-test. Very mysterious. Unable to reproduce so far except in-situ. Even exercising the hlint api from a stand-alone app on the same input doesn't exhibit the abnormal termination.

**Comment by shayne-fletcher-da** [comment]
The story is that in (`ApplyRefact.hs`),
```
runLintCmd :: FilePath -> [String] -> ExceptT [Diagnostic] IO [Idea]
runLintCmd fp args = do
  (flags,classify,hint) <- liftIO $ argsSettings args
  let myflags = flags { hseFlags = (hseFlags flags) { extensions = EnableExtension TypeApplications:extensions (hseFlags flags)}}
  res <- bimapExceptT parseErrorToDiagnostic id $ ExceptT $ parseModuleEx myflags fp Nothing
  pure $ applyHints classify hint [res]
```
if `fp` generates a syntax error, `parseModuleEx` abnormally terminates. As earlier mentioned, haven't been able to reproduce this behavior yet with either the `hlint` exe or a stand-alone program that calls `parseModuleEx`. Super mysterious.

**Comment by alanz** [comment]
Do we know what kicks off the exit type of (-11)?

And could it be related to us having a handler further up in the chain, that might be catching the lower level exception? I am not 100% sure how exception handlers work in that scenario.  Given hlint is now using the GHC API for parsing, it might be a GHC error being thrown, that needs to be explicitly managed as such.

**Comment by shayne-fletcher-da** [comment]
> Do we know what kicks off the exit type of (-11)?

In the event of a syntax error in the input, the expression `  Lexer.unP Parser.parseModule parseState
` in `parseFileGhcLib`  in the file `hlint/src/GHC/Util.hs` terminates abnormally instead of returning a `PFailed _`.

> And could it be related to us having a handler further up in the chain, that might be catching the lower level exception? I am not 100% sure how exception handlers work in that scenario. Given hlint is now using the GHC API for parsing, it might be a GHC error being thrown, that needs to be explicitly managed as such.

We put a `catch` around that bit but obviously to no avail. I don't at this time no of any way to influence the lexer/parser to throw exceptions, I've never seen it before now and we don't expect it to do that either. Yes, there's something about specific to this environment. The mention of exception handlers "higher up" may be a clue.

**Comment by shayne-fletcher-da** [comment]
I have no idea what exit code -11 corresponds to but expect it to be a segfault or bus error.

**Comment by alanz** [comment]
Another thought. In the hlint tests, you only use ghc-lib-parser.

In hie we use it and the normal GHC API. Could there be some kind of clash?

**Comment by ndmitchell** [comment]
Yes, a clash is possible. But I've no idea how it could arise, and it seems like a violation of something fairly fundamental. It's going to be difficult to track down I suspect.

**Comment by ndmitchell** [comment]
I've released 2.1.21 which disables the GHC parser while we investigate.

**Comment by alanz** [comment]
FYI I tried this in hie, and it now disappears into a call to `applyRefactorings`, 

```haskell
    liftIO $ logm $ "applyHint:apply=" ++ show commands
    res <- liftIO $ (Right <$> applyRefactorings Nothing commands fp) `catches`
              [ Handler $ \e -> return (Left (show (e :: IOException)))
              , Handler $ \e -> return (Left (show (e :: ErrorCall)))
              , Handler $ \e -> return (Left (show (e :: SomeException))) -- AZ:temporary
              ]
    liftIO $ logm $ "applyHint:res=" ++ show res
```

The first `logm` puts stuff in the log, but the second one does not, and we eventually time out.

Using [this branch](https://github.com/alanz/haskell-ide-engine/tree/hlint-2.1.19)

**Comment by alanz** [comment]
The relevant code is at https://github.com/alanz/haskell-ide-engine/blob/hlint-2.1.19/src/Haskell/Ide/Engine/Plugin/ApplyRefact.hs#L237-L270

**Comment by ndmitchell** [comment]
All fixed and made a release. Please shout if it causes issues!
