### ISSUE TITLE
More warnings on trivial length comparisons?

### ISSUE THREAD

**Issue by jvoigtlaender** [ndmitchell/hlint#642]
There currently appear to be warnings on all the following cases:
* `length x == 0`
* `length x /= 0`
* `length x >= 0`
* `length x > 0`
* `length x >= 1`

... suggesting calls of `null`, `not . null`, or simply `True` accordingly.

But we find our students also writing expressions like:
* `length x < 1`
* `length x <= 0`

for which currently no warnings are given.

Open for a pull request adding such warnings? Or not considered desirable?

**Comment by ndmitchell** [comment]
PR most welcome! Anything people do in practice is worth including.

**Comment by jvoigtlaender** [comment]
Just to be on the safe side: A PR would have to add relevant lines to https://github.com/ndmitchell/hlint/blob/master/data/hlint.yaml, right?

**Comment by ndmitchell** [comment]
Yep, you seem to have figured it out :)
