### ISSUE TITLE
Move to ghc-lib-parser

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/hlint#645]
Given that haskell-src-exts is changing maintainer again https://www.reddit.com/r/haskell/comments/bswd7m/haskellcafe_haskellsrcexts_no_more_releases/ the plan is to get away from it and move to ghc-lib-parser. This ticket tracks the effort.

The rough game plan is:

- [x] Add ghc-lib-parser as a dependency
- [x] Parse all files with ghc-lib-parser
- [x] Make it a parse error if you can't parse with ghc-lib-parser
- [x] Rewrite the public API to make it not reference HSE values
- [x] Convert hints one by one to ghc-lib-parser
- [ ] Stop parsing with HSE

The intent is to do this a combination of me and @shayne-fletcher-da.

**Comment by ndmitchell** [comment]
Thanks for the offer @googleson78. The patch to make it an error should be landing today. The change in the API is the big thing which is probably going to take a fair bit of effort and is hard to do, since it requires looking at and talking to all users. Once we get past that step the job of converting individual tests from HSE to GHC should be highly parallelisable, so any help at that stage would be most welcome! I'll comment on the ticket when we get there.

**Comment by ndmitchell** [comment]
@googleson78 we're now in the converting hints one by one. @shayne-fletcher-da is working on it, but it parallelises well, so if you want to take a crack at some hints, go for it. The first one has been done, https://github.com/ndmitchell/hlint/pull/693.

**Comment by googleson78** [comment]
I'll try doing `NewType.hs`.

**Comment by googleson78** [comment]
I have a question though:
I see that stuff is getting renamed from `X` to `XEx` (`Module` -> `ModuleEx`). Should I also make a `DeclEx` which holds both a `Decl_` and a `HsDecl`?

**Comment by ndmitchell** [comment]
0. There's no guarantee that HSE and GHC consider programs to have the same number of Decl's so you can't do that. We probably need DeclOld and DeclNew as two separate hints, and slowly migrate from old to new. (Might make sense to leave the old one as is, introduce a new one, and flip names at the end)

1. Not sure what you mean? Aim is to delete all HSE - current approach is to try and do it incrementally without a Big Bang.

**Comment by googleson78** [comment]
WIP on `NewType.hs`:
https://github.com/ndmitchell/hlint/pull/696

**Comment by googleson78** [comment]
I'd also take a look at `Naming.hs`, but I don't know if I'll have too much time before the coming weekend, if someone else wants to do it before then..

**Comment by googleson78** [comment]
Question:

Why does `NewType.hs` give a hint for a single declaration, whereas `Naming.hs` gives hints for an entire module (as far as I can tell)?

**Comment by googleson78** [comment]
Question2:

Do you want to have `Named` instances for `ghc-lib-parser` stuff, like it is currently with `HSE`?

**Comment by ndmitchell** [comment]
Naming tries to avoid suggesting names that are already used so it has to work at the whole module level.

Where you use the Named type class or not is your choice. It turned out to be useful for HSE, but if GHC works better another way I'm happy. Although I would default to doing the same again since that's probably easiest since we know it works.

**Comment by googleson78** [comment]
Here's a WIP - #708

**Comment by shayne-fletcher-da** [comment]
@googleson78 @ndmitchell comments done, heads-up : taking on imports next.

**Comment by googleson78** [comment]
I'll try taking a look at (the slightly daunting) `Hint.Lambda`.

**Comment by shayne-fletcher-da** [comment]
Thanks for the heads up!

**Comment by shayne-fletcher-da** [comment]
I plan on starting on `List.hs` next week. When that's done, I think we'll be left with Patterns, Monads, Extensions and Match.

**Comment by googleson78** [comment]
This is slightly unrelated, but why is the lambda not removed in these case:

```haskell
f (test -> a) = \x -> x + x
```
The commit says `Don't suggest removing lambda if it causes view patterns to be recomputed more`, but why is
```haskell
f (test -> a) x = x + x
```
doing more computation than the first example?

**Comment by ndmitchell** [comment]
@googleson78 `map (f x) xs` causes `test x` to be computed once in the first case, and `length xs` times in the second case.

**Comment by shayne-fletcher-da** [comment]
With lambdas in-flight, we have patterns, monads, extensions and matches to go. 'Pattern.hs' is on my radar for next week:
- Redundant guard;
- Redundant `where`;
- Use `otherwise`;
- Use record patterns;
- Redundant bang pattern;
- Used `otherwise` as a pattern;
- Redundant irrefutable pattern;
- Redundant `as` pattern;
- Redundant case.

**Comment by shayne-fletcher-da** [comment]
Patterns are up for review, moving next to monads.
- Redundant `do`;
- Redundant `void`;
- Use `let`;
- Use `join`;
- Redundant variable capture;
- Redundant `return` ...;
- Use `<$>`.

**Comment by shayne-fletcher-da** [comment]
Monads are up for review. Taking a couple of weeks off. On return intend to pick up extensions and match.

**Comment by shayne-fletcher-da** [comment]
Match is in-flight.

**Comment by shayne-fletcher-da** [comment]
Match has landed. If I'm not mistaken, this leaves just lambdas and extensions to go before we can mark the "Convert hints one by one to ghc-lib-parser" task done.

**Comment by shayne-fletcher-da** [comment]
Extensions have landed. I believe only lambdas remain before the sub-task "Parse all files with ghc-lib-parser" can be marked complete.

**Comment by googleson78** [comment]
(related to [this](https://github.com/ndmitchell/hlint/pull/889#issuecomment-592928091))

Since `ghc` has some notion of "fake" src spans, whereas `hse` didn't (?), there needs to be some handling of this case.

How about making `toSS'` (and co.) return `Maybe`s and handling this when creating refactoring suggestions?

I would imagine that the source code `hlint` (`GhcPs`) wants to process will never contain fake src spans (as it is not intended to process generated code (?), afaik), so it would be awesome if `ghc` could start guaranteeing to output `RealSrcSpan`s from the parsing phase

**Comment by ndmitchell** [comment]
The Maybe can indeed occur. HLint is an API, and users who have preprocessors (e.g. record-dot-preprocessor) are likely to submit code to HLint which has some fake src spans.

**Comment by ndmitchell** [comment]
We're done with phase 1! All the hints work off ghc-lib. That's the hard bit. Closing this issue and using #892 for the rest, which is about cleaning up the things around the sides.
