### ISSUE TITLE
Parse error on variable name 'pattern'

### ISSUE THREAD

**Issue by andrewruxton** [ndmitchell/hlint#655]
hlint (v2.1.11) throws the following error on a line containing the variable name 'pattern':

```
Error: Parse error
Found:
    interpolateVersion :: Version -> String -> String
  > interpolateVersion Version {..} pattern =
        T.unpack $
        sub "minor" (show minor) . sub "major" (show major) . sub "patch" (show patch) . sub "hash" hash $ T.pack pattern
```

changing the variable name avoids this error

**Comment by ndmitchell** [comment]
I believe this is covered by https://github.com/ndmitchell/hlint/issues/216 - basic answer for now is pass `-XNoPatternSynonyms`, but we're working on a way to avoid the problem properly.
