### ISSUE TITLE
Don't apply the refactoring tool when there are no hints

### ISSUE THREAD

**Issue by sjakobi** [ndmitchell/hlint#661]
I noticed that automatic refactorings with `refactor` would even change files for which `hlint` reported no hints.

This can be observed for example with trailing whitespace which `refactor` will remove.

I think that mostly for performance reasons it would be better if the application of the refactoring tool would be skipped entirely in such cases.

**Comment by ndmitchell** [comment]
This bug report probably belongs with the refactor tool at https://github.com/mpickering/apply-refact

**Comment by sjakobi** [comment]
I'd prefer if the refactoring would be skipped for any refactoring tool. So I think it would be nice if `hlint`'s behavior could be changed here.

I'll try to make a PR if you agree.

**Comment by ndmitchell** [comment]
My worry is that if people abuse the refactoring tool for other reasons, e.g. reports, context sensitive markup etc then it won't work if we skip empty files. That said, I don't think anyone has actually done that, so I'm on the fence.

**Comment by mitchellwrosen** [comment]
I think this was resolved by #685

**Comment by sjakobi** [comment]
Thanks @mitchellwrosen! :+1:
