### ISSUE TITLE
lpaste.net is hard to access

### ISSUE THREAD

**Issue by sjakobi** [ndmitchell/hlint#663]
The first paragraph of the readme suggests trying hlint on http://lpaste.net. lpaste.net looks kind of hard to access currently:

![image](https://user-images.githubusercontent.com/3664523/59117477-24d67680-894e-11e9-856b-c90a692faa35.png)

Maybe the suggestion should be less prominent.

**Comment by ndmitchell** [comment]
Thanks, agreed - I've now just moved it into the pile of other integrations, taking it on faith that behind that login there is probably still the old lpaste...
