### ISSUE TITLE
Is introducing uncurry really "evaluation"?

### ISSUE THREAD

**Issue by jvoigtlaender** [ndmitchell/hlint#664]
It puzzles me that this hint:
https://github.com/ndmitchell/hlint/blob/a3fb0b5f529c2e0774cd18131a9a433551676490/data/hlint.yaml#L601

says that what to do there is "Evaluate".

I wouldn't say that replacing `f (fst p) (snd p)` by `uncurry f p` is evaluation, i.e., that the `uncurry` call is more evaluated than the `fst`/`snd` calls. Not in the way as is the case with all other hints in the "Evaluate" category, like `fst (x,y) ==> x` etc.

**Comment by ndmitchell** [comment]
Entirely agreed. I moved it and called it Use uncurry, which is much more reasonable. Thanks!
