### ISSUE TITLE
Suggest sortWith instead of sortOn

### ISSUE THREAD

**Issue by sjakobi** [ndmitchell/hlint#669]
Given

```
x = reverse (sort xs)
```

hlint currently recommends

```
≻ hlint sort.hs 
sort.hs:1:5: Warning: Avoid reverse
Found:
  reverse (sort xs)
Perhaps:
  sortOn Data.Ord.Down xs
```

The problem is that `sortOn` caches the comparison function, which in the case of `Down` or any other newtype or many other cheap functions makes performance worse. Roman Cheplyaka has written [a nice article](https://ro-che.info/articles/2016-04-02-descending-sort-haskell) including benchmarks about this.

```
sortOn :: Ord b => (a -> b) -> [a] -> [a]
sortOn f =
  map snd . sortBy (comparing fst) . map (\x -> let y = f x in y `seq` (y, x))
```

A better suggestion would be to use `GHC.Exts.sortWith` which doesn't do these extra allocations.

```
sortWith :: Ord b => (a -> b) -> [a] -> [a]
sortWith f = sortBy (\x y -> compare (f x) (f y))
```

The other suggestions for `sortOn` are slightly less clear-cut:

```
    - warn: {lhs: sortBy (comparing (flip f)), rhs: sortOn (Down . f)}
    - warn: {lhs: sortBy (comparing f), rhs: sortOn f}
    - warn: {lhs: reverse (sortOn f x), rhs: sortOn (Data.Ord.Down . f) x, name: Avoid reverse}
```

Here it depends on the cost of `f` whether `sortOn` or `sortWith` would be better. But `sortWith` will have the same performance characteristics as `sortBy`.

**Comment by sjakobi** [comment]
In fact, there should probably be warnings for `sortOn`. We could make specific ones for `sortOn {fst,snd}` or just a general warning with some note regarding expensive comparison functions.

**Comment by ndmitchell** [comment]
I'm not keen on recommending sortWith since its in GHC.Exts, which is not something people should use as standard. If sortOn has poor performance I'm fine with not recommending it, but that probably means these hints die.

**Comment by sjakobi** [comment]
> I'm not keen on recommending sortWith since its in GHC.Exts, which is not something people should use as standard.

Can you expand on why people shouldn't use it? I would agree that relying on `GHC.Exts` at least feels less comfortable than depending on e.g. `Data.List`.

OTOH, hlint already recommends GHC-specific "extensions", such as `LambdaCase`. I'm not sure why `sortWith` should be handled differently.

**Comment by ndmitchell** [comment]
The fact that GHC.Exts things are in base is a wart. Things that are in them and useful should be moved into normal base too. I've never seen anyone recommend importing things from GHC.Exts unless they were doing low-level GHC hackery, so it feels like a community norm - albeit one that is not documented.

In contrast, I'd say LambdaCase was an extension of general utility, with a clean specification, that happens to be implemented by GHC. It's not a GHC-specific extension. I don't think I recommend any of those.

**Comment by sjakobi** [comment]
Thanks for explaining your view! :)

I should make a proposal to move `sortWith` into `Data.List` then. There's already a bit of discussion in https://gitlab.haskell.org/ghc/ghc/issues/12044.

**Comment by ndmitchell** [comment]
I'm going to stick to the principle of not recommending anything in GHC.*, since these functions are a bit of a weird set, which I think should be migrated to base if they are useful. Feel free to raise the proposal to move them.

**Comment by sjakobi** [comment]
> I'm going to stick to the principle of not recommending anything in GHC.*, since these functions are a bit of a weird set, which I think should be migrated to base if they are useful.

To be clear, `GHC.Exts` is in `base`. I get your point though.

**Comment by ndmitchell** [comment]
Yep, _real_ base 😉

**Comment by juhp** [comment]
> I should make a proposal to move `sortWith` into `Data.List` then.

+1

> There's already a bit of discussion in https://gitlab.haskell.org/ghc/ghc/issues/12044.

I can't see discussion, but that ticket is suggesting the opposite thing.

**Comment by juhp** [comment]
Can we just drop the hint to use sortOn for now?

**Comment by ndmitchell** [comment]
Sure.

**Comment by ndmitchell** [comment]
Having `reverseSort` seems sensible. I removed the suggestion to use sortOn in 39334297702e4f98bf0c9d4eabfd914c216fc4dd

**Comment by juhp** [comment]
I need to correct the benchmark data I posted above: as Roman [kindly pointed out](https://ro-che.info/articles/2016-04-02-descending-sort-haskell#why-reverse) my "corrected" benchmark was actually only timing `reverse` not `reverse . sort`.  Here is are updated results:

```
benchmarking sort
time                 109.8 μs   (108.9 μs .. 110.9 μs)
                     0.999 R²   (0.999 R² .. 1.000 R²)
mean                 109.2 μs   (108.8 μs .. 110.3 μs)
std dev              2.209 μs   (1.391 μs .. 3.663 μs)
variance introduced by outliers: 15% (moderately inflated)

benchmarking reverse . sort
time                 206.2 μs   (203.3 μs .. 209.8 μs)
                     0.998 R²   (0.998 R² .. 0.999 R²)
mean                 202.6 μs   (200.9 μs .. 204.9 μs)
std dev              6.621 μs   (5.120 μs .. 8.271 μs)
variance introduced by outliers: 29% (moderately inflated)

benchmarking sortBy
time                 115.0 μs   (114.1 μs .. 116.1 μs)
                     0.999 R²   (0.999 R² .. 1.000 R²)
mean                 114.2 μs   (113.8 μs .. 114.9 μs)
std dev              1.761 μs   (1.174 μs .. 2.673 μs)

benchmarking sortOn
time                 697.1 μs   (683.4 μs .. 707.5 μs)
                     0.998 R²   (0.997 R² .. 0.999 R²)
mean                 677.3 μs   (672.3 μs .. 685.0 μs)
std dev              20.58 μs   (14.56 μs .. 29.17 μs)
variance introduced by outliers: 21% (moderately inflated)
```

Anyway it doesn't change the conclusion that `sortOn` is actually quite slow.
