### ISSUE TITLE
Suggest explicit `DerivingStrategies` for newtypes

### ISSUE THREAD

**Issue by clementd-fretlink** [ndmitchell/hlint#682]
The behaviour of automatically derived instances for `newtype`s depend on the enabled extensions. Even though the process is deterministic, it is hard to know the actual behaviour just by looking at the code. As a concrete example, when deriving JSON instances, a newtype can either be seen as just a wrapper (when using `GeneralizedNewtypeDeriving`) or as a 1-field record (when using `DeriveAnyClass` and generic derivation). Errors because of this come up regularly in my team.

Thankfully, the [`DerivingStrategies`](https://gitlab.haskell.org/ghc/ghc/wikis/commentary/compiler/deriving-strategies)  extension allows to explicitly specify how the instances should be derived.

An optional hint suggesting to always put explicit strategies when deriving instances on a newtype could be quite helpful (we currently enforce it manually through code review, but automated help is always welcome).

**Comment by ndmitchell** [comment]
Agreed, I had great problems with this in previous teams. I'd welcome a patch - it has to be an off-by-default hint, but a most welcome one.

**Comment by clementd-fretlink** [comment]
Perfect, I'll give it a shot then.

**Comment by divarvel** [comment]
I came up with a patch. It's not 100% satisfying yet, but the gist of it is there

**Comment by clementd-fretlink** [comment]
Fixed by #683
