### ISSUE TITLE
Parse error on kind synonym

### ISSUE THREAD

**Issue by peddie** [ndmitchell/hlint#687]
The following module
```
module A where

type Foo = * -> *
```
loads successfully in GHCI 8.6.3, but hlint v2.1.24 fails to parse it with
```
A.hs:3:12: Error: Parse error
Found:
    module A where
    
  > type Foo = * -> *
```

**Comment by peddie** [comment]
Upstream issue can be found [here](https://github.com/haskell-suite/haskell-src-exts/issues/435).

**Comment by ndmitchell** [comment]
This is one where #645 solves it entirely (I just checked), cc @shayne-fletcher-da

**Comment by ndmitchell** [comment]
Solved in the next release.
