### ISSUE TITLE
declName to return Maybe String + comment on what the function does

### ISSUE THREAD

**Issue by googleson78** [ndmitchell/hlint#706]
Looking at the function `GHC.Util.declName` it seems to only return names for declarations that you would want to report (aka declarations that create new binders, not ones that refer to already existing binders).

What do you think about changing its return type to `Maybe String`, to make this more explicit, and adding a comment explaining the logic behind the function?

(of course I volunteer to do this if you agree)

**Comment by ndmitchell** [comment]
If you think its a good idea, go for it. Sounds entirely plausible, and writing a comment is never a bad idea!
