### ISSUE TITLE
Parse error with TypeApplications

### ISSUE THREAD

**Issue by chreekat** [ndmitchell/hlint#709]
Specifically, in a module that defines operators that use `@`:

```
[b@fuzzbomb:~/Projects/chreekat.net]$ ghc -V
The Glorious Glasgow Haskell Compilation System, version 8.6.4

[b@fuzzbomb:~/Projects/chreekat.net]$ hlint --version
HLint v2.2, (C) Neil Mitchell 2006-2019

[b@fuzzbomb:~/Projects/chreekat.net]$ cat typeapp.hs
{-# LANGUAGE TypeApplications #-}

x @: y = x + y

main = print @Int (3 @: 4)

[b@fuzzbomb:~/Projects/chreekat.net]$ runghc typeapp.hs
7

[b@fuzzbomb:~/Projects/chreekat.net]$ hlint typeapp.hs
typeapp.hs:3:4: Error: Parse error
Found:
    {-# LANGUAGE TypeApplications #-}

  > x @: y = x + y

    main = print @Int (3 @: 4)


1 hint

```

**Comment by ndmitchell** [comment]
Thanks. Will have to see if this also happens with the new GHC parser, which might be the solution.

**Comment by chreekat** [comment]
Oh right, I neglected to show the versions of those packages I used.

```
$ for i in ghc-lib-parser haskell-src-exts haskell-src-exts-util; do ghc-pkg list $i; done | grep '^ '
    ghc-lib-parser-8.8.0.20190424
    haskell-src-exts-1.21.0
    haskell-src-exts-util-0.2.5
```

Those are the latest on Hackage, if I'm not mistaken.

**Comment by ndmitchell** [comment]
At the moment HLint uses both the GHC parser and the HSE parser, so you get a parse error if either fails. Soon we'll get rid of the HSE parser, and if the GHC parser already works, we'll be good. Something to test as part of #645

**Comment by ndmitchell** [comment]
Confirmed works with HEAD that doesn't use HSE for parsing, so fixed in the next release.

**Comment by chreekat** [comment]
Nice!
