### ISSUE TITLE
Feature request: Encourage CamelCase source file names

### ISSUE THREAD

**Issue by mcandre** [ndmitchell/hlint#71]
`runghc`/`runhaskell` is happy to load scripts with names like `hello.hs` and `littlebobbytables.hs`. But if you want to import module `Hello` or `LittleBobbyTables` into other code, `ghc`/`ghci` has a hard time finding it; GHC only searches for the module in `<ModuleName>.hs`/`<ModuleName>.lhs` by default.

For this reason, it would be nice to encourage Haskell programmers to use the same name for their source files as their module names. Would you consider adding an HLint rule to that effect?

**Comment by ndmitchell** [comment]
I think this should be a GHC warning, or a better error message. There are lots of legit reasons to want non camel case filenames, and GHC would be much better placed to tell you what you did wrong. I agree the error message sucks, but we can improve it for more people if we fix GHC.
