### ISSUE TITLE
Function to run hlint directly on sources

### ISSUE THREAD

**Issue by vrom911** [ndmitchell/hlint#727]
At the moment `hlint` function take the list of paths to the files. Is there a way to run HLint on the content of the source files instead?

**Comment by ndmitchell** [comment]
See the example at the top of https://hackage.haskell.org/package/hlint-2.2.2/docs/Language-Haskell-HLint4.html. Replace `parseModule` from `Nothing` to `Just contents` and it won't read the file from disk. Is that what you were after?

**Comment by vrom911** [comment]
That's exactly what I was looking for, excellent! Thanks for your help :slightly_smiling_face:
