### ISSUE TITLE
Detect redundant `let` bindings in `do` blocks

### ISSUE THREAD

**Issue by clementd-fretlink** [ndmitchell/hlint#730]
This code 

```haskell
do 
 let a = 1
 let b = 2
 pure $ a + b
```

could be rewritten as

```haskell
do
  let a = 1
       b = 2
  pure $ a + b
```

**Comment by ndmitchell** [comment]
It could, but I find that people like to do it both ways around - neither is strictly better than the other. Without a clear consensus from the community, I tend to not bother with a hint.

**Comment by clementd-fretlink** [comment]
Alright, that makes sense. I'll tell my coworkers to be more lenient then
