### ISSUE TITLE
Refactoring files without issues results in no output

### ISSUE THREAD

**Issue by TomMD** [ndmitchell/hlint#746]
A refactored file with no issues should just reproduce the original file.  Consider:

```
    % echo "main = print 2" > so.hs ; hlint - --refactor 2>/dev/null < so.hs
```

There is no output - the entire file is missing.  This is particularly painful for editor integrations, such as:

```
    % docker run --rm -it tommd/haskell
    % vi /tmp.so.hs
    main = print 1
```

And type `ta` to run the hlint plugin.

In case it needs said, everything works fine if there is at least one suggestion:

```
% echo "main = print (2)" > so.hs ; hlint - --refactor 2>/dev/null < so.hs
main = print 2
```

**Comment by ndmitchell** [comment]
Agreed. That's just odd. Patch very welcome! (I never use the refactoring stuff - it could do with a lot more tests...)
