### ISSUE TITLE
Warnings with -fwarn-incomplete-patterns

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/hlint#756]
It currently gives warnings on things such as:

```
src\Hint\Naming.hs:106:1: warning: [-Wincomplete-patterns]
    Pattern match(es) are non-exhaustive
    In an equation for `getNames': Patterns not matched: _
    |
106 | getNames (LL _ decl) = maybeToList (declName decl) ++ getConstructorNames decl
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I'm thinking LL pattern synonym needs a COMPLETE pragma? https://gitlab.haskell.org/ghc/ghc/wikis/pattern-synonyms/complete-sigs

CC @shayne-fletcher-da

**Comment by shayne-fletcher-da** [comment]
Thank-you. I'll pick it up. Leave it with me.

**Comment by shayne-fletcher-da** [comment]
Despite contradictory documentation in the Wiki page referenced above, it appears that the `COMPLETE` pragma must be associated with the defining module of the pattern synonym.
```
    • Orphan COMPLETE pragmas not supported
      A COMPLETE pragma must mention at least one data constructor
      or pattern synonym defined in the same module.
 ```

**Comment by shayne-fletcher-da** [comment]
Worked around for the existing code base in https://github.com/ndmitchell/hlint/pull/757. I'll look into an upstream fix.

**Comment by ndmitchell** [comment]
Shame - never mind though, let's close this issue then.
