### ISSUE TITLE
Suggest camelCase for more identifiers

### ISSUE THREAD

**Issue by guibou** [ndmitchell/hlint#763]
As I understood the code, camel case is checked only for exposed identifiers.

Can it be also suggested for other identifiers, such as variable name.

I'd like the following to suggest to rewrite `x_y` to `xY`, however for now hlint `2.2.2` does nothing:

```
fooBar = let
  x_y = 10
  in x_y
```

**Comment by ndmitchell** [comment]
That's deliberate. The number of people who like non-camel-case identifiers is relatively high. I can't see it likely making this check catch more things by default, given that it's already catching more than a lot of people like. In a way choosing a non-camel-case local identifier doesn't have much impact, so is less of a problem.

**Comment by guibou** [comment]
Thank for the answer. Your point is valid. I'm closing.

**Comment by ghorn** [comment]
Are you interested in an off-by-default check for non-exposed identifiers? I'm not aware of any other off-by-default checks in hlint. Otherwise we'll find another way to lint for this in our codebasel.

**Comment by ndmitchell** [comment]
The problem is at the moment all the off-by-default hints have to be applied always, and then are ignored later in the pipeline. Checking this properly on all variables is quite expensive (I had it doing that very originally), so not suitable even as off by default, unfortunately.

**Comment by ghorn** [comment]
Thank you, understood.
