### ISSUE TITLE
* in .gitignore

### ISSUE THREAD

**Issue by googleson78** [ndmitchell/hlint#764]
As of right now (master is at 0872489c3b23d660cd24102929838b3458cab327), `*` is present in `.gitignore`. This is a bit weird and it really messes with my file searching setup. It seems to have been introduced (unintentionally?) in ebb61450e50abf376814d87f593fdb15ae042256. @shayne-fletcher-da, would it be fine to remove (since you added it)?

**Comment by shayne-fletcher-da** [comment]
That's weird. Those patterns are supposed to get emacs temp files like `.#Foo.hs#` and `#Bar.hs#`. I have no issues removing them but they got added because their absence allowed me to commit rubbish! :)

**Comment by googleson78** [comment]
Yeah, those are fine. I mean this thing - https://github.com/ndmitchell/hlint/commit/ebb61450e50abf376814d87f593fdb15ae042256#diff-a084b794bc0759e7a6b77810e01874f2R3 , `*` is in there too!

**Comment by shayne-fletcher-da** [comment]
Oh! Oh my goodness. That is clearly wrong. I shall raise a PR immediately. Sorry!

**Comment by googleson78** [comment]
Thanks! Happens to everyone :sweat_smile:

**Comment by shayne-fletcher-da** [comment]
> Thanks! Happens to everyone 😅

😢. Here's the fix!! https://github.com/ndmitchell/hlint/pull/765.
