### ISSUE TITLE
HLint recommends to change FunctionalDependencies to MultiParamTypeClasses

### ISSUE THREAD

**Issue by phadej** [ndmitchell/hlint#768]
... which is technically correct, but I'd prefer to almost always use `FunctionalDependencies`
(and in fact get a hint if there's a MultiParamTypeClass defined without any FunDep).

Is there a way to configure unused language pragma hints *per pragma*? Specifically in my case, "if there are multiparamtypeclass instances, fundep is fine"/

**Comment by ndmitchell** [comment]
Why do you prefer to use a more powerful extension that you don't actually use? Generally speaking, preferring the most restrictive extension that meets your needs makes sense.

**Comment by phadej** [comment]
In short, I'd need a proper IDE, so when I move code around I don't need to weaken`FunctionalDependencies` to `MultiParamTypeClasses` manually. In cases where HLint suggest to remove an extension like `DeriveFunctor` e.g., it's simpler to do.

**Comment by ndmitchell** [comment]
You're in luck! https://github.com/digital-asset/ghcide is now out. I know @shayne-fletcher-da has been working on an HLint plugin that fits together with it. Not sure how far away that is.

I think if there is a feature to add to HLint, it would be ignoring unused warnings extension warnings in certain cases. Currently they all have the same name, so you have to ignore all of them, or none of them, not on an extension by extension basis.

**Comment by shayne-fletcher-da** [comment]
Thanks for the ping @ndmitchell, @phadej. You can track progress on integration of an HLint pluging for ghcide here https://github.com/digital-asset/ghcide/issues/104.

**Comment by phadej** [comment]
a proper IDE was slightly sarcastic comment, though I do value your work on `ghcide`.

I guess this is not going to be even configurable, I'm closing this issue.
