### ISSUE TITLE
Using createModuleEx with source fragments in IHaskell

### ISSUE THREAD

**Issue by vaibhavsagar** [ndmitchell/hlint#772]
I'm having trouble adapting IHaskell's use of HLint to the new interface provided by `2.1.18` onwards, and especially struggling to construct the `ModuleEx` that is now required. It seems like I could create a dummy `ModuleEx` with empty fields for the new `ghc-lib-parser`-provided fields, but this seems brittle and bound to break when you switch things over to operate on the newer representation. [Here](https://github.com/gibiansky/IHaskell/blob/ac0882dc39d27fbb7f068834f5f111ad1b2cd340/src/IHaskell/Eval/Lint.hs#L58-L60) is what we currently have. I'd appreciate any help or suggestions you are able to offer.

**Comment by ndmitchell** [comment]
You probably need to go via parseModuleEx - that's the only way to enable the majority of hints - so you end up rendering it to a string and reparsing. Unfortunate, but there's no other way at the moment. Once the GHC migration is finished, you'll be able to do it with just a ghc-api Module.

If you would actually use a function that took both a HSE module and a GHC module as arguments I'd provide one.
