### ISSUE TITLE
Enable linking with ghc (not ghc-lib-parser) when building with 8.8.1

### ISSUE THREAD

**Issue by shayne-fletcher-da** [ndmitchell/hlint#773]
To pave the way for HLint integration with ghcide, enable linking against package ghc rather than `ghc-lib-parser` if building with ghc-8.8.1 (see https://github.com/digital-asset/ghcide/issues/104).

Roughly I think that means,
- Remove the use of package imports for `ghc-lib-parser`;
- Write a little Cabal logic to switch between package `ghc-lib-parser` and `ghc` depending on the compiler version.

**Comment by ndmitchell** [comment]
Sounds great. Are you volunteering or is this one you want to punt on?

**Comment by shayne-fletcher-da** [comment]
> Sounds great. Are you volunteering or is this one you want to punt on?

I volunteer. Not a big job. Feel free to assign me.

**Comment by ndmitchell** [comment]
Done - although really just wanting an idea if I archive it from my inbox, or just snooze it for a week every week for the next few months :)

**Comment by shayne-fletcher-da** [comment]
I'm putting this near to the top of my stack so PR should be coming in the next two - three days.
