### ISSUE TITLE
"Avoid reverse" changes stability

### ISSUE THREAD

**Issue by ChickenProp** [ndmitchell/hlint#792]
For example,

    λ> reverse $ sortOn fst [(1, 2), (1, 3)]
    [(1,3),(1,2)]
    λ> sortOn (Down . fst) [(1, 2), (1, 3)]
    [(1,2),(1,3)]

Specifically, the second is stable, while the first reverses the order of comparing-equal elements. ("Anti-stable?")

Is it worth adding a note for these rules?

**Comment by ndmitchell** [comment]
Very true, there is a slight semantic difference, and a Note would be appropriate. None of the existing notes seem applicable though, and I'm not sure if adding one specialised to StableSort is a good idea or not. Any suggestions what to name the Note?

**Comment by ChickenProp** [comment]
I think my default inclination would be simply `note: stabilizes sort order`.

**Comment by ndmitchell** [comment]
That's much more sensible than what I was going to do. Done and pushed.
