### ISSUE TITLE
QUESTION: hlint --refactor missing refactor

### ISSUE THREAD

**Issue by monkoose** [ndmitchell/hlint#804]
Linux
stack
GHC 8.6.5
HLint 2.1.26

When i try this command `hlint --refactor src` or `stack exec -- hlint --refactor src` it returns error
```
hlint: Could not find refactor
Tried with: refactor

CallStack (from HasCallStack):
  error, called at src/HLint.hs:251:20 in hlint-2.1.26-IuMN8edws1DBXpGceL1aAV:HLint
```
Reinstalling hlint doesn't help. Any ideas how to fix this?
Thank You.

**Comment by ndmitchell** [comment]
See https://github.com/ndmitchell/hlint#automatically-applying-hints, in particular:

> In order to do this, it is necessary to have the refactor executable on you path. refactor is provided by the apply-refact package, it uses the GHC API in order to transform source files given a list of refactorings to apply. Hlint directly calls the executable to apply the suggestions.

So cabal install apply-refact first and make sure it's on your $PATH.

**Comment by monkoose** [comment]
Yes, it works.
