### ISSUE TITLE
foldMap/map hints

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/hlint#811]
foldMap f . map g => foldMap (f . g) I think. Ditto for fmap in the second fold, I think. Check and add if true.

**Comment by josephcsible** [comment]
Yes, that's true. See under "which implies that" at http://hackage.haskell.org/package/base-4.12.0.0/docs/Data-Foldable.html#t:Foldable

**Comment by ndmitchell** [comment]
Thanks, I copied all the ones from the docs.
