### ISSUE TITLE
Unicode parse error

### ISSUE THREAD

**Issue by georgefst** [ndmitchell/hlint#823]
```
(→) = ()
```
causes a parse error without any extensions. I would expect this only when `-XUnicodeSyntax` is on.

In my use case, this is a (very) mild inconvenience.

**Comment by josephcsible** [comment]
It seems that that's just on by default. You can pass `-XNoUnicodeSyntax` to hlint to make it work.

**Comment by georgefst** [comment]
Ah, thanks. I hadn't realised that `hlint` turned any extensions on by default. To be fair, now that I look, that is quite clearly documented.
