### ISSUE TITLE
hlint-2.2.3 regression: cannot parse "infixr 4 <%@~" in .hlint.yaml

### ISSUE THREAD

**Issue by RyanGlScott** [ndmitchell/hlint#842]
If you take the following `.hlint.yaml` file:

```yaml
- fixity: "infixr 4 <%@~"
```

And use it to lint the following file:

```hs
(<%@~) :: a -> b -> IO ()
_ <%@~ _ = return ()

main :: IO ()
main = () <%@~ ()
```

It will succeed on `hlint-2.2.2` but fail to parse on `hlint-2.2.3` or later:

```
$ ./hlint-2.2.2/hlint Bug.hs
No hints

$ ./hlint-2.2.3/hlint Bug.hs
hlint: user error (Failed to read YAML configuration file /home/rgscott/Documents/Hacking/Haskell/.hlint.yaml
  Aeson exception:
Error in $: Error when decoding YAML, Failed to parse Parse error: <%, when parsing:
  infixr 4 <%@~
Along path: root 0 fixity
When at: String
- fixity: infixr 4 <%@~
)
```

This bug breaks `lens`' CI. See [here](https://travis-ci.org/ekmett/lens/jobs/641808902#L1897) for an example of a failing build.

**Comment by ndmitchell** [comment]
Thanks for the report. @shayne-fletcher-da - is this related to the move to GHC for parsing these things?

**Comment by shayne-fletcher** [comment]
@ndmitchell never say never but it doesn't look like it. The parse error is originating from HSE in this case. Specifically, `parseHSE` called from `parseFixity` called form `parseConfigYaml`.

**Comment by RyanGlScott** [comment]
Good catch. A more minimal example that only depends on `haskell-src-exts` is this:

```hs
-- Bug.hs
infixr 4 <%@~
(<%@~) :: a -> b -> IO ()
_ <%@~ _ = return ()

main :: IO ()
main = () <%@~ ()
```
```
$ cabal v2-repl -b haskell-src-exts --constraint=haskell-src-exts==1.23.0
Resolving dependencies...
Build profile: -w ghc-8.8.2 -O1
In order, the following will be built (use -v for more details):
 - fake-package-0 (lib) (first run)
Configuring library for fake-package-0..
Preprocessing library for fake-package-0..
Warning: No exposed modules
GHCi, version 8.8.2: https://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /home/rgscott/.ghci
Loaded GHCi configuration from /tmp/cabal-repl.-15019/setcwd.ghci
λ> import Language.Haskell.Exts
λ> parseFileWithExts [] "Bug.hs"
ParseOk (<elided>)
λ> parseFileWithExts [EnableExtension XmlSyntax] "Bug.hs"
ParseFailed (SrcLoc "Bug.hs" 2 10) "Parse error: <%"
```

This only started to manifest in `hlint-2.2.3` because of [this commit](https://github.com/ndmitchell/hlint/commit/e7e1125733be95e5d17e7ba22a9a54aae181fcd9#diff-36de94d61938045e00caf8362a81dff4), which enabled more extensions when parsing things with `parseHSE`. One of the extensions that was enabled was, you guessed it, `XmlSyntax`.

(Also, I had no idea `XmlSyntax` was a thing until just now.)

**Comment by ndmitchell** [comment]
Thanks for the detective work. `XmlSyntax` should definitely be on the really bad extensions list! The reason HSE was developed was for a thesis which added Xml syntax into Haskell. It's a custom HSE-only extension that hasn't been used by anyone in ages!

**Comment by ndmitchell** [comment]
I put those extensions in the really bad pile, and testing it now it works. I'll make a release later today.

**Comment by shayne-fletcher** [comment]
![skull](https://user-images.githubusercontent.com/1500167/73196868-647ce900-40fe-11ea-8742-b5803b8da60d.png)
