### ISSUE TITLE
Can't restrict head without restricting NE.head

### ISSUE THREAD

**Issue by josephcsible** [ndmitchell/hlint#861]
If I restrict the `head` function, my intention is to restrict only the bad one from `Prelude`. However, if I do `import qualified Data.List.NonEmpty as NE` and then use `NE.head`, hlint flags that one too.

**Comment by ndmitchell** [comment]
If you restrict `Prelude.head` does that work? It should then infer that NE.head is definitely not Prelude.head, and ignore it.

**Comment by josephcsible** [comment]
Well, it does stop matching `NE.head` when I do that, but it stops matching the unqualified `head` too!

**Comment by ndmitchell** [comment]
That sounds like a bug. The Scope stuff is meant to mean that if `Prelude` is in scope (and it implicitly is), then `Prelude.head` should match. I've no idea if it's always been broken, or got broken during the migration to the ghc-lib parser.
