### ISSUE TITLE
hlint does not install on windows due to old-time dependency

### ISSUE THREAD

**Issue by Kamayuq** [ndmitchell/hlint#885]
Can you replace the old-time dependency as it is not compatible with a standard windows installation and requires MinGW+MSYS or Cygwin, which I have no intention of installing. 

Failed to install old-time-1.1.0.3
Build log ( C:\Users\khipu\AppData\Roaming\cabal\logs\ghc-8.6.5\old-time-1.1.0.3-2XkcGgLYS3G4Bt8PCBG9iL.log ):
Configuring old-time-1.1.0.3...
cabal.exe: The package has a './configure' script. If you are on Windows, This
requires a Unix compatibility toolchain such as MinGW+MSYS or Cygwin. If you
are not on Windows, ensure that an 'sh' command is discoverable in your path.
cabal: Leaving directory 'C:\Users\khipu\AppData\Local\Temp\cabal-tmp-96\old-time-1.1.0.3'

**Comment by ndmitchell** [comment]
You can install it using Stack just fine, or grab a binary from the releases. Unfortunately the old-time dependency is not in HLint, but as a dependency of cpphs by @malcolmwallace. I'd love for him to migrate away from old-time!

**Comment by Kamayuq** [comment]
Does Haskell have something like cargo-deny (for rust) to manage package dependencies? Its for example good to find and clean multiple different versions of the same package are otherwise bad new for compile times. Unwanted licenses or other bad behavior etc.

**Comment by ndmitchell** [comment]
Not that I know - but in this case the old-time dependency is nothing surprising, and the dependency on cpphs was added back when old-time was called simply "time".

**Comment by ndmitchell** [comment]
Fixed upstream - see https://github.com/malcolmwallace/cpphs/issues/15
