### ISSUE TITLE
Generate explicit module export lists / minimal import lists

### ISSUE THREAD

**Issue by jrp2014** [ndmitchell/hlint#908]
GHC has a `-ddump-minimal-imports` flag. Would it be possible to use the `hlint` apparatus to write a new app to apply the minimal imports (optionally ignoring Prelude, perhaps) generated automatically?

For bonus points, it should also be possible to use the set of minimal imports across a project to add explicit export lists to each module using the minimal import lists.

Of course, `weeder` does some of this at the module level, but not the module contents level.

Presumably, this would help faster compilation and provide GHC with better optimization opportunities.

Undoubtedly the automatically-generated results would need hand tweaking, but I think that it might be a great help to some older code bases that have developed a certain amount of cruft that this sort of analysis could help improve.  Doing it by hand, with a shell script or two would be one approach, but it would be good to have something a bit more robust (eg, preserving comments).

Perhaps someone has already done this.

**Comment by googleson78** [comment]
This seems more like `ghcide` territory to me - it can already add imports for example (iirc)

**Comment by ndmitchell** [comment]
I can see the use of a tool, but the information needed for it isn't the information that HLint has, and the approach of modifying the code like that isn't the core focus of what HLint does. I suggest a separate tool, a Ghcide plugin, or a dedicated tool.

**Comment by jrp2014** [comment]
Thanks.  Understood.  I'll leave a message on the GHCIDE repo.
