### ISSUE TITLE
Missing fixities

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/hlint#913]
From @yairchu on https://github.com/ndmitchell/hlint/commit/38574f067fdeb6782c08ba38c9afe26d5577fb30#commitcomment-37846765

`GhclibParserEx.baseFixities` is missing most of the fixities defined in the removed `baseNotYetInHSE`: `<>`, `<|`, `<$~>`, `$>`, `:~:`, `:~~:`, and `Compose`.

I noticed it by getting false hints involving `<>`.

**Comment by shayne-fletcher** [comment]
The definitions for prelude and base came via Refact. We never actually checked that they didn't contain these. Will get it fixed today!
