### ISSUE TITLE
Suggest f = g . h for f x = g (h x)?

### ISSUE THREAD

**Issue by zliu41** [ndmitchell/hlint#936]
hlint currently suggests `g . h` for `\x -> g (h x)`, and `f = g` for `f x = g x`. So it seems to me a good idea to suggest `f = g . h` for `f x = g (h x)`. But I'd like to double check before implementing it. cc @ndmitchell

**Comment by ndmitchell** [comment]
HLint originally did suggest that warning, but it wasn't well liked, and was the most disabled hint by some margin. The first is only suggested if you have an explicit lambda, which people do like to get rid of, while people tend to not mind that extra `x` on the end of a function definition so much. So no, probably not a good idea to add, but it seemed like it to me originally!
