### ISSUE TITLE
Release HLint 3.0

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/hlint#942]
The next release deserves the title HLint 3.0. What needs doing first?

* We need to build with GHC 8.10, which requires polyparse: https://github.com/haskell-infra/hackage-trustees/issues/259
* We need to have apply-refact working and being tested, which requires: https://github.com/mpickering/apply-refact/pull/54 and potentially a GHC 8.8 port

Anything we need to do from the HLint side?

**Comment by alanz** [comment]
> deserves the title HLint 3.0

Because haskell-src-exts is removed?

**Comment by ndmitchell** [comment]
> Because haskell-src-exts is removed?

Yes, and the knock on effect that it changes the API entirely and we've removed deprecated features that were holding us back. The changelog lists breaking changes with a `*` in front of them, so its a pretty long list. https://github.com/ndmitchell/hlint/blob/master/CHANGES.txt

**Comment by GeorgeCo** [comment]
Thanks for all your work on this so far! Now that  mpickering/apply-refact#54 would it be possible to do HLint 3.0 soon?

**Comment by ndmitchell** [comment]
The only thing now blocking us is my health - there are one or two issues I need to read, and I need to be recovered from COVID and fully functional for a few days. Hopefully not long now!

**Comment by GeorgeCo** [comment]
Very sorry to hear that you have Covid! I wish you a speedy recovery.
Obviously HLint 3.0 can wait.

All the best,
George

**Comment by ndmitchell** [comment]
I've gone through all the issues and PR's I had on my list, so I think it's now ready to go. Assuming no one says otherwise, I'll aim to release at some point over the weekend.

**Comment by GeorgeCo** [comment]
more importantly, I assume you're recovered? That's great news!

**Comment by ndmitchell** [comment]
Released and blogged https://neilmitchell.blogspot.com/2020/05/hlint-30.html. Thanks everyone who contributed!

I've now left the house for the first time in a month two days ago, am no longer infectious, but still suffering some of the lingering after-effects. Can't complain, but expecting to remain below-par for a while.
