### ISSUE TITLE
Hlint incorrectly identifies scope of shadowing variables

### ISSUE THREAD

**Issue by expipiplus1** [ndmitchell/hlint#953]
Perhaps this will be a non-issue after moving away from haskell-src-exts

Consider 

```haskell
foo = for [] $ \n -> bar n >>= \case
  Just n  -> pure ()
  Nothing -> baz n
```

Hlint's suggestion doesn't compile because `n` is out of scope.

```
A.hs:1:16: Suggestion: Use >=>
Found:
  \ n
    -> bar n
         >>=
           \case
             Just n -> pure ()
             Nothing -> baz n
Perhaps:
  (bar
     Control.Monad.>=>
       (\case
          Just n -> pure ()
          Nothing -> baz n))
```

if the pattern `Just n` does not contain exactly `n` then hlint suggests nothing.

**Comment by shayne-fletcher** [comment]
Confirmed to exhibit on HEAD.

**Comment by ndmitchell** [comment]
The free variable computation we use doesn't come from GHC or HSE, it's our own approximation. And that approximation was a bit off for `\case` - so I copied the variant for `case` and that fixes the bug. I confess that the subtle details of why the code differs eludes me - the whole free variable thing needs a healthy look at in future - but it works for now.

**Comment by expipiplus1** [comment]
Thanks!
