### ISSUE TITLE
hlint generates "- infix:" but expects "- fixity:"

### ISSUE THREAD

**Issue by ju1m** [ndmitchell/hlint#955]
hlint's `README.md` suggests that I can:
> put all the fixity declarations in a `.hlint.yaml` file as `- fixity: "infixr 5 !@%$"`. You can also use `--find` to automatically produce a list of fixity declarations in a file.

But `hlint --find` outputs `- infix:` entries instead of `- fixity:` entries, this is a bit unfortunate and disturbing.

Though not a big problem, as it just requires to use a `sed` substitution:
`
hlint --find . | sed -ne 's/^- infix:/- fixity:/p' | sort -u >>.hlint.yaml
`

```
$ hlint --version
HLint v2.2.11, (C) Neil Mitchell 2006-2020
```

**Comment by ndmitchell** [comment]
Thanks for the report! I've made it output fixity. Will be available in the next release.
