### ISSUE TITLE
Support for ghc-8.10.1?

### ISSUE THREAD

**Issue by peti** [ndmitchell/hlint#959]
Will there be a new release of hlint soon that accepts ghc-lib-parser-ex version 8.10.x? I can build hlint in Nixpkgs right now, too, but it's a bit awkward because the ghc-lib-parser versions I have to use don't match the compiler.

**Comment by ndmitchell** [comment]
Yes, in the next day or so.

**Comment by ndmitchell** [comment]
Released!
