### ISSUE TITLE
"Use section" suggestion in hlint-3.0 doesn't parse

### ISSUE THREAD

**Issue by RyanGlScott** [ndmitchell/hlint#963]
If you lint the following code with `hlint-3.0`:

```hs
module Bug where

f :: [(Char, String)]
f = map (flip (,) "a") "123"
```

You'll get the following suggestions:

```
$ hlint --version
HLint v3.0.1, (C) Neil Mitchell 2006-2020
$ hlint Bug.hs
Bug.hs:4:9-22: Suggestion: Use section
Found:
  (flip (,) "a")
Perhaps:
  (`(,)` "a")

Bug.hs:4:10-21: Warning: Use tuple-section
Found:
  flip (,) "a"
Perhaps:
  (, "a")
Note: may require `{-# LANGUAGE TupleSections #-}` adding to the top of the file

2 hints
```

The first suggestion recommending ```(`(,)` "a")``` is completely bogus, since GHC won't even parse that:

```
Bug.hs:4:11: error: parse error on input ‘(’
  |
4 | f = map (`(,)` "a") "123"
  |           ^
```

Note that this suggestion only started to appear in `hlint-3.0`. In `hlint-2.2.11`, only the latter suggestion is given:

```
$ hlint --version
HLint v2.2.11, (C) Neil Mitchell 2006-2020
$ hlint Bug.hs
Bug.hs:4:10: Warning: Use tuple-section
Found:
  flip (,) "a"
Perhaps:
  (, "a")
Note: may require `{-# LANGUAGE TupleSections #-}` adding to the top of the file

1 hint
```

**Comment by ndmitchell** [comment]
Thanks! Extra check added that we aren't generating these for tuples.

**Comment by ndmitchell** [comment]
BTW, I'll release 3.0.2 tomorrow morning, with fixes for anything you find overnight, and then promote that as the new HLint 3.0 :) Thanks for your reports thusfar @RyanGlScott

**Comment by RyanGlScott** [comment]
I just tested `hlint-3.0` on all of my code, and I couldn't find anything else that looked suspicious. Thank you for the prompt fixes!

**Comment by ndmitchell** [comment]
Thanks @RyanGlScott - 3.0.2 now out which fixes everything.

**Comment by RyanGlScott** [comment]
Sigh, I spoke too soon—there is one more subtle bug that I didn't notice until I actually tried to apply it. See #965.
