### ISSUE TITLE
Wrong redundant bracket suggestion with BlockArguments.

### ISSUE THREAD

**Issue by galenhuntington** [ndmitchell/hlint#969]
This code

```haskell
{-# LANGUAGE BlockArguments #-}
foo = (Just \x -> x || x) *> Just True
```

yields this:

```
hlint.hs:2:7-38: Suggestion: Redundant bracket
Found:
  (Just \ x -> x || x) *> Just True
Perhaps:
  Just \ x -> x || x *> Just True
```

But this is plainly wrong, as the lambda will max-munch the whole line.

**Comment by ndmitchell** [comment]
Thanks for the report. Yep, a definite bug - it used to be the case that applications inside infix applications were always unnecessary brackets - but block arguments changes that. Will investigate.

**Comment by ndmitchell** [comment]
I've added an extra case that non-atomic non-apps in the RHS of an App on the LHS of an operator definitely require brackets. I'm not totally confident I've caught all the cases that BlockArguments introduces, but I definitely got the one above. Please report any other weirdities you find.
