### ISSUE TITLE
Make errors warnings, and warnings suggestions

### ISSUE THREAD

**Issue by marcusbuffett** [ndmitchell/hlint#99]
I have a file that looks like this : 

    module Tracker where
    type Tracker = [CardTracker]
    type Card = String
    data CardTracker = CardTracker {ctCard :: Card, ctEF :: Float, ctN :: Int}

    removeCard :: Card -> [CardTracker] -> [CardTracker]
    removeCard card tracker = filter (\cTracker -> ctCard cTracker /= card) tracker

If I run hlint File.hs (the file that contains this code), I get an error on the removeCard function, even though it should be a warning

**Comment by wolftune** [comment]
@ndmitchell how about "warning" and "suggestion" instead of trying to have extraneous qualifiers for a single word?

**Comment by marcusbuffett** [comment]
I'm in favor of "warning" and "suggestion" too. It's confusing when all the other linting tools use error for "will not compile, you're doing something wrong", and third party tools make the problem worse. For example, I use hlint with Syntastic. With every other language, I know not to run my code when there's a red arrow by a line, since that means error, but with hlint I have to remind myself that it's not really an error, and that my code will compile despite the red arrows that I've come to associate with "stop now, you did something wrong".

**Comment by ndmitchell** [comment]
Hmm, that's fair. So I map error to warning, and warning to suggestion? I quite like that. Anyone disagree?

**Comment by wolftune** [comment]
So, 6 months later, nobody disagrees. I find the old terminology confusing and offputting to newcomers. Please go ahead and do the fix of these terms!

**Comment by ndmitchell** [comment]
So the only remaining issue is that the final line of HLint says "No suggestions" or "12 suggestions". If we say there are now warnings and suggestions (the two types of suggestion), that doesn't make a lot of sense. Anyone got suggestions for replacement text to go there? "No tips"? "No ideas"? "No refactorings"? In the API I call it an Idea, which I think is an adequate name for the API, but a terrible name for user-facing text.

**Comment by ndmitchell** [comment]
General plan, once that niggle is resolved:

* Add Suggestion data type, with support for declaring suggestions.
* For all my internal suggestions shift error to warning, warning to suggestion.
* Keep error indefinitely, so people can declare their own priority Error suggestions.

So I don't rename, I add, and then redeclare the shipped hints.

**Comment by wolftune** [comment]
First, one internal thing that needs to stay an "error" still: "Parse error" is neither a suggestion nor a warning, it's a true error. I actually think you should reserve "error" for something going wrong like this with hlint.

Your suggestion to have three levels, suggestion, warning, error all for normal syntax lint issues, that's adding a higher resolution than you already have. It strikes me as an additional feature change, not just a renaming. If you really want to do that, you could do it, but I'd still suggest a different word than "error". I think "error" should be reserved for something unworkable, like a "Parse Error"

When there are no suggestions, warnings, or errors, I suggest "No issues, hlint approved!" or something of that sort.

**Comment by ndmitchell** [comment]
Renaming is a pain because its an API change - people using the HLint API lose a constructor and gain another, and also have a constructor remapped. People who have written their own rules with `error = ...` - would they get remapped to warning? In which case `warn` doesn't mean warning anymore, and it all gets very confusing. Introducing the new one seems reasonable.

**Comment by wolftune** [comment]
okay, I think releasing a breaking thing that people would need to update isn't crazy, but I understand not doing that.

So, go with suggestion, warning, error, rename the internal, let people do their own renaming when they want to shift to the new terms. Keep "Parse error" as an error for internal.

**Comment by ndmitchell** [comment]
Yep, having breaking changes isn't the end of the world, just best avoided if possible.

Parse error has never been an error, even now, it's a warning. That confuses a lot of people though, I'll make it an error.

**Comment by ndmitchell** [comment]
OK, all done. I'd appreciate if you can checkout HEAD and give it a whirl.

My release plan is wait til Feb (since I'm busy next week), fix #208, write a blog post announcing this change (which may have user visible impact) and also telling people that the opportunity to move to the new API is now and they'll be gone in the next major release.

**Comment by ndmitchell** [comment]
Also, I should deprecate the API's with proper `{-# DEPRECATE #-}` pieces.

**Comment by marcusbuffett** [comment]
Awesome, thank you for making this change!

**Comment by wolftune** [comment]
I'd personally wish this was released ASAP in order to get included in Stackage LTS-5 but I'm happy to see the change made at least. I'd like to help test, but a bit overwhelmed with backlog and prep for Snowdrift.coop having booth this weekend at SCALE…

**Comment by ndmitchell** [comment]
It will be a minor bump (the API doesn't change), so will make it to LTS-5.

**Comment by ndmitchell** [comment]
Now done everywhere and using #209 to track the release requirements.

**Comment by ndmitchell** [comment]
This is now out and released.
