### ISSUE TITLE
Be more careful about suggestions in the presence of unknown operators

### ISSUE THREAD

**Issue by Caagr98** [ndmitchell/hlint#993]
I have a custom operator 
```
infixl 4 <*! -- same as <$> and <*>
(<*!) :: Applicative f => f (a -> b) -> a -> f b
a <*! b = a <*> pure b
```

When used like `f =<< g <$> x <*! y`, hlint suggests changing it to `f . g =<< (x <*! y)`, which is not correct. Replacing it with `f =<< g <$> x <*> pure y` gives no such suggestion (but is more verbose!), which implies that it's related to some operators being known and not. There might be other rules that have similar problems.

**Comment by ndmitchell** [comment]
Lots of rules assume they have the correct parse tree, and I think if we ignore all those where the parse tree might be wrong we're going to lose a lot of useful hints. The solution is to make the parse tree correct:

* For things like IDE's, they can supply HLint with a pre-fixity resolved parse tree, which means the problem goes away.
* If you are using HLint from the command line add a `- fixity: "infixl 4 <*!"` definition - see https://github.com/ndmitchell/hlint/blob/master/README.md#why-doesnt-hlint-know-the-fixity-for-my-custom--operator

**Comment by Caagr98** [comment]
Yeah, that makes sense. Though I would expect it to figure out the fixities of operators defined in the same module.

**Comment by ndmitchell** [comment]
It used to take the fixities of the same module into account, but I guess not anymore. Perhaps @shayne-fletcher has an idea how we can get that back?

**Comment by shayne-fletcher** [comment]
> It used to take the fixities of the same module into account, but I guess not anymore. Perhaps @shayne-fletcher has an idea how we can get that back?

Didn't intentionally disable that feature 🤷‍♀️ I can look into restoring it. @ndmitchell would maybe be helpful if you can point me to a revision where it worked? In any case, off the top of my head, I guess we can probably extract operator definitions from the parse tree before we rejig with `applyFixities`   just before we go sniffing for hints.

**Comment by ndmitchell** [comment]
I am certain it used to work with HSE. I am not aware of it ever working with GHC. Note that in Haskell you can do things like:

```
let a ???? b = ...
     infixr ???? 3
in ...
```

Looking at the ghc-lib-parser-ex code for applyFixities, I suspect we _do_ deal with that. But we don't grab statement level fixities at the top-level, which is 99.99% of the cases. So perhaps a bug in applyFixities?

**Comment by shayne-fletcher** [comment]
No, I don't think it's a bug in `applyFixities`. If they were input, they'd be applied. It's as you say - we simply don't give the fixities encountered in the module to `applyFixities`. That's the obvious fix I'd wager.

**Comment by shayne-fletcher** [comment]
> But we don't grab statement level fixities at the top-level, which is 99.99% of the cases.

I think we are on the same page. We should do that and send them into `applyFixities`.

**Comment by shayne-fletcher** [comment]
Hmm. Correct me if I'm misunderstanding you! A couple of things : (1) I'd be surprised to hear there was a bug in `applyFixities` it's a straight port from the renamer at the end of the day (2) happy for you to assign me to this ticket for now.

**Comment by ndmitchell** [comment]
I'm messing in the code at the moment. Let me try and do it. I agree it's not a bug in applyFixities (my bad) - I was more arguing that applyFixities could suck them up itself, but that seems unnecessarily annoying.

**Comment by shayne-fletcher** [comment]
Oh! I've already half implemented it :)

**Comment by shayne-fletcher** [comment]
Shall I stop?

**Comment by ndmitchell** [comment]
@shayne-fletcher and I wrote half of it each - now added and tested. I'll make a release this evening.
